Repository sbb-design-systems/lyne-components, pull requests merged in 2024-10, with the labels that each got.

#3124 build: avoid compiling CSS comments
  .stylelintrc.json
  src/elements/autocomplete/autocomplete-base-element.scss
  src/elements/button/common/button-common.scss
  src/elements/checkbox/checkbox/checkbox.scss
  src/elements/core/styles/core/functions.scss
  src/elements/core/styles/mixins/helpers.scss
  src/elements/core/styles/mixins/lists.scss
  src/elements/core/styles/mixins/scrollbar.scss
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/normalize.scss
  src/elements/loading-indicator/loading-indicator.scss
  src/elements/notification/notification.scss
  src/elements/select/select.scss
  src/storybook/pages/home/home.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3125 fix(sbb-radio-group): avoid focusing disabled radios
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3126 fix: fix list colors
  src/elements/core/styles/mixins/lists.scss
  src/storybook/styles/list/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3135 chore: remove index file from boilerplate
  tools/generate-component/boilerplate/index.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3134 fix(sbb-image): introduce css property to configure object-fit
  src/elements/image/image.scss
  src/elements/image/image.ts
  src/elements/image/image.visual.spec.ts
  src/elements/image/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3140 fix(sbb-teaser): allow teaser usage in flexible layouts
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.stories.ts
  src/elements/teaser/teaser.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3131 fix(sbb-image): fix skipLqip mode
  src/elements/image/image.scss
  src/elements/image/image.stories.ts
  src/elements/image/image.ts
  src/elements/image/image.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3139 build: inline fonts during tests
  tools/web-test-runner/index.ts
  tools/web-test-runner/preload-fonts.ts
  tools/web-test-runner/preload-icons.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3143 fix(sbb-teaser): css variable typo
  src/elements/teaser/teaser.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3144 fix(sbb-loading-indicator): center component into his box
  src/elements/loading-indicator/loading-indicator.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3101 feat(sbb-select): implement native form support
  src/elements/checkbox/checkbox-panel/readme.md
  src/elements/checkbox/checkbox/readme.md
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/core/mixins/required-mixin.ts
  src/elements/select/readme.md
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
  src/elements/select/select.visual.spec.ts
  src/elements/slider/readme.md
  src/elements/slider/slider.ts
  src/elements/toggle-check/readme.md
  tools/docs/docs_generate.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3147 refactor: remove obsolete index.ts files
  src/elements/autocomplete-grid/autocomplete-grid-optgroup/index.ts
  src/elements/button/mini-button-group/index.ts
  src/elements/button/mini-button-group/mini-button-group.scss
  src/elements/flip-card/flip-card-details/index.ts
  src/elements/flip-card/flip-card-summary/index.ts
  src/elements/flip-card/flip-card/index.ts
  src/elements/link-list/link-list-anchor/index.ts
  src/elements/link-list/link-list-anchor/link-list-anchor.scss
  src/elements/link-list/link-list/link-list.scss
  src/elements/paginator/index.ts
  src/elements/radio-button/radio-button-panel/index.ts
  src/elements/table/table-wrapper/table-wrapper.scss
  src/elements/tabs/tab/index.ts
  src/elements/tabs/tab/tab.scss
  src/elements/teaser-product/common/teaser-product-common.scss
  src/elements/teaser-product/teaser-product/teaser-product.scss
  src/storybook/styles/typography/typo-internal.scss
  src/visual-regression-app/src/components/overview/overview.scss
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.scss
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.scss
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.scss
  src/visual-regression-app/src/components/test-case/test-case.scss
  src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3151 docs: fix SASS link in getting started docs
  docs/GETTING_STARTED.md
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3141 style: fix background-color on negative disabled buttons
  src/elements/button/common/button-common.scss
  src/elements/button/mini-button-group/mini-button-group.stories.ts
  src/elements/core/styles/mixins/buttons.scss
Labels: preview-available, ux approved, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3085 feat(sbb-file-selector): implement native form support
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/file-selector/file-selector.scss
  src/elements/file-selector/file-selector.spec.ts
  src/elements/file-selector/file-selector.ts
  src/elements/file-selector/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3130 feat(sbb-paginator): add disabled property
  src/elements/paginator/paginator.scss
  src/elements/paginator/paginator.stories.ts
  src/elements/paginator/paginator.ts
  src/elements/paginator/paginator.visual.spec.ts
  src/elements/paginator/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3155 build: remove leading pipes in docs generation
  src/elements/card/card/readme.md
  src/elements/dialog/dialog-title/readme.md
  src/elements/image/readme.md
  src/elements/navigation/navigation-section/readme.md
  src/elements/navigation/navigation/readme.md
  src/elements/overlay/readme.md
  src/elements/popover/popover/readme.md
  tools/docs/docs_generate.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3154 feat(sbb-header): introduce active state
  src/elements/header/common/header-action.scss
  src/elements/header/header-button/header-button.stories.ts
  src/elements/header/header-button/header-button.visual.spec.ts
  src/elements/header/header-button/readme.md
  src/elements/header/header-link/header-link.stories.ts
  src/elements/header/header-link/header-link.visual.spec.ts
  src/elements/header/header-link/readme.md
  src/elements/header/header/header.stories.ts
  src/elements/header/header/readme.md
Labels: preview-available, pr: peer review approved, pr: ux review approved, pr: visual review required, diff-available

#3166 build(eslint): fix ignore patterns
  eslint.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3159 build: add script to download screenshots of closed PRs
  scripts/manual-diff-check.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required

#3175 build: fix keys.js imports
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/core/a11y/focus.spec.ts
  src/elements/core/testing/private.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/form-field/form-field/form-field.spec.ts
  src/elements/header/header/header.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/select/select.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3177 build: introduce trunk based development workflow
  .github/workflows/maintenance-changelog.yml
  .github/workflows/maintenance-cherry-pick.yml
  .github/workflows/maintenance-tagging.yml
  .github/workflows/release-please.yml
  package.json
  renovate.json
  scripts/update-maintenance-issue.ts
  yarn.lock
Labels: pr: peer review required, pr: visual review required, target: 1.x

#3181 build: fix cherry picking
  .github/workflows/maintenance-changelog.yml
  .github/workflows/maintenance-cherry-pick.yml
  .github/workflows/release-please.yml
Labels: pr: peer review required, target: 1.x

#3184 build: fix token for cherry picking
  .github/workflows/maintenance-cherry-pick.yml
  .github/workflows/release-please.yml
Labels: pr: peer review required, target: 1.x

#3185 build: filter labels before cherry picking
  .github/workflows/maintenance-cherry-pick.yml
Labels: pr: peer review required, target: 1.x

#3186 Revert "build: filter labels before cherry picking (#3185)"
  .github/workflows/maintenance-cherry-pick.yml
Labels: pr: peer review required, target: 1.x

#3174 build: fix logic for SSR in React wrapper
  src/elements/core/controllers/slot-state-controller.ts
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  tools/manifest/custom-elements-manifest.config.js
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3187 style: rename animation '-time' variables to '-duration'
  src/elements/alert/alert/alert.scss
  src/elements/button/common/button-common.scss
  src/elements/calendar/calendar.scss
  src/elements/clock/clock.scss
  src/elements/container/sticky-bar/sticky-bar.scss
  src/elements/core/mixins/panel-common.scss
  src/elements/core/styles/mixins/animation.scss
  src/elements/core/styles/mixins/buttons.scss
  src/elements/core/styles/mixins/card.scss
  src/elements/core/styles/mixins/overlay.scss
  src/elements/core/styles/mixins/panel.scss
  src/elements/dialog/dialog/dialog.scss
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.scss
  src/elements/expansion-panel/expansion-panel/expansion-panel.scss
  src/elements/file-selector/file-selector.scss
  src/elements/flip-card/flip-card-details/flip-card-details.scss
  src/elements/flip-card/flip-card-summary/flip-card-summary.scss
  src/elements/flip-card/flip-card/flip-card.scss
  src/elements/form-field/form-field/form-field.scss
  src/elements/header/common/header-action.scss
  src/elements/header/header/header.scss
  src/elements/image/image.scss
  src/elements/loading-indicator/loading-indicator.scss
  src/elements/map-container/map-container.scss
  src/elements/menu/menu/menu.scss
  src/elements/navigation/common/navigation-action.scss
  src/elements/navigation/navigation-marker/navigation-marker.scss
  src/elements/navigation/navigation-section/navigation-section.scss
  src/elements/navigation/navigation/navigation.scss
  src/elements/notification/notification.scss
  src/elements/overlay/overlay.scss
  src/elements/paginator/paginator/paginator.scss
  src/elements/popover/popover/popover.scss
  src/elements/radio-button/common/radio-button-common.scss
  src/elements/selection-expansion-panel/selection-expansion-panel.scss
  src/elements/slider/slider.scss
  src/elements/stepper/step-label/step-label.scss
  src/elements/stepper/step/step.scss
  src/elements/stepper/stepper/stepper.scss
  src/elements/tabs/tab-group/tab-group.scss
  src/elements/tabs/tab-label/tab-label.scss
  src/elements/tag/tag/tag.scss
  src/elements/teaser-product/teaser-product/teaser-product.scss
  src/elements/teaser/teaser.scss
  src/elements/toast/toast.scss
  src/elements/toggle-check/toggle-check.scss
  src/elements/toggle/toggle/toggle.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available
