Repository sbb-design-systems/lyne-components, pull requests merged in 2024-06, with the labels that each got.

#2694 test: test visual regression focus without waiting
  .github/workflows/continuous-integration-secure.yml
  src/elements/core/testing/private/visual-regression-snapshot.ts
  src/elements/lead-container/lead-container.snapshot.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2705 fix(sbb-block-link): always show underline except for footer links
  src/elements/breadcrumb/breadcrumb/breadcrumb.scss
  src/elements/core/styles/mixins/link.scss
  src/elements/footer/footer.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, visual-regression-diff-available

#2706 build: fix component generation script
  eslint.config.js
  package.json
  tools/generate-component/boilerplate/component.e2e.ts
  tools/generate-component/boilerplate/component.snapshot.spec.ts
  tools/generate-component/boilerplate/component.spec.ts
  tools/generate-component/boilerplate/component.stories.ts
  tools/generate-component/boilerplate/component.ts
  tools/generate-component/boilerplate/index.ts
  tools/generate-component/index.ts
  tools/generate-component/index/component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2712 fix(sbb-image): render URL correctly with SSR
  src/elements/image/image.ssr.spec.ts
  src/elements/image/image.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2713 fix(sbb-option): correctly determine highlight state with SSR
  src/elements/option/option/option.ssr.spec.ts
  src/elements/option/option/option.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2711 refactor: change visual regression testing API
  src/elements/button/button/button.snapshot.spec.ts
  src/elements/button/button/button.visual.spec.ts
  src/elements/core/testing/private/describe-viewports.ts
  src/elements/core/testing/private/fixture.ts
  src/elements/core/testing/private/visual-regression-snapshot.ts
  src/elements/lead-container/lead-container.snapshot.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2685 feat(file-selector): add size s
  src/elements/file-selector/__snapshots__/file-selector.spec.snap.js
  src/elements/file-selector/file-selector.scss
  src/elements/file-selector/file-selector.spec.ts
  src/elements/file-selector/file-selector.stories.ts
  src/elements/file-selector/file-selector.ts
  src/elements/file-selector/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, visual-regression-diff-available

#2719 feat(sbb-lead-container): add support for sbb-alert-group
  src/elements/lead-container/lead-container.scss
  src/elements/lead-container/lead-container.stories.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/lead-container/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2718 refactor: move css logic and avoid duplications
  src/elements/checkbox/checkbox-group/checkbox-group.scss
  src/elements/checkbox/checkbox-panel/__snapshots__/checkbox-panel.spec.snap.js
  src/elements/checkbox/checkbox-panel/checkbox-panel.scss
  src/elements/checkbox/checkbox-panel/checkbox-panel.ssr.spec.ts
  src/elements/checkbox/checkbox-panel/checkbox-panel.stories.ts
  src/elements/checkbox/checkbox-panel/checkbox-panel.ts
  src/elements/checkbox/checkbox/__snapshots__/checkbox.spec.snap.js
  src/elements/checkbox/checkbox/checkbox.scss
  src/elements/checkbox/checkbox/checkbox.ts
  src/elements/checkbox/common/checkbox-common.scss
  src/elements/checkbox/common/checkbox-common.ts
  src/elements/core/mixins.ts
  src/elements/core/mixins/panel-common.scss
  src/elements/core/mixins/panel-mixin.ts
  src/elements/core/styles/_index.scss
  src/elements/radio-button/common/radio-button-common.scss
  src/elements/radio-button/radio-button-group/radio-button-group.scss
  src/elements/radio-button/radio-button-panel/__snapshots__/radio-button-panel.spec.snap.js
  src/elements/radio-button/radio-button-panel/radio-button-panel.scss
  src/elements/radio-button/radio-button-panel/radio-button-panel.ssr.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.stories.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ts
  src/elements/radio-button/radio-button/radio-button.scss
  src/elements/selection-expansion-panel/__snapshots__/selection-expansion-panel.spec.snap.js
  src/elements/selection-expansion-panel/selection-expansion-panel.scss
  src/elements/selection-expansion-panel/selection-expansion-panel.ssr.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.stories.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2722 fix(sbb-dialog): fix dialog-content z-index
  src/elements/dialog/dialog-content/dialog-content.scss
  src/elements/dialog/dialog/dialog.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2721 fix(sbb-datepicker): handle hydration correctly
  src/elements/calendar/calendar.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/datepicker/datepicker/datepicker.ssr.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2599 refactor: create base class for overlay functionality
  src/elements/autocomplete/autocomplete.ts
  src/elements/autocomplete/readme.md
  src/elements/core/base-elements.ts
  src/elements/core/base-elements/open-close-base-element.ts
  src/elements/core/interfaces.ts
  src/elements/core/interfaces/overlay-close-details.ts
  src/elements/core/mixins/update-scheduler-mixin.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/dialog/dialog/readme.md
  src/elements/menu/menu/menu.ts
  src/elements/menu/menu/readme.md
  src/elements/navigation/navigation/navigation.ts
  src/elements/navigation/navigation/readme.md
  src/elements/notification/notification.ts
  src/elements/overlay.ts
  src/elements/overlay/overlay-base-element.ts
  src/elements/overlay/overlay.ts
  src/elements/overlay/readme.md
  src/elements/popover/popover/popover.ts
  src/elements/popover/popover/readme.md
  src/elements/select/readme.md
  src/elements/select/select.ts
  src/elements/selection-panel/selection-panel.ts
  src/elements/toast/readme.md
  src/elements/toast/toast.ts
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2491 feat(sbb-stepper): introduce `sbb-stepper` component
  src/elements/core/styles/a11y.scss
  src/elements/stepper.ts
  src/elements/stepper/step-label.ts
  src/elements/stepper/step-label/__snapshots__/step-label.spec.snap.js
  src/elements/stepper/step-label/readme.md
  src/elements/stepper/step-label/step-label.scss
  src/elements/stepper/step-label/step-label.spec.ts
  src/elements/stepper/step-label/step-label.ssr.spec.ts
  src/elements/stepper/step-label/step-label.stories.ts
  src/elements/stepper/step-label/step-label.ts
  src/elements/stepper/step.ts
  src/elements/stepper/step/__snapshots__/step.spec.snap.js
  src/elements/stepper/step/readme.md
  src/elements/stepper/step/step.scss
  src/elements/stepper/step/step.spec.ts
  src/elements/stepper/step/step.ssr.spec.ts
  src/elements/stepper/step/step.stories.ts
  src/elements/stepper/step/step.ts
  src/elements/stepper/stepper.ts
  src/elements/stepper/stepper/__snapshots__/stepper.spec.snap.js
  src/elements/stepper/stepper/readme.md
  src/elements/stepper/stepper/stepper.e2e.ts
  src/elements/stepper/stepper/stepper.scss
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/stepper/stepper/stepper.ssr.spec.ts
  src/elements/stepper/stepper/stepper.stories.ts
  src/elements/stepper/stepper/stepper.ts
  src/elements/tabs/tab-title/tab-title.ts
  tools/docs/docs_generate.ts
  tsconfig.json
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: a11y review required, pr: visual review required, visual-regression-diff-available

#2725 feat(sbb-image): provide load and error events
  src/elements/core/testing.ts
  src/elements/core/testing/wait-for-image-ready.ts
  src/elements/image/image.e2e.ts
  src/elements/image/image.spec.ts
  src/elements/image/image.stories.ts
  src/elements/image/image.ts
  src/elements/image/readme.md
  src/elements/lead-container/__snapshots__/lead-container.snapshot.spec.snap.js
  src/elements/lead-container/lead-container.snapshot.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/message/__snapshots__/message.spec.snap.js
  src/elements/message/message.spec.ts
  src/elements/teaser-hero/__snapshots__/teaser-hero.spec.snap.js
  src/elements/teaser-hero/teaser-hero.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2727 build: mangle private properties in prod build to reduce size
  src/elements-experimental/vite.config.ts
  src/elements/vite.config.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2732 refactor(sbb-stepper): move setter before getter
  src/elements/stepper/stepper/stepper.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2733 fix(sbb-breadcrumb): avoid to collapse for two or fewer breadcrumbs
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.spec.ts
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2734 test(sbb-popover): stabilize popover tests
  src/elements/popover/popover-trigger/popover-trigger.spec.ts
  src/elements/popover/popover/popover.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2736 fix: fix stacked overlays inert mechanism
  src/elements/core/overlay/overlay.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2726 docs(sbb-stepper): improve stories
  src/elements/stepper/step-label/step-label.stories.ts
  src/elements/stepper/step/__snapshots__/step.snapshot.spec.snap.js
  src/elements/stepper/step/step.snapshot.spec.ts
  src/elements/stepper/step/step.stories.ts
  src/elements/stepper/stepper/__snapshots__/stepper.snapshot.spec.snap.js
  src/elements/stepper/stepper/stepper.snapshot.spec.ts
  src/elements/stepper/stepper/stepper.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2741 build: create PR for playwright deps update to check visual regression
  renovate.json
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2739 test: refactor styles to new visual regression tests
  src/elements/core/testing/private/fixture.ts
  src/elements/core/testing/private/keys.ts
  src/elements/core/testing/private/visual-regression-snapshot.ts
  src/elements/image/image.visual.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/storybook/styles/layout/layout.visual.spec.ts
  src/storybook/styles/list/list.visual.spec.ts
  src/storybook/styles/scrollbar/scrollbar.visual.spec.ts
  src/storybook/styles/typography/typography.visual.spec.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2743 test: focus links correctly on Webkit on macOS
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/core/a11y/focus.spec.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/form-field/form-field/form-field.spec.ts
  src/elements/header/header/header.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/select/select.spec.ts
  src/elements/selection-panel/selection-panel.spec.ts
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2735 test: use press instead of down for key events
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.spec.ts
  src/elements/core/base-elements/button-base-element.spec.ts
  src/elements/core/base-elements/link-base-element.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/selection-panel/selection-panel.spec.ts
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/toggle-check/toggle-check.spec.ts
  src/elements/toggle/toggle/toggle.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2748 chore: introduce eslint rule to ensure tabkey is used for sendKeys()
  tools/eslint/index.ts
  tools/eslint/test-tabkey-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2747 chore: introduce eslint rule to ensure describe() has component name as title
  eslint.config.js
  src/elements/card/card-link/__snapshots__/card-link.snapshot.spec.snap.js
  src/elements/card/card-link/card-link.snapshot.spec.ts
  tools/eslint/index.ts
  tools/eslint/test-describe-title.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2775 test(sbb-stepper): fix flickering test
  src/elements/stepper/stepper/__snapshots__/stepper.snapshot.spec.snap.js
  src/elements/stepper/stepper/stepper.snapshot.spec.ts
Labels: pr: peer review required, pr: lead review approved

#2779 fix(sbb-train-formation): hide sectors row if no sectors were defined
  src/elements/train/train-blocked-passage/__snapshots__/train-blocked-passage.snapshot.spec.snap.js
  src/elements/train/train-blocked-passage/train-blocked-passage.snapshot.spec.ts
  src/elements/train/train-formation/__snapshots__/train-formation.snapshot.spec.snap.js
  src/elements/train/train-formation/train-formation.snapshot.spec.ts
  src/elements/train/train-formation/train-formation.spec.ts
  src/elements/train/train-formation/train-formation.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2781 test: try taller standard viewport height
  src/elements/core/testing/private/describe-viewports.ts
  src/elements/image/image.visual.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2744 refactor(sbb-tab): align with sbb-stepper
  src/elements/tabs.ts
  src/elements/tabs/tab-group/__snapshots__/tab-group.snapshot.spec.snap.js
  src/elements/tabs/tab-group/readme.md
  src/elements/tabs/tab-group/tab-group.snapshot.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/tabs/tab-group/tab-group.ssr.spec.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
  src/elements/tabs/tab-group/tab-group.ts
  src/elements/tabs/tab-label.ts
  src/elements/tabs/tab-label/__snapshots__/tab-label.snapshot.spec.snap.js
  src/elements/tabs/tab-label/readme.md
  src/elements/tabs/tab-label/tab-label.scss
  src/elements/tabs/tab-label/tab-label.snapshot.spec.ts
  src/elements/tabs/tab-label/tab-label.spec.ts
  src/elements/tabs/tab-label/tab-label.ssr.spec.ts
  src/elements/tabs/tab-label/tab-label.stories.ts
  src/elements/tabs/tab-label/tab-label.ts
  src/elements/tabs/tab-title.ts
  src/elements/tabs/tab-title/__snapshots__/tab-title.snapshot.spec.snap.js
  src/elements/tabs/tab-title/tab-title.scss
  src/elements/tabs/tab-title/tab-title.snapshot.spec.ts
  src/elements/tabs/tab-title/tab-title.spec.ts
  src/elements/tabs/tab-title/tab-title.ssr.spec.ts
  src/elements/tabs/tab.ts
  src/elements/tabs/tab/__snapshots__/tab.snapshot.spec.snap.js
  src/elements/tabs/tab/index.ts
  src/elements/tabs/tab/readme.md
  src/elements/tabs/tab/tab.scss
  src/elements/tabs/tab/tab.snapshot.spec.ts
  src/elements/tabs/tab/tab.spec.ts
  src/elements/tabs/tab/tab.ssr.spec.ts
  src/elements/tabs/tab/tab.stories.ts
  src/elements/tabs/tab/tab.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2750 test(sbb-action-group): add visual tests
  src/elements/action-group/action-group.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2751 test(sbb-accordion, sbb-expansion-panel): add visual test
  src/elements/accordion/accordion.visual.spec.ts
  src/elements/expansion-panel/expansion-panel-content/__snapshots__/expansion-panel-content.snapshot.spec.snap.js
  src/elements/expansion-panel/expansion-panel-content/expansion-panel-content.snapshot.spec.ts
  src/elements/expansion-panel/expansion-panel-header/__snapshots__/expansion-panel-header.snapshot.spec.snap.js
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.snapshot.spec.ts
  src/elements/expansion-panel/expansion-panel/expansion-panel.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2782 refactor(sbb-teaser-hero, sbb-teaser-paid): move to `@sbb-esta/lyne-elements-experimental`
  src/elements-experimental/teaser-hero.ts
  src/elements-experimental/teaser-hero/__snapshots__/teaser-hero.snapshot.spec.snap.js
  src/elements-experimental/teaser-hero/readme.md
  src/elements-experimental/teaser-hero/teaser-hero.scss
  src/elements-experimental/teaser-hero/teaser-hero.snapshot.spec.ts
  src/elements-experimental/teaser-hero/teaser-hero.spec.ts
  src/elements-experimental/teaser-hero/teaser-hero.ssr.spec.ts
  src/elements-experimental/teaser-hero/teaser-hero.stories.ts
  src/elements-experimental/teaser-hero/teaser-hero.ts
  src/elements-experimental/teaser-paid.ts
  src/elements-experimental/teaser-paid/__snapshots__/teaser-paid.snapshot.spec.snap.js
  src/elements-experimental/teaser-paid/readme.md
  src/elements-experimental/teaser-paid/teaser-paid.scss
  src/elements-experimental/teaser-paid/teaser-paid.snapshot.spec.ts
  src/elements-experimental/teaser-paid/teaser-paid.spec.ts
  src/elements-experimental/teaser-paid/teaser-paid.ssr.spec.ts
  src/elements-experimental/teaser-paid/teaser-paid.stories.ts
  src/elements-experimental/teaser-paid/teaser-paid.ts
  src/elements/teaser-hero/readme.md
  src/elements/teaser-paid/readme.md
  src/storybook/pages/home/home.common.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2787 test: fix freeze on assert fail
  package.json
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2796 chore: lock '@web/dev-server-core' dep
  package.json
  renovate.json
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2795 test(sbb-clock): add visual spec
  src/elements/clock/__snapshots__/clock.snapshot.spec.snap.js
  src/elements/clock/clock.snapshot.spec.ts
  src/elements/clock/clock.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2794 test(sbb-chip): add visual spec
  src/elements/chip/chip.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2789 test(sbb-calendar): add visual tests
  src/elements/calendar/__snapshots__/calendar.snapshot.spec.snap.js
  src/elements/calendar/calendar.snapshot.spec.ts
  src/elements/calendar/calendar.visual.spec.ts
  src/elements/core/testing/private/describe-each.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2715 feat(sbb-table-wrapper): initial implementation
  src/elements/core/styles/_index.scss
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/standard-theme.scss
  src/elements/core/styles/table.scss
  src/elements/stepper/stepper/__snapshots__/stepper.snapshot.spec.snap.js
  src/elements/table.ts
  src/elements/table/table-wrapper.ts
  src/elements/table/table-wrapper/__snapshots__/table-wrapper.snapshot.spec.snap.js
  src/elements/table/table-wrapper/readme.md
  src/elements/table/table-wrapper/table-wrapper.scss
  src/elements/table/table-wrapper/table-wrapper.snapshot.spec.ts
  src/elements/table/table-wrapper/table-wrapper.spec.ts
  src/elements/table/table-wrapper/table-wrapper.ssr.spec.ts
  src/elements/table/table-wrapper/table-wrapper.stories.ts
  src/elements/table/table-wrapper/table-wrapper.ts
  src/elements/table/table-wrapper/table-wrapper.visual.spec.ts
  src/storybook/styles/table/readme.md
  src/storybook/styles/table/table.stories.ts
  src/storybook/styles/table/table.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, visual-regression-diff-available

#2799 style: fix mini-button mixin
  src/elements/core/styles/mixins/buttons.scss
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2752 test(sbb-breadcrumb, sbb-breadcrumb-group): add visual tests
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.visual.spec.ts
  src/elements/breadcrumb/breadcrumb/__snapshots__/breadcrumb.snapshot.spec.snap.js
  src/elements/breadcrumb/breadcrumb/breadcrumb.snapshot.spec.ts
  src/elements/breadcrumb/breadcrumb/breadcrumb.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2803 style(table): add 'color-iron' variant
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/table.scss
  src/elements/dialog/dialog/dialog.snapshot.spec.ts
  src/storybook/styles/table/readme.md
  src/storybook/styles/table/table.stories.ts
  src/storybook/styles/table/table.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, visual-regression-diff-available

#2810 docs(sbb-header): fix url in readme.md
  src/elements/header/header/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2797 test(sbb-datepicker): add visual tests
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.visual.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.visual.spec.ts
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.snapshot.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.visual.spec.ts
  src/elements/datepicker/datepicker/datepicker.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2811 test(sbb-message): add visual regression tests
  src/elements/message/message.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2812 test(sbb-file-selector): add visual tests
  src/elements/file-selector/__snapshots__/file-selector.snapshot.spec.snap.js
  src/elements/file-selector/file-selector.snapshot.spec.ts
  src/elements/file-selector/file-selector.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2819 refactor(mini-button): inline variable for display property
  src/elements/core/styles/mixins/buttons.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2815 refactor(sbb-notification): add CSS property to define icon size
  src/elements/notification/notification.scss
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2816 fix(sbb-tab-group): fix nested tab groups logic
  src/elements/tabs/tab-group/__snapshots__/tab-group.snapshot.spec.snap.js
  src/elements/tabs/tab-group/readme.md
  src/elements/tabs/tab-group/tab-group.scss
  src/elements/tabs/tab-group/tab-group.snapshot.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/tabs/tab-group/tab-group.ssr.spec.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
  src/elements/tabs/tab-group/tab-group.ts
  src/elements/tabs/tab/__snapshots__/tab.snapshot.spec.snap.js
  src/elements/tabs/tab/readme.md
  src/elements/tabs/tab/tab.snapshot.spec.ts
  src/elements/tabs/tab/tab.spec.ts
  src/elements/tabs/tab/tab.ssr.spec.ts
  src/elements/tabs/tab/tab.stories.ts
Labels: pr: peer review required, pr: lead review approved

#2821 build: run playwright browsers in a container for visual regression testing
  .github/workflows/continuous-integration.yml
  docs/DEVELOPER.md
  package.json
  tools/visual-regression-testing/exec.ts
  tools/visual-regression-testing/prepare-failed-screenshots-artifact.ts
  tools/visual-regression-testing/testing.Dockerfile
  tools/visual-regression-testing/testing.Dockerfile.dockerignore
  tools/web-test-runner/configure-container-playwright-browser.ts
  tools/web-test-runner/container-playwright-browser-plugin.ts
  tools/web-test-runner/index.ts
  tools/web-test-runner/start-playwright-server.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2824 build: downgrade playwright to stabilize test execution
  package.json
  src/elements/option/option/__snapshots__/option.snapshot.spec.snap.js
  src/elements/stepper/step-label/__snapshots__/step-label.snapshot.spec.snap.js
  yarn.lock
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2823 test(sbb-datepicker): fix value format
  src/elements/datepicker/datepicker/datepicker.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2831 test(sbb-message): await image loading and fix import
  src/elements/message/message.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2798 test(sbb-container, sbb-sticky-bar): add visual spec
  src/elements/container/container/__snapshots__/container.snapshot.spec.snap.js
  src/elements/container/container/container.snapshot.spec.ts
  src/elements/container/container/container.visual.spec.ts
  src/elements/container/sticky-bar/__snapshots__/sticky-bar.snapshot.spec.snap.js
  src/elements/container/sticky-bar/sticky-bar.snapshot.spec.ts
  src/elements/container/sticky-bar/sticky-bar.stories.ts
  src/elements/container/sticky-bar/sticky-bar.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2680 feat(sbb-timetable-row): enhance trip status and display logic
  src/elements-experimental/pearl-chain-time/pearl-chain-time.snapshot.spec.ts
  src/elements-experimental/pearl-chain/pearl-chain.sample-data.ts
  src/elements-experimental/pearl-chain/pearl-chain.snapshot.spec.ts
  src/elements-experimental/pearl-chain/pearl-chain.ts
  src/elements-experimental/timetable-row/timetable-row.sample-data.ts
  src/elements-experimental/timetable-row/timetable-row.snapshot.spec.ts
  src/elements-experimental/timetable-row/timetable-row.stories.ts
  src/elements-experimental/timetable-row/timetable-row.ts
  src/elements/core/i18n/i18n.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2832 test(sbb-action-group): fix flickering tests
  src/elements/action-group/action-group.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2818 test(sbb-footer): add visual spec
  src/elements/footer/__snapshots__/footer.snapshot.spec.snap.js
  src/elements/footer/footer.snapshot.spec.ts
  src/elements/footer/footer.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2837 test(sbb-journey-header): add visual spec
  src/elements/core/testing/test-setup.ts
  src/elements/journey-header/__snapshots__/journey-header.snapshot.spec.snap.js
  src/elements/journey-header/journey-header.snapshot.spec.ts
  src/elements/journey-header/journey-header.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2784 test(sbb-alert): add visual regression tests
  src/elements/alert/alert-group/alert-group.visual.spec.ts
  src/elements/alert/alert/__snapshots__/alert.snapshot.spec.snap.js
  src/elements/alert/alert/alert.snapshot.spec.ts
  src/elements/alert/alert/alert.ts
  src/elements/alert/alert/alert.visual.spec.ts
  src/elements/alert/alert/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2834 test(sbb-image): stabilize image tests
  src/elements/core/testing/assets/placeholder-image.png
  src/elements/image/image.visual.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/message/message.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2833 test(sbb-datepicker): attempt to stabilize visual regression tests
  src/elements/core/testing/private/fixture.ts
  src/elements/core/testing/private/visual-regression-snapshot.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.visual.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.visual.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.visual.spec.ts
  src/elements/datepicker/datepicker/datepicker.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2841 test(sbb-loading-indicator): add visual spec
  src/elements/loading-indicator/__snapshots__/loading-indicator.snapshot.spec.snap.js
  src/elements/loading-indicator/loading-indicator.snapshot.spec.ts
  src/elements/loading-indicator/loading-indicator.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2840 build: preload icons for testing
  src/elements/core/testing/test-setup.ts
  src/elements/icon/icon-request.ts
  src/elements/icon/icon.ssr.spec.ts
  tools/web-test-runner/index.ts
  tools/web-test-runner/preload-icons.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2842 docs(sbb-accordion): fix documentation
  src/elements/accordion/accordion.ts
  src/elements/accordion/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2838 fix(sbb-clock): treat a specific date consistently
  src/elements/clock/__snapshots__/clock.snapshot.spec.snap.js
  src/elements/clock/clock.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2826 test(sbb-icon): add visual tests
  src/elements/icon/__snapshots__/icon.snapshot.spec.snap.js
  src/elements/icon/icon.snapshot.spec.ts
  src/elements/icon/icon.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2820 test(sbb-header): add visual tests
  src/elements/header/header-button/__snapshots__/header-button.snapshot.spec.snap.js
  src/elements/header/header-button/header-button.snapshot.spec.ts
  src/elements/header/header-button/header-button.stories.ts
  src/elements/header/header-button/header-button.visual.spec.ts
  src/elements/header/header-link/__snapshots__/header-link.snapshot.spec.snap.js
  src/elements/header/header-link/header-link.snapshot.spec.ts
  src/elements/header/header-link/header-link.stories.ts
  src/elements/header/header-link/header-link.visual.spec.ts
  src/elements/header/header/__snapshots__/header.snapshot.spec.snap.js
  src/elements/header/header/header.snapshot.spec.ts
  src/elements/header/header/header.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2844 test(sbb-link): add visual tests
  src/elements/link/block-link-button/__snapshots__/block-link-button.snapshot.spec.snap.js
  src/elements/link/block-link-button/block-link-button.snapshot.spec.ts
  src/elements/link/block-link-button/block-link-button.visual.spec.ts
  src/elements/link/block-link-static/__snapshots__/block-link-static.snapshot.spec.snap.js
  src/elements/link/block-link-static/block-link-static.snapshot.spec.ts
  src/elements/link/block-link-static/block-link-static.visual.spec.ts
  src/elements/link/block-link/__snapshots__/block-link.snapshot.spec.snap.js
  src/elements/link/block-link/block-link.snapshot.spec.ts
  src/elements/link/block-link/block-link.visual.spec.ts
  src/elements/link/link-button/__snapshots__/link-button.snapshot.spec.snap.js
  src/elements/link/link-button/link-button.snapshot.spec.ts
  src/elements/link/link-button/link-button.visual.spec.ts
  src/elements/link/link-static/__snapshots__/link-static.snapshot.spec.snap.js
  src/elements/link/link-static/link-static.snapshot.spec.ts
  src/elements/link/link-static/link-static.visual.spec.ts
  src/elements/link/link/__snapshots__/link.snapshot.spec.snap.js
  src/elements/link/link/link.snapshot.spec.ts
  src/elements/link/link/link.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2848 test(sbb-dialog): shorten text for more margin to scroll activated
  src/elements/dialog/dialog/dialog.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available

#2849 test(sbb-link): fix visual regression tests
  src/elements/link/block-link-button/block-link-button.visual.spec.ts
  src/elements/link/block-link-static/block-link-static.visual.spec.ts
  src/elements/link/block-link/block-link.visual.spec.ts
  src/elements/link/link-button/link-button.visual.spec.ts
  src/elements/link/link-static/link-static.visual.spec.ts
  src/elements/link/link/link.visual.spec.ts
Labels: preview-available, pr: peer review approved

#2827 test(sbb-toggle, sbb-toggle-check): add visual spec
  src/elements/toggle-check/readme.md
  src/elements/toggle-check/toggle-check.ts
  src/elements/toggle-check/toggle-check.visual.spec.ts
  src/elements/toggle/toggle-option/toggle-option.visual.spec.ts
  src/elements/toggle/toggle/toggle.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2807 test(sbb-form-field): add visual spec
  src/elements/form-error/form-error.visual.spec.ts
  src/elements/form-field/form-field-clear/__snapshots__/form-field-clear.snapshot.spec.snap.js
  src/elements/form-field/form-field-clear/form-field-clear.snapshot.spec.ts
  src/elements/form-field/form-field-clear/form-field-clear.stories.ts
  src/elements/form-field/form-field-clear/form-field-clear.visual.spec.ts
  src/elements/form-field/form-field/form-field.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2847 test(sbb-map-container): add visual spec
  src/elements/map-container/__snapshots__/map-container.snapshot.spec.snap.js
  src/elements/map-container/map-container.snapshot.spec.ts
  src/elements/map-container/map-container.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2850 fix: ensure slotchange events are handled correctly in hydration
  src/elements/core/mixins/hydration-mixin.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2845 fix(sbb-visual-checkbox): fix high contrast mode of indeterminate state
  src/elements/core/testing/private/fixture.ts
  src/elements/visual-checkbox/visual-checkbox.scss
  src/elements/visual-checkbox/visual-checkbox.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, visual-regression-diff-available
