Repository sbb-design-systems/lyne-components, pull requests merged in 2024-03, with the labels that each got.

#2450 fix(sbb-teaser): prevent overlapping chip if including long content
  src/components/teaser/teaser.scss
  src/components/teaser/teaser.stories.ts
Labels: preview-available, pr: lead review approved

#2457 fix(sbb-status): fix text styling
  src/components/status/status.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2458 fix(layout): apply max-width only for ultra screen size
  src/components/core/styles/mixins/layout.scss
Labels: pr: peer review required, pr: lead review approved

#2452 refactor: implement and use hostAttributes decorator
  src/components/autocomplete/autocomplete.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/card/card-badge/card-badge.ts
  src/components/card/common/card-action-common.ts
  src/components/container/sticky-bar/sticky-bar.ts
  src/components/core/common-behaviors/action-base-element.ts
  src/components/core/common-behaviors/button-base-element.ts
  src/components/core/common-behaviors/host-attributes.ts
  src/components/core/common-behaviors/index.ts
  src/components/core/common-behaviors/link-base-element.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/divider/divider.ts
  src/components/expansion-panel/expansion-panel-content/expansion-panel-content.ts
  src/components/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/components/form-field/form-field-clear/form-field-clear.ts
  src/components/icon/icon-base.ts
  src/components/loading-indicator/loading-indicator.ts
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.ts
  src/components/option/option/option.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/select/select.ts
  src/components/slider/slider.ts
  src/components/title/title.ts
  src/components/toggle/toggle-option/toggle-option.ts
  src/components/toggle/toggle/toggle.ts
  web-test-runner.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved

#2456 feat(sbb-checkbox, sbb-toggle-check): introduce native form support
  .eslintrc.json
  package.json
  src/components/breadcrumb/breadcrumb-group/__snapshots__/breadcrumb-group.spec.snap.js
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.spec.ts
  src/components/breadcrumb/breadcrumb/__snapshots__/breadcrumb.spec.snap.js
  src/components/breadcrumb/breadcrumb/breadcrumb.spec.ts
  src/components/button/common/button-common.ts
  src/components/checkbox/checkbox-group/__snapshots__/checkbox-group.spec.snap.js
  src/components/checkbox/checkbox-group/checkbox-group.e2e.ts
  src/components/checkbox/checkbox/__snapshots__/checkbox.spec.snap.js
  src/components/checkbox/checkbox/checkbox.e2e.ts
  src/components/checkbox/checkbox/checkbox.scss
  src/components/checkbox/checkbox/checkbox.spec.ts
  src/components/checkbox/checkbox/checkbox.stories.ts
  src/components/checkbox/checkbox/checkbox.ts
  src/components/checkbox/checkbox/readme.md
  src/components/core/common-behaviors/disabled-mixins.ts
  src/components/core/common-behaviors/form-associated-checkbox-mixin.ts
  src/components/core/common-behaviors/form-associated-mixin.ts
  src/components/core/common-behaviors/index.ts
  src/components/core/common-behaviors/required-mixin.ts
  src/components/core/eventing/form-element-handlers.ts
  src/components/menu/common/menu-action-common.ts
  src/components/selection-panel/__snapshots__/selection-panel.spec.snap.js
  src/components/selection-panel/selection-panel.e2e.ts
  src/components/toggle-check/__snapshots__/toggle-check.spec.snap.js
  src/components/toggle-check/readme.md
  src/components/toggle-check/toggle-check.e2e.ts
  src/components/toggle-check/toggle-check.scss
  src/components/toggle-check/toggle-check.spec.ts
  src/components/toggle-check/toggle-check.stories.ts
  src/components/toggle-check/toggle-check.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2460 docs: describe css properties
  scripts/docs_generate.ts
  src/components/autocomplete/autocomplete.ts
  src/components/autocomplete/readme.md
  src/components/container/sticky-bar/readme.md
  src/components/container/sticky-bar/sticky-bar.ts
  src/components/dialog/dialog.ts
  src/components/dialog/readme.md
  src/components/header/header/header.ts
  src/components/header/header/readme.md
  src/components/icon/icon-base.ts
  src/components/icon/readme.md
  src/components/logo/logo.ts
  src/components/logo/readme.md
  src/components/map-container/map-container.ts
  src/components/map-container/readme.md
  src/components/menu/menu-button/menu-button.ts
  src/components/menu/menu-button/readme.md
  src/components/menu/menu-link/menu-link.ts
  src/components/menu/menu-link/readme.md
  src/components/menu/menu/menu.ts
  src/components/menu/menu/readme.md
  src/components/navigation/navigation/navigation.ts
  src/components/navigation/navigation/readme.md
  src/components/notification/notification.ts
  src/components/notification/readme.md
  src/components/option/option/option.ts
  src/components/option/option/readme.md
  src/components/popover/popover/popover.ts
  src/components/popover/popover/readme.md
  src/components/select/readme.md
  src/components/select/select.ts
  src/components/skiplink-list/readme.md
  src/components/skiplink-list/skiplink-list.scss
  src/components/skiplink-list/skiplink-list.ts
  src/components/timetable-occupancy-icon/readme.md
  src/components/title/readme.md
  src/components/title/title.ts
  src/components/toast/readme.md
  src/components/toast/toast.ts
  tools/generate-component/boilerplate/component.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2464 refactor: simplify sbb-tag-group logic
  src/components/button/button/readme.md
  src/components/card/card-button/readme.md
  src/components/core/common-behaviors/button-base-element.ts
  src/components/core/common-behaviors/form-associated-mixin.ts
  src/components/datepicker/datepicker-next-day/readme.md
  src/components/datepicker/datepicker-previous-day/readme.md
  src/components/expansion-panel/expansion-panel-header/readme.md
  src/components/form-field/form-field-clear/readme.md
  src/components/header/header-button/readme.md
  src/components/link/block-link-button/readme.md
  src/components/link/link-button/readme.md
  src/components/menu/menu-button/readme.md
  src/components/navigation/navigation-button/readme.md
  src/components/popover/popover-trigger/readme.md
  src/components/tag/tag-group/readme.md
  src/components/tag/tag-group/tag-group.e2e.ts
  src/components/tag/tag-group/tag-group.ts
  src/components/tag/tag/readme.md
  src/components/tag/tag/tag.ts
Labels: preview-available, pr: peer review approved

#2463 feat(sbb-selection-panel): increase border width for active state
  src/components/selection-panel/selection-panel.scss
Labels: preview-available, pr: peer review approved, pr: ux review approved

#2468 fix(sbb-selection-panel): fix transition of border-width
  src/components/selection-panel/selection-panel.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2469 fix(sbb-selection-panel): fix transition of border-width second attempt
  src/components/selection-panel/selection-panel.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2455 refactor(sbb-navigation): improve active handling and focus
  src/components/navigation/common/navigation-action-common.ts
  src/components/navigation/common/navigation-action.scss
  src/components/navigation/navigation-button/readme.md
  src/components/navigation/navigation-link/readme.md
  src/components/navigation/navigation-marker/navigation-marker.e2e.ts
  src/components/navigation/navigation-marker/navigation-marker.stories.ts
  src/components/navigation/navigation-marker/navigation-marker.ts
  src/components/navigation/navigation-section/navigation-section.stories.ts
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.e2e.ts
  src/components/navigation/navigation/navigation.stories.ts
  src/components/navigation/navigation/navigation.ts
  src/components/navigation/navigation/readme.md
  src/storybook/pages/home/home.common.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2473 feat(sbb-navigation): remove navigation section divider
  src/components/navigation/navigation-section/__snapshots__/navigation-section.spec.snap.js
  src/components/navigation/navigation-section/navigation-section.scss
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required

#2475 fix: fix imports of common styles
  src/components/button/button-link/button-link.ts
  src/components/button/button-static/button-static.ts
  src/components/button/button/button.ts
  src/components/button/common/index.ts
  src/components/button/secondary-button-link/secondary-button-link.ts
  src/components/button/secondary-button-static/secondary-button-static.ts
  src/components/button/secondary-button/secondary-button.ts
  src/components/button/tertiary-button-link/tertiary-button-link.ts
  src/components/button/tertiary-button-static/tertiary-button-static.ts
  src/components/button/tertiary-button/tertiary-button.ts
  src/components/button/transparent-button-link/transparent-button-link.ts
  src/components/button/transparent-button-static/transparent-button-static.ts
  src/components/button/transparent-button/transparent-button.ts
  src/components/card/card-button/card-button.ts
  src/components/card/card-link/card-link.ts
  src/components/header/header-button/header-button.ts
  src/components/header/header-link/header-link.ts
  src/components/menu/menu-link/menu-link.ts
  src/components/navigation/navigation-button/navigation-button.ts
  src/components/navigation/navigation-link/navigation-link.ts
  src/components/vite.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2471 fix(sbb-navigation): fix active and focus handling
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.e2e.ts
  src/components/navigation/navigation/navigation.stories.ts
  src/components/navigation/navigation/navigation.ts
  src/storybook/pages/home/home.common.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2483 fix: fix unresolved sass imports
  src/components/button/common/button-common.ts
  src/components/button/common/index.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2479 fix(sbb-status): fix flex behavior in Firefox
  src/components/status/status.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2486 build: completely remove jest
  TODOS.md
  docs/DEVELOP.md
  package.json
  src/components/navigation/navigation-section/navigation-section.stories.ts
  src/components/navigation/navigation/navigation.stories.ts
  src/storybook/testing/wait-for-components-ready.ts
  tools/eslint/custom-element-class-name-rule.ts
  tools/eslint/missing-component-documentation-rule.ts
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved

#2488 refactor: migrate 'toggleDatasetEntry' calls to 'toggleAttribute'
  scripts/migrate-toggle-data-entry.ts
  src/components/autocomplete/autocomplete.ts
  src/components/calendar/calendar.ts
  src/components/card/card-badge/card-badge.ts
  src/components/card/common/card-action-common.ts
  src/components/checkbox/checkbox-group/checkbox-group.ts
  src/components/container/container/container.ts
  src/components/core/a11y/focus-visible-within-controller.ts
  src/components/core/dom/dataset.ts
  src/components/core/dom/index.ts
  src/components/core/dom/scroll.ts
  src/components/core/overlay/overlay.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
  src/components/datepicker/datepicker/datepicker.ts
  src/components/dialog/dialog.ts
  src/components/file-selector/file-selector.ts
  src/components/form-field/form-field/form-field.ts
  src/components/header/common/header-action-common.ts
  src/components/header/header/header.ts
  src/components/map-container/map-container.ts
  src/components/notification/notification.ts
  src/components/option/optgroup/optgroup.ts
  src/components/option/option/option.ts
  src/components/popover/popover-trigger/popover-trigger.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/select/select.ts
  src/components/tabs/tab-group/tab-group.ts
  src/components/time-input/time-input.ts
  src/components/toggle/toggle/toggle.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2489 fix: fix order of class decorators
  src/components/autocomplete/autocomplete.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/card/card-badge/card-badge.ts
  src/components/container/sticky-bar/sticky-bar.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/divider/divider.ts
  src/components/expansion-panel/expansion-panel-content/expansion-panel-content.ts
  src/components/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/components/form-field/form-field-clear/form-field-clear.ts
  src/components/loading-indicator/loading-indicator.ts
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.ts
  src/components/option/option/option.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/select/select.ts
  src/components/slider/slider.ts
  src/components/title/title.ts
  src/components/toggle/toggle-option/toggle-option.ts
  src/components/toggle/toggle/toggle.ts
  tools/eslint/custom-element-decorator-position-rule.ts
  tools/eslint/index.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2481 fix(sbb-navigation): fix navigation actions contrast ratio
  src/components/navigation/common/navigation-action-common.ts
  src/components/navigation/common/navigation-action.scss
  src/components/navigation/navigation-button/navigation-button.spec.ts
  src/components/navigation/navigation-link/navigation-link.spec.ts
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.scss
  src/components/navigation/navigation/navigation.ts
  src/components/notification/notification.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved

#2480 refactor(breakpoint): convert breakpoint-dependent code to pure css
  src/components/calendar/calendar.ts
  src/components/header/common/header-action-common.ts
  src/components/header/common/header-action.scss
  src/components/header/header-button/__snapshots__/header-button.spec.snap.js
  src/components/header/header-button/header-button.spec.ts
  src/components/header/header-link/__snapshots__/header-link.spec.snap.js
  src/components/header/header-link/header-link.spec.ts
  src/components/navigation/navigation-section/navigation-section.scss
  src/components/navigation/navigation-section/navigation-section.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2493 fix(sbb-navigation-section): ensure `sbb-active` initializes correctly
  src/components/navigation/common/navigation-action-common.ts
  src/components/navigation/navigation-button/readme.md
  src/components/navigation/navigation-link/readme.md
Labels: preview-available, pr: peer review required

#2495 chore: remove 'vite-plugin-turbosnap' dependency
  .storybook/main.ts
  package.json
Labels: preview-available, pr: peer review required, pr: lead review approved

#2505 fix(sbb-checkbox, sbb-toggle-check): enable attribute mutation after form reset
  src/components/checkbox/checkbox/checkbox.e2e.ts
  src/components/core/common-behaviors/form-associated-checkbox-mixin.ts
  src/components/core/common-behaviors/form-associated-mixin.ts
  src/components/toggle-check/toggle-check.e2e.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2501 refactor: use sbb-screenreader-only component where possible
  src/components/calendar/__snapshots__/calendar.spec.snap.js
  src/components/calendar/calendar.scss
  src/components/calendar/calendar.ts
  src/components/dialog/__snapshots__/dialog.spec.snap.js
  src/components/dialog/dialog.e2e.ts
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
  src/components/journey-header/__snapshots__/journey-header.spec.snap.js
  src/components/journey-header/journey-header.scss
  src/components/journey-header/journey-header.ts
  src/components/journey-summary/__snapshots__/journey-summary.spec.snap.js
  src/components/journey-summary/journey-summary.scss
  src/components/journey-summary/journey-summary.ts
  src/components/option/option/option.scss
  src/components/option/option/option.ts
  src/components/radio-button/radio-button/__snapshots__/radio-button.spec.snap.js
  src/components/radio-button/radio-button/radio-button.e2e.ts
  src/components/radio-button/radio-button/radio-button.scss
  src/components/radio-button/radio-button/radio-button.ts
  src/components/selection-panel/selection-panel.e2e.ts
  src/components/timetable-occupancy/__snapshots__/timetable-occupancy.spec.snap.js
  src/components/timetable-occupancy/timetable-occupancy.scss
  src/components/timetable-occupancy/timetable-occupancy.ts
Labels: preview-available, pr: peer review approved

#2502 docs(sbb-icon): add note about icon naming
  src/components/icon/readme.md
Labels: preview-available, pr: peer review approved

#2508 fix(sbb-header): fix header shadow on keyboard navigation
  src/components/header/header/header.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2509 refactor(timetable-row): remove service product logic
  src/components/core/timetable/timetable-properties.ts
  src/components/timetable-row/timetable-row.sample-data.ts
  src/components/timetable-row/timetable-row.spec.ts
  src/components/timetable-row/timetable-row.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2511 refactor(sbb-calendar): implement initial support for other date libraries
  src/components/calendar/calendar.e2e.ts
  src/components/calendar/calendar.spec.ts
  src/components/calendar/calendar.stories.ts
  src/components/calendar/calendar.ts
  src/components/calendar/readme.md
  src/components/core/datetime/date-adapter.ts
  src/components/core/datetime/native-date-adapter.spec.ts
  src/components/core/datetime/native-date-adapter.ts
  src/components/core/interfaces/types.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/datepicker/datepicker/datepicker.ts
  tsconfig.json
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2520 refactor: rename component name from `sbb-screenreader-only` to `sbb-screeen-reader-only`
  src/components/breadcrumb/breadcrumb/__snapshots__/breadcrumb.spec.snap.js
  src/components/button/button-link/__snapshots__/button-link.spec.snap.js
  src/components/button/secondary-button-link/__snapshots__/secondary-button-link.spec.snap.js
  src/components/button/tertiary-button-link/__snapshots__/tertiary-button-link.spec.snap.js
  src/components/button/transparent-button-link/__snapshots__/transparent-button-link.spec.snap.js
  src/components/calendar/__snapshots__/calendar.spec.snap.js
  src/components/calendar/calendar.ts
  src/components/card/card-button/__snapshots__/card-button.e2e.snap.js
  src/components/card/card-link/__snapshots__/card-link.e2e.snap.js
  src/components/card/common/card-action-common.ts
  src/components/checkbox/checkbox/__snapshots__/checkbox.spec.snap.js
  src/components/checkbox/checkbox/checkbox.ts
  src/components/core/common-behaviors/link-base-element.ts
  src/components/core/common-behaviors/named-slot-list-mixin.ts
  src/components/core/timetable/access-leg-helper.ts
  src/components/dialog/__snapshots__/dialog.spec.snap.js
  src/components/dialog/dialog.e2e.ts
  src/components/dialog/dialog.ts
  src/components/header/header-link/__snapshots__/header-link.spec.snap.js
  src/components/journey-header/__snapshots__/journey-header.spec.snap.js
  src/components/journey-header/journey-header.ts
  src/components/journey-summary/__snapshots__/journey-summary.spec.snap.js
  src/components/journey-summary/journey-summary.ts
  src/components/link/link/__snapshots__/link.spec.snap.js
  src/components/menu/menu-link/menu-link.spec.ts
  src/components/navigation/navigation-link/navigation-link.spec.ts
  src/components/option/option/option.ts
  src/components/pearl-chain-time/pearl-chain-time.scss
  src/components/pearl-chain-time/pearl-chain-time.spec.ts
  src/components/pearl-chain-time/pearl-chain-time.ts
  src/components/pearl-chain/pearl-chain.scss
  src/components/radio-button/radio-button/__snapshots__/radio-button.spec.snap.js
  src/components/radio-button/radio-button/radio-button.e2e.ts
  src/components/radio-button/radio-button/radio-button.scss
  src/components/radio-button/radio-button/radio-button.ts
  src/components/screen-reader-only/__snapshots__/screen-reader-only.spec.snap.js
  src/components/screen-reader-only/index.ts
  src/components/screen-reader-only/readme.md
  src/components/screen-reader-only/screen-reader-only.e2e.ts
  src/components/screen-reader-only/screen-reader-only.scss
  src/components/screen-reader-only/screen-reader-only.spec.ts
  src/components/screen-reader-only/screen-reader-only.stories.ts
  src/components/screen-reader-only/screen-reader-only.ts
  src/components/screenreader-only/index.ts
  src/components/screenreader-only/screenreader-only.e2e.ts
  src/components/selection-panel/selection-panel.e2e.ts
  src/components/teaser-hero/__snapshots__/teaser-hero.spec.snap.js
  src/components/teaser-paid/__snapshots__/teaser-paid.spec.snap.js
  src/components/timetable-occupancy/__snapshots__/timetable-occupancy.spec.snap.js
  src/components/timetable-occupancy/timetable-occupancy.ts
  src/components/timetable-row/timetable-row.scss
  src/components/timetable-row/timetable-row.spec.ts
  src/components/timetable-row/timetable-row.ts
  src/components/train/train-formation/__snapshots__/train-formation.spec.snap.js
  src/components/train/train-wagon/__snapshots__/train-wagon.spec.snap.js
  src/components/train/train-wagon/train-wagon.scss
  src/components/train/train-wagon/train-wagon.spec.ts
  src/components/train/train-wagon/train-wagon.ts
Labels: preview-available, pr: peer review approved

#2526 fix(sbb-button): remove gap for hidden icons in icon slot
  src/components/button/button-link/__snapshots__/button-link.spec.snap.js
  src/components/button/button-link/button-link.stories.ts
  src/components/button/button-static/__snapshots__/button-static.spec.snap.js
  src/components/button/button-static/button-static.stories.ts
  src/components/button/button/__snapshots__/button.spec.snap.js
  src/components/button/button/button.stories.ts
  src/components/button/common/button-common.scss
  src/components/button/common/button-common.ts
  src/components/button/common/common-stories.ts
  src/components/button/secondary-button-link/__snapshots__/secondary-button-link.spec.snap.js
  src/components/button/secondary-button-link/secondary-button-link.stories.ts
  src/components/button/secondary-button-static/__snapshots__/secondary-button-static.spec.snap.js
  src/components/button/secondary-button-static/secondary-button-static.stories.ts
  src/components/button/secondary-button/__snapshots__/secondary-button.spec.snap.js
  src/components/button/secondary-button/secondary-button.stories.ts
  src/components/button/tertiary-button-link/__snapshots__/tertiary-button-link.spec.snap.js
  src/components/button/tertiary-button-link/tertiary-button-link.stories.ts
  src/components/button/tertiary-button-static/__snapshots__/tertiary-button-static.spec.snap.js
  src/components/button/tertiary-button-static/tertiary-button-static.stories.ts
  src/components/button/tertiary-button/__snapshots__/tertiary-button.spec.snap.js
  src/components/button/tertiary-button/tertiary-button.stories.ts
  src/components/button/transparent-button-link/__snapshots__/transparent-button-link.spec.snap.js
  src/components/button/transparent-button-link/transparent-button-link.stories.ts
  src/components/button/transparent-button-static/__snapshots__/transparent-button-static.spec.snap.js
  src/components/button/transparent-button-static/transparent-button-static.stories.ts
  src/components/button/transparent-button/__snapshots__/transparent-button.spec.snap.js
  src/components/button/transparent-button/transparent-button.stories.ts
Labels: preview-available, pr: peer review approved

#2523 fix(sbb-form-field): remove label property and attribute
  src/components/autocomplete/autocomplete.stories.ts
  src/components/autocomplete/readme.md
  src/components/button/mini-button/mini-button.stories.ts
  src/components/button/mini-button/readme.md
  src/components/datepicker/datepicker/datepicker.stories.ts
  src/components/dialog/dialog.stories.ts
  src/components/form-field/form-field-clear/__snapshots__/form-field-clear.spec.snap.js
  src/components/form-field/form-field-clear/form-field-clear.e2e.ts
  src/components/form-field/form-field-clear/form-field-clear.spec.ts
  src/components/form-field/form-field-clear/form-field-clear.stories.ts
  src/components/form-field/form-field-clear/readme.md
  src/components/form-field/form-field/__snapshots__/form-field.spec.snap.js
  src/components/form-field/form-field/form-field.e2e.ts
  src/components/form-field/form-field/form-field.spec.ts
  src/components/form-field/form-field/form-field.stories.ts
  src/components/form-field/form-field/form-field.ts
  src/components/form-field/form-field/readme.md
  src/components/option/optgroup/optgroup.stories.ts
  src/components/option/option/option.stories.ts
  src/components/select/readme.md
  src/components/select/select.stories.ts
  src/components/slider/readme.md
  src/components/slider/slider.stories.ts
  src/components/time-input/time-input.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2528 fix: stories with label bold for sbb-checkbox and sbb-radio-button
  src/components/checkbox/checkbox/checkbox.stories.ts
  src/components/checkbox/checkbox/readme.md
  src/components/radio-button/radio-button/radio-button.stories.ts
  src/components/radio-button/radio-button/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2529 docs(sbb-checkbox-group): set props instead of attributes in story
  src/components/checkbox/checkbox-group/checkbox-group.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2530 build: extract web test runner config into separate files
  config/web-test-runner/index.js
  config/web-test-runner/lit-ssr-worker.js
  config/web-test-runner/minimal-reporter.js
  config/web-test-runner/patched-summary-reporter.js
  config/web-test-runner/ssr-plugin.js
  config/web-test-runner/vite-plugin.js
  web-test-runner.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved
