Repository sbb-design-systems/lyne-components, pull requests merged in 2024-04, with the labels that each got.

#2477 feat(sbb-overlay): extract `sbb-overlay` component from dialog
  src/components/autocomplete/autocomplete.scss
  src/components/autocomplete/autocomplete.ts
  src/components/autocomplete/readme.md
  src/components/core/styles/core/variables.scss
  src/components/core/styles/typography.scss
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
  src/components/dialog/readme.md
  src/components/menu/menu/menu.scss
  src/components/menu/menu/menu.ts
  src/components/menu/menu/readme.md
  src/components/navigation/navigation-section/navigation-section.scss
  src/components/navigation/navigation/navigation.scss
  src/components/navigation/navigation/navigation.ts
  src/components/navigation/navigation/readme.md
  src/components/overlay/__snapshots__/overlay.spec.snap.js
  src/components/overlay/index.ts
  src/components/overlay/overlay.e2e.ts
  src/components/overlay/overlay.scss
  src/components/overlay/overlay.spec.ts
  src/components/overlay/overlay.stories.ts
  src/components/overlay/overlay.ts
  src/components/overlay/readme.md
  src/components/popover/popover/popover.scss
  src/components/popover/popover/popover.ts
  src/components/popover/popover/readme.md
  src/components/screenreader-only/__snapshots__/screenreader-only.spec.snap.js
  src/components/select/readme.md
  src/components/select/select.scss
  src/components/select/select.ts
  src/components/skiplink-list/readme.md
  src/components/skiplink-list/skiplink-list.scss
  src/components/skiplink-list/skiplink-list.ts
  src/components/toast/readme.md
  src/components/toast/toast.scss
  src/components/toast/toast.ts
  tsconfig.json
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2506 feat(sbb-form-field): support the textarea inside the `<sbb-form-field>`
  src/components/core/styles/mixins/buttons.scss
  src/components/core/styles/typography.scss
  src/components/datepicker/datepicker-toggle/datepicker-toggle.scss
  src/components/form-field/form-field/form-field.e2e.ts
  src/components/form-field/form-field/form-field.scss
  src/components/form-field/form-field/form-field.stories.ts
  src/components/form-field/form-field/form-field.ts
  src/components/form-field/form-field/readme.md
  src/components/slider/slider.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required

#2546 refactor(sbb-option): remove unused CSS variable
  src/components/option/option/option.scss
Labels: preview-available, pr: peer review required

#2539 build: extract build and test configuration to tools
  package.json
  scripts/docs_generate.ts
  src/components/vite.config.ts
  src/react/vite.config.ts
  tools/manifest/custom-elements-manifest.config.js
  tools/vite/build-meta.ts
  tools/vite/copy-assets.ts
  tools/vite/custom-elements-manifest.ts
  tools/vite/dts.ts
  tools/vite/generate-react-wrappers.ts
  tools/vite/index-map.ts
  tools/vite/index.ts
  tools/vite/package-json-template.ts
  tools/vite/typography.ts
  tools/web-test-runner/index.js
  tools/web-test-runner/lit-ssr-worker.js
  tools/web-test-runner/minimal-reporter.js
  tools/web-test-runner/patched-summary-reporter.js
  tools/web-test-runner/ssr-plugin.js
  tools/web-test-runner/vite-plugin.js
  vite.config.ts
  web-test-runner.config.js
Labels: preview-available, pr: peer review required

#2547 fix: fix boolean handling in react wrapper
  src/react/core/create-component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2551 feat: update tokens
  package.json
  src/components/button/common/button-common.scss
  src/components/form-error/form-error.scss
  src/components/form-field/form-field/form-field.scss
  src/components/header/common/header-action.scss
  src/components/menu/menu/menu.e2e.ts
  src/components/popover/popover/popover.e2e.ts
  src/components/train/train-blocked-passage/train-blocked-passage.scss
  src/components/train/train-formation/train-formation.scss
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved

#2558 fix(sbb-form-error): fix internal css variable name
  src/components/form-error/form-error.scss
Labels: pr: peer review approved

#2532 refactor: base element for datepicker buttons
  src/components/datepicker/common/datepicker-button.ts
  src/components/datepicker/common/index.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
  src/components/datepicker/datepicker-next-day/readme.md
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
  src/components/datepicker/datepicker-previous-day/readme.md
  src/components/datepicker/datepicker/datepicker.ts
  src/components/datepicker/index.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2553 fix(sass): inline external .scss files during build
  src/components/core/styles/core/functions.scss
  src/components/core/styles/core/mediaqueries.scss
  src/components/vite.config.ts
  tools/vite/copy-sass.ts
  tools/vite/index.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2549 build: separate dev and prod builds
  package.json
  src/components/core/styles/core/functions.scss
  src/components/core/styles/core/mediaqueries.scss
  src/components/form-field/form-field/form-field.ts
  src/components/image/image.helper.ts
  src/components/tabs/tab-group/tab-group.ts
  src/components/tag/tag-group/tag-group.ts
  src/components/toggle/toggle/toggle.ts
  src/components/vite.config.ts
  src/react/core/create-component.ts
  src/react/vite.config.ts
  tools/vite/copy-sass.ts
  tools/vite/index.ts
  tools/vite/package-json-template.ts
Labels: preview-available, pr: peer review required

#2561 build: remove standard version
  package.json
  renovate.json
  yarn.lock
Labels: preview-available, pr: peer review required

#2560 build: refine test setup
  src/components/core/mixins/hydration-mixin.ts
  src/components/core/testing/platform.ts
  src/components/popover/popover/popover.e2e.ts
  src/components/toast/toast.e2e.ts
  tools/web-test-runner/vite-plugin.js
  web-test-runner.config.js
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2564 fix(sbb-calendar): align month view label
  src/components/calendar/calendar.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2565 refactor: remove false check for boolean attributes
  src/components/autocomplete/autocomplete.e2e.ts
  src/components/autocomplete/autocomplete.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/card/card-button/card-button.e2e.ts
  src/components/card/card-link/card-link.e2e.ts
  src/components/core/dom/index.ts
  src/components/core/dom/is-valid-attribute.ts
  src/components/core/dom/scroll.ts
  src/components/core/dom/set-or-remove-attribute.ts
  src/components/datepicker/common/datepicker-button.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.e2e.ts
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.e2e.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/datepicker/datepicker/datepicker.ts
  src/components/dialog/dialog.ts
  src/components/form-error/form-error.ts
  src/components/form-field/form-field-clear/form-field-clear.e2e.ts
  src/components/form-field/form-field-clear/form-field-clear.ts
  src/components/form-field/form-field/form-field.e2e.ts
  src/components/form-field/form-field/form-field.ts
  src/components/link-list/link-list.e2e.ts
  src/components/menu/menu/menu.ts
  src/components/navigation/navigation-section/navigation-section.ts
  src/components/navigation/navigation/navigation.ts
  src/components/option/optgroup/optgroup.e2e.ts
  src/components/option/optgroup/optgroup.ts
  src/components/option/option/option.ts
  src/components/overlay/overlay.ts
  src/components/popover/popover-trigger/popover-trigger.ts
  src/components/popover/popover/popover.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/select/select.e2e.ts
  src/components/select/select.ts
  src/components/selection-panel/selection-panel.e2e.ts
  src/components/slider/slider.e2e.ts
  src/components/slider/slider.ts
  src/components/tabs/tab-group/tab-group.ts
  src/components/tag/tag-group/tag-group.ts
  src/components/tag/tag/tag.e2e.ts
  src/components/time-input/time-input.ts
  src/components/timetable-occupancy-icon/timetable-occupancy-icon.ts
  src/components/timetable-row/timetable-row.ts
  src/components/toast/toast.e2e.ts
  src/components/toast/toast.ts
  src/components/toggle/toggle-option/toggle-option.ts
  src/components/toggle/toggle/toggle.e2e.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2566 feat(sbb-sticky-bar): allow configuration of z-index
  src/components/container/sticky-bar/readme.md
  src/components/container/sticky-bar/sticky-bar.scss
  src/components/container/sticky-bar/sticky-bar.ts
Labels: preview-available, pr: peer review required

#2544 feat(button): implemented size 'S'
  src/components/button/button-link/button-link.stories.ts
  src/components/button/button-static/button-static.stories.ts
  src/components/button/button/button.stories.ts
  src/components/button/common/button-common.scss
  src/components/button/common/button-common.ts
  src/components/button/common/common-stories.ts
  src/components/button/secondary-button-link/secondary-button-link.stories.ts
  src/components/button/secondary-button-static/secondary-button-static.stories.ts
  src/components/button/secondary-button/secondary-button.stories.ts
  src/components/button/tertiary-button-link/tertiary-button-link.stories.ts
  src/components/button/tertiary-button-static/tertiary-button-static.stories.ts
  src/components/button/tertiary-button/tertiary-button.stories.ts
  src/components/button/transparent-button-link/transparent-button-link.stories.ts
  src/components/button/transparent-button-static/transparent-button-static.stories.ts
  src/components/button/transparent-button/transparent-button.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required

#2231 refactor(sbb-dialog): introduce inner components and header animation
  src/components/core/dom/breakpoint.ts
  src/components/dialog/__snapshots__/dialog.spec.snap.js
  src/components/dialog/dialog-actions/__snapshots__/dialog-actions.spec.snap.js
  src/components/dialog/dialog-actions/dialog-actions.scss
  src/components/dialog/dialog-actions/dialog-actions.spec.ts
  src/components/dialog/dialog-actions/dialog-actions.stories.ts
  src/components/dialog/dialog-actions/dialog-actions.ts
  src/components/dialog/dialog-actions/index.ts
  src/components/dialog/dialog-actions/readme.md
  src/components/dialog/dialog-content/dialog-content.scss
  src/components/dialog/dialog-content/dialog-content.spec.ts
  src/components/dialog/dialog-content/dialog-content.stories.ts
  src/components/dialog/dialog-content/dialog-content.ts
  src/components/dialog/dialog-content/index.ts
  src/components/dialog/dialog-content/readme.md
  src/components/dialog/dialog-title/__snapshots__/dialog-title.spec.snap.js
  src/components/dialog/dialog-title/dialog-title.e2e.ts
  src/components/dialog/dialog-title/dialog-title.scss
  src/components/dialog/dialog-title/dialog-title.spec.ts
  src/components/dialog/dialog-title/dialog-title.stories.ts
  src/components/dialog/dialog-title/dialog-title.ts
  src/components/dialog/dialog-title/index.ts
  src/components/dialog/dialog-title/readme.md
  src/components/dialog/dialog.spec.ts
  src/components/dialog/dialog.stories.ts
  src/components/dialog/dialog/__snapshots__/dialog.spec.snap.js
  src/components/dialog/dialog/dialog.e2e.ts
  src/components/dialog/dialog/dialog.scss
  src/components/dialog/dialog/dialog.spec.ts
  src/components/dialog/dialog/dialog.stories.ts
  src/components/dialog/dialog/dialog.ts
  src/components/dialog/dialog/index.ts
  src/components/dialog/dialog/readme.md
  src/components/dialog/index.ts
  src/components/dialog/readme.md
  src/storybook/pages/home/home--logged-in.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2572 fix(sbb-dialog): fix z-index
  src/components/dialog/dialog-title/dialog-title.scss
  src/components/dialog/dialog/dialog.ts
  src/components/dialog/dialog/readme.md
Labels: preview-available, pr: peer review approved

#2573 feat: provide full font characters set as alternative
  src/components/core/styles/core/font-face.scss
  src/components/core/styles/fullfont.scss
  src/components/vite.config.ts
  tools/vite/typography.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2578 docs(sbb-dialog-actions): change examples to be in plural form
  src/components/dialog/dialog-actions/readme.md
  src/components/dialog/dialog/readme.md
Labels: pr: peer review required

#2579 fix: update import paths missed in the migration
  src/components/calendar/calendar.ts
  src/components/clock/clock.ts
  src/components/core/datetime.ts
  src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
  src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/datepicker/datepicker/datepicker.ts
  src/components/journey-summary/journey-summary.ts
  src/components/pearl-chain-time/pearl-chain-time.ts
  src/components/pearl-chain/pearl-chain.ts
  src/components/timetable-row/timetable-row.ts
  src/components/vite.config.ts
  tools/vite/index.ts
  tools/vite/verify-entry-points.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2589 fix: adapt react package import paths missed during migration
  tools/manifest/custom-elements-manifest.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved

#2588 fix(sbb-overlay): consider sbb-overlay as overlay in inert mechanism
  src/components/core/overlay/overlay.ts
Labels: preview-available, pr: peer review approved

#2585 docs(sbb-action-group): add button-size small
  src/components/action-group/action-group.spec.ts
  src/components/action-group/action-group.stories.ts
  src/components/action-group/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved

#2581 fix(sbb-teaser-hero): use auto hyphens for title text to avoid overflow
  src/components/teaser-hero/teaser-hero.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2582 fix: adapt lyne tokens change
  package.json
  src/components/core/styles/_index.scss
  src/components/core/styles/core/variables.scss
  src/components/core/styles/fullfont.scss
  src/components/core/styles/global.scss
  src/components/core/styles/mixins/font-face.scss
  src/components/core/styles/typography.scss
  tools/vite/copy-sass.ts
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved

#2592 build: re-enable chromatic stories
  .storybook/preview.ts
  scripts/chromatic-stories-generator.ts
  scripts/migrate-ssr-e2e.ts
  scripts/migrate-toggle-data-entry.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2594 refactor(sbb-title): extract base class
  src/components/dialog/dialog-title/dialog-title.scss
  src/components/dialog/dialog-title/dialog-title.ts
  src/components/dialog/dialog-title/readme.md
  src/components/title.ts
  src/components/title/readme.md
  src/components/title/title-base.ts
  src/components/title/title-common.scss
  src/components/title/title.scss
  src/components/title/title.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2605 docs: 📚 optimize code preview + add table of contents
  .storybook/preview.ts
Labels: pr: peer review required

#2607 fix(sbb-image): fix alt attribute and provide css var for aspect-ratio
  src/components/image/image.e2e.ts
  src/components/image/image.scss
  src/components/image/image.ts
  src/components/image/readme.md
Labels: pr: peer review required, pr: lead review approved

#2490 docs: add getting started and clean up docs
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/contributing-request.yml
  .github/ISSUE_TEMPLATE/feature-request-or-enhancement.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  STORYBOOK.md
  docs/CICD.md
  docs/CODE_OF_CONDUCT.md
  docs/CODING_STANDARDS.md
  docs/CONTRIBUTING.md
  docs/DEVELOP.md
  docs/DEVELOPER.md
  docs/GETTING_STARTED.md
  docs/README.md
  docs/REVIEW.md
  docs/STATES.md
  docs/TERMINOLOGY.md
  docs/VISION.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2609 fix: prefix all css variable names
  src/components/button/common/button-common.scss
  src/components/form-field/form-field/form-field.scss
  src/components/image/image.scss
Labels: preview-available, pr: peer review approved

#2611 fix(sbb-container): fix background color for nested containers
  src/components/container/container/container.scss
  src/components/container/container/container.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2612 refactor: use `localName` instead of `tagName`
  src/components/accordion/accordion.e2e.ts
  src/components/accordion/accordion.ts
  src/components/alert/alert-group/alert-group.e2e.ts
  src/components/autocomplete/autocomplete.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.e2e.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/calendar/calendar.ts
  src/components/card/common/card-action-common.ts
  src/components/core/base-elements/link-base-element.ts
  src/components/core/mixins/named-slot-list-mixin.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/form-field/form-field-clear/form-field-clear.ts
  src/components/form-field/form-field/form-field.ts
  src/components/link-list/link-list.ts
  src/components/menu/menu/menu.ts
  src/components/navigation/navigation-list/navigation-list.ts
  src/components/navigation/navigation-marker/navigation-marker.ts
  src/components/select/select.ts
  src/components/skiplink-list/skiplink-list.ts
  src/components/tabs/tab-group/tab-group.ts
  src/components/tag/tag-group/tag-group.ts
  src/components/train/train-formation/train-formation.ts
  src/components/train/train-wagon/train-wagon.ts
  src/components/train/train/train.ts
  tools/eslint/index.ts
  tools/eslint/local-name-rule.ts
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2606 feat(notification): add size 's'
  src/components/notification/__snapshots__/notification.spec.snap.js
  src/components/notification/notification.scss
  src/components/notification/notification.spec.ts
  src/components/notification/notification.stories.ts
  src/components/notification/notification.ts
  src/components/notification/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved

#2603 feat(sbb-accordion, sbb-expansion-panel): add size s
  src/components/accordion/__snapshots__/accordion.spec.snap.js
  src/components/accordion/accordion.e2e.ts
  src/components/accordion/accordion.stories.ts
  src/components/accordion/accordion.ts
  src/components/accordion/readme.md
  src/components/expansion-panel/expansion-panel-content/expansion-panel-content.scss
  src/components/expansion-panel/expansion-panel-header/expansion-panel-header.scss
  src/components/expansion-panel/expansion-panel/__snapshots__/expansion-panel.spec.snap.js
  src/components/expansion-panel/expansion-panel/expansion-panel.e2e.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.scss
  src/components/expansion-panel/expansion-panel/expansion-panel.spec.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.stories.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/expansion-panel/expansion-panel/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review required, pr: ux review approved

#2613 fix: enable next.js 14 support and add some upstream fixes
  src/react/core/create-component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2618 feat: reduce font-faces to single SBB variant
  docs/GETTING_STARTED.md
  package.json
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.scss
  src/components/core/styles/mixins/font-face.scss
  src/components/core/styles/mixins/panel.scss
  src/components/core/styles/mixins/typo.scss
  src/components/core/styles/typography.scss
  src/components/form-field/form-field/form-field.scss
  src/components/loading-indicator/loading-indicator.stories.ts
  src/components/menu/menu-link/menu-link.stories.ts
  src/components/menu/menu/menu.stories.ts
  src/components/pearl-chain-vertical/pearl-chain-vertical.stories.ts
  src/components/skiplink-list/skiplink-list.stories.ts
  src/components/tabs/tab-group/tab-group.stories.ts
  src/storybook/styles/list/list.stories.ts
  src/storybook/styles/typography/readme.md
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved

#2615 feat: split css outputs into smaller modules
  .storybook/preview.ts
  docs/GETTING_STARTED.md
  src/components/core/styles/a11y.scss
  src/components/core/styles/animation.scss
  src/components/core/styles/core.scss
  src/components/core/styles/font-characters-extension.scss
  src/components/core/styles/global.scss
  src/components/core/styles/layout.scss
  src/components/core/styles/lists.scss
  src/components/core/styles/mixins/typo.scss
  src/components/core/styles/normalize.scss
  src/components/core/styles/standard-theme.scss
  src/components/core/styles/typography.scss
  src/components/vite.config.ts
  tools/vite/typography.ts
  web-test-runner.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved
