Repository sbb-design-systems/lyne-components, pull requests merged in 2024-05, with the labels that each got.

#2630 fix(sbb-loading-indicator): fix sizes of loading indicator
  src/components/loading-indicator/loading-indicator.scss
  src/components/loading-indicator/loading-indicator.stories.ts
Labels: pr: peer review approved

#2628 fix(sbb-tab-group): avoid unwanted margin block spaces
  src/components/container/container/container.scss
  src/components/core/styles/mixins/helpers.scss
  src/components/tabs/tab-group/tab-group.scss
  src/components/tabs/tab-group/tab-group.stories.ts
Labels: pr: peer review approved

#2641 feat: add root entry point with global component registration
  src/components/vite.config.ts
  tools/vite/generate-root-entry-point.ts
  tools/vite/index.ts
Labels: preview-available, pr: peer review required

#2634 docs: add section about focus outlines
  docs/GETTING_STARTED.md
  src/storybook/styles/layout/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2637 fix(sbb-dialog): show all content if header is always present
  src/components/dialog/dialog-content/dialog-content.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2640 feat(sbb-container): allow expanded background color
  src/components/container/container/container.scss
  src/components/container/container/container.stories.ts
  src/components/container/container/container.ts
  src/components/container/container/readme.md
  src/components/container/sticky-bar/sticky-bar.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2642 refactor: use typed PropertyValues and always call super method of willChange
  src/components/accordion/accordion.ts
  src/components/action-group/action-group.ts
  src/components/autocomplete/autocomplete.ts
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/calendar/calendar.ts
  src/components/checkbox/checkbox-group/checkbox-group.ts
  src/components/core/mixins/hydration-mixin.ts
  src/components/core/mixins/named-slot-list-mixin.ts
  src/components/core/mixins/required-mixin.ts
  src/components/datepicker/common/datepicker-button.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/datepicker/datepicker/datepicker.ts
  src/components/dialog/dialog-title/__snapshots__/dialog-title.spec.snap.js
  src/components/dialog/dialog-title/dialog-title.spec.ts
  src/components/dialog/dialog-title/dialog-title.ts
  src/components/dialog/dialog/__snapshots__/dialog.spec.snap.js
  src/components/dialog/dialog/dialog.ts
  src/components/divider/divider.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/form-field/form-field/form-field.ts
  src/components/icon/icon.ts
  src/components/link-list/link-list.ts
  src/components/navigation/navigation-list/navigation-list.ts
  src/components/navigation/navigation-marker/navigation-marker.ts
  src/components/option/optgroup/optgroup.ts
  src/components/option/option/option.ts
  src/components/overlay/overlay.ts
  src/components/popover/popover/popover.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/select/select.ts
  src/components/selection-panel/selection-panel.ts
  src/components/skiplink-list/skiplink-list.ts
  src/components/tag/tag-group/tag-group.ts
  src/components/timetable-occupancy-icon/timetable-occupancy-icon.ts
  src/components/timetable-row/timetable-row.ts
  src/components/title/title-base.ts
  src/components/toggle/toggle-option/toggle-option.ts
  src/components/toggle/toggle/toggle.ts
  src/components/train/train-formation/train-formation.ts
  src/components/train/train-wagon/train-wagon.ts
  src/components/train/train/train.ts
  tools/generate-component/boilerplate/component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2541 refactor(expansion-panel, notification): migrate from transition to animation
  src/components/expansion-panel/expansion-panel/expansion-panel.e2e.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.scss
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/notification/notification.scss
  src/components/notification/notification.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2643 feat: add default entries for style exports in package.json
  src/components/vite.config.ts
Labels: pr: peer review required

#2644 fix: fix super calls of lit element lifecycle methods
  src/components/alert/alert/alert.ts
  src/components/checkbox/checkbox/checkbox.ts
  src/components/clock/clock.ts
  src/components/container/sticky-bar/sticky-bar.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/image/image.ts
  src/components/notification/notification.ts
  src/components/popover/popover/popover.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/select/select.ts
  src/components/selection-panel/selection-panel.ts
  src/components/tabs/tab-group/tab-group.ts
  src/storybook/helpers/spread.ts
  tools/eslint/index.ts
  tools/eslint/needs-super-call-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2650 fix(sbb-alert): improve SSR hydration support
  src/components/alert/alert-group/alert-group.ts
  src/components/core/mixins/hydration-mixin.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2624 build: implement visual regression testing with @web/test-runner
  .github/default.conf
  .github/workflows/container-image-cleanup.yml
  .github/workflows/continuous-integration-secure.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/preview-image-cleanup.yml
  .github/workflows/release-please.yml
  Dockerfile
  eslint.config.js
  package.json
  src/components/accordion/accordion.e2e.ts
  src/components/button/button/button.snapshot.spec.ts
  src/components/button/common/button-common.scss
  src/components/button/common/common-stories.ts
  src/components/core/testing.ts
  src/components/core/testing/private.ts
  src/components/core/testing/private/a11y-tree-snapshot.ts
  src/components/core/testing/private/describe-each.ts
  src/components/core/testing/private/describe-viewports.ts
  src/components/core/testing/private/fixture.ts
  src/components/core/testing/private/platform.ts
  src/components/core/testing/private/visual-regression-snapshot.ts
  src/components/core/testing/test-setup-ssr.ts
  src/components/core/testing/test-setup.ts
  src/visual-regression-app/index.html
  src/visual-regression-app/src/components/overview/overview.scss
  src/visual-regression-app/src/components/overview/overview.ts
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.scss
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.scss
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.scss
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
  src/visual-regression-app/src/components/test-case/test-case.scss
  src/visual-regression-app/src/components/test-case/test-case.ts
  src/visual-regression-app/src/interfaces.ts
  src/visual-regression-app/src/main.ts
  src/visual-regression-app/src/screenshots.ts
  src/visual-regression-app/tsconfig.json
  src/visual-regression-app/vite.config.ts
  src/vite-env.d.ts
  tools/visual-regression-testing/baseline.Dockerfile
  tools/visual-regression-testing/baseline.nginx.conf
  tools/visual-regression-testing/diff-app.Dockerfile
  tools/visual-regression-testing/etag-map-generation.sh
  tools/visual-regression-testing/exec.ts
  tools/visual-regression-testing/testing.Dockerfile
  tools/visual-regression-testing/testing.Dockerfile.dockerignore
  tools/web-test-runner/index.js
  tools/web-test-runner/visual-regression-plugin-config.js
  web-test-runner.config.js
  yarn.lock
Labels: preview-available, pr: peer review required

#2659 build: fix storybook build
  .github/workflows/continuous-integration.yml
  .storybook/main.ts
  .storybook/preview.ts
  tools/visual-regression-testing/exec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2665 build: show visual regression app for baseline images
  .github/workflows/continuous-integration-secure.yml
  .github/workflows/continuous-integration.yml
  src/visual-regression-app/src/components/overview/overview.ts
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
  src/visual-regression-app/src/components/test-case/test-case.ts
  src/visual-regression-app/src/interfaces.ts
  src/visual-regression-app/src/screenshots.ts
  src/visual-regression-app/vite.config.ts
  tools/visual-regression-testing/Dockerfile
  tools/visual-regression-testing/baseline.Dockerfile
  tools/visual-regression-testing/etag-map-generation.sh
  tools/visual-regression-testing/visual-regression.nginx.conf
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2661 fix: prevent stack overflow with attribute changes
  src/components/core/base-elements/button-base-element.ts
  src/components/core/mixins/form-associated-mixin.ts
  src/components/option/option/option.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2666 build: stabilize visual regression testing
  src/components/button/button/button.snapshot.spec.ts
  src/components/core/testing/private/describe-viewports.ts
  src/components/core/testing/private/fixture.ts
  src/components/core/testing/private/visual-regression-snapshot.ts
  tools/visual-regression-testing/testing.Dockerfile
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2673 refactor(sbb-image): apply styling according to coding standards
  src/components/image/__snapshots__/image.spec.snap.js
  src/components/image/image.e2e.ts
  src/components/image/image.helper.ts
  src/components/image/image.scss
  src/components/image/image.spec.ts
  src/components/image/image.ts
  src/components/image/readme.md
  src/components/message/__snapshots__/message.spec.snap.js
  src/components/teaser-hero/__snapshots__/teaser-hero.spec.snap.js
  src/components/teaser-hero/teaser-hero.spec.ts
  src/components/teaser-paid/teaser-paid.e2e.ts
Labels: pr: peer review required, pr: lead review approved

#2679 build: improve test runner concurrency
  tools/web-test-runner/vite-plugin.js
  web-test-runner.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved

#2678 fix(sbb-button): fix gap between icon and text for size s
  src/components/button/button/button.snapshot.spec.ts
  src/components/button/common/button-common.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review approved, visual-regression-diff-available

#2656 feat(journey-header): add size s
  src/components/journey-header/journey-header.stories.ts
  src/components/journey-header/journey-header.ts
  src/components/journey-header/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2692 fix(sbb-radio-button): fix checked initialization
  src/components/radio-button/radio-button-group/radio-button-group.e2e.ts
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/radio-button/radio-button/radio-button.e2e.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/react/core/create-component.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2688 feat(sbb-popover): change close button size
  src/components/popover/popover/__snapshots__/popover.spec.snap.js
  src/components/popover/popover/popover.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review approved, visual-regression-diff-available

#2677 refactor: convert platform functions to constants
  src/components/accordion/accordion.e2e.ts
  src/components/autocomplete/autocomplete.spec.ts
  src/components/autocomplete/autocomplete.ts
  src/components/button/button/button.snapshot.spec.ts
  src/components/checkbox/checkbox/checkbox.e2e.ts
  src/components/core/a11y/input-modality-detector.ts
  src/components/core/controllers/language-controller.ts
  src/components/core/dom/breakpoint.ts
  src/components/core/dom/find-referenced-element.ts
  src/components/core/dom/get-document-writing-mode.ts
  src/components/core/dom/host-context.ts
  src/components/core/dom/platform.ts
  src/components/core/testing/private/a11y-tree-snapshot.ts
  src/components/core/testing/private/fixture.ts
  src/components/core/testing/private/platform.ts
  src/components/core/testing/test-setup.ts
  src/components/form-field/form-field/form-field.ts
  src/components/header/header/header.ts
  src/components/image/image.ts
  src/components/lead-container/lead-container.snapshot.spec.ts
  src/components/option/optgroup/optgroup.spec.ts
  src/components/option/optgroup/optgroup.ts
  src/components/option/option/option.ts
  src/components/select/select.spec.ts
  src/components/select/select.ts
  src/components/toast/toast.spec.ts
  src/components/toast/toast.ts
  src/components/toggle-check/toggle-check.e2e.ts
  src/components/toggle/toggle/toggle.ts
Labels: preview-available, pr: peer review required, pr: visual review required, visual-regression-diff-available

#2651 style(sbb-button): button disabled state
  src/components/button/common/button-common.scss
  src/components/core/styles/mixins/buttons.scss
Labels: preview-available, ux approved, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2683 feat(sbb-tab-group): add size s variant
  src/components/tabs/tab-group/readme.md
  src/components/tabs/tab-group/tab-group.stories.ts
  src/components/tabs/tab-group/tab-group.ts
  src/components/tabs/tab-title/tab-title.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review approved, visual-regression-diff-available

#2698 build: configure Node.js esm hooks
  .nvmrc
  eslint.config.js
  package.json
  src/elements-experimental/journey-summary/journey-summary.ts
  src/elements-experimental/pearl-chain-time/pearl-chain-time.ts
  src/elements-experimental/pearl-chain/pearl-chain.ts
  src/elements-experimental/timetable-duration/timetable-duration.ts
  src/elements-experimental/timetable-row/timetable-row.ts
  src/elements-experimental/vite.config.ts
  src/react-experimental/vite.config.ts
  src/react/vite.config.ts
  tools/node-esm-hook/lyne-alias-hook.js
  tools/node-esm-hook/register-hooks.js
  tools/node-esm-hook/sass-hook.js
  tools/node-esm-hook/typescript-hook.js
  tools/vite/verify-entry-points.ts
  tools/web-test-runner/index.ts
  tools/web-test-runner/lit-ssr-worker.js
  tools/web-test-runner/minimal-reporter.ts
  tools/web-test-runner/patched-summary-reporter.js
  tools/web-test-runner/patched-summary-reporter.ts
  tools/web-test-runner/ssr-plugin.js
  tools/web-test-runner/visual-regression-plugin-config.js
  tools/web-test-runner/visual-regression-plugin-config.ts
  tools/web-test-runner/vite-plugin.ts
  web-test-runner.config.ts
  yarn.lock
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, visual-regression-diff-available

#2704 chore(sbb-lead-container): fix story path
  src/elements/lead-container/lead-container.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved
