Repository sbb-design-systems/lyne-components, pull requests merged in 2024-12, with the labels that each got.

#3263 test: fix flip card visual tests
  src/elements/flip-card/flip-card/flip-card.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3259 build: fix type of globalThis
  src/elements/core/config/config.ts
  src/elements/icon/icon.snapshot.spec.ts
  src/elements/navigation/navigation/navigation.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3250 fix(sbb-teaser, sbb-teaser-product): allow screen readers to navigate the content
  src/elements/core/base-elements/link-base-element.ts
  src/elements/teaser-product/common/teaser-product-common.scss
  src/elements/teaser-product/common/teaser-product-common.ts
  src/elements/teaser-product/teaser-product-static/__snapshots__/teaser-product-static.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product/__snapshots__/teaser-product.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product/teaser-product.scss
  src/elements/teaser-product/teaser-product/teaser-product.stories.ts
  src/elements/teaser-product/teaser-product/teaser-product.ts
  src/elements/teaser/__snapshots__/teaser.snapshot.spec.snap.js
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.ts
  src/elements/teaser/teaser.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: a11y review approved, pr: visual review required, diff-available, target: 1.x

#3264 fix(sbb-teaser, sbb-teaser-product): allow screen readers to navigate the content
  src/elements/core/base-elements/link-base-element.ts
  src/elements/teaser-product/common/teaser-product-common.scss
  src/elements/teaser-product/common/teaser-product-common.ts
  src/elements/teaser-product/teaser-product-static/__snapshots__/teaser-product-static.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product/__snapshots__/teaser-product.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product/teaser-product.scss
  src/elements/teaser-product/teaser-product/teaser-product.stories.ts
  src/elements/teaser-product/teaser-product/teaser-product.ts
  src/elements/teaser/__snapshots__/teaser.snapshot.spec.snap.js
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.ts
  src/elements/teaser/teaser.visual.spec.ts
Labels: pr: peer review required, pr: lead review approved

#3270 refactor(sbb-alert): remove sbb-link from shadow DOM
  src/elements/alert/alert-group/__snapshots__/alert-group.snapshot.spec.snap.js
  src/elements/alert/alert-group/alert-group.snapshot.spec.ts
  src/elements/alert/alert-group/alert-group.spec.ts
  src/elements/alert/alert-group/alert-group.ssr.spec.ts
  src/elements/alert/alert-group/alert-group.stories.ts
  src/elements/alert/alert-group/alert-group.visual.spec.ts
  src/elements/alert/alert-group/readme.md
  src/elements/alert/alert/__snapshots__/alert.snapshot.spec.snap.js
  src/elements/alert/alert/alert.snapshot.spec.ts
  src/elements/alert/alert/alert.stories.ts
  src/elements/alert/alert/alert.ts
  src/elements/alert/alert/alert.visual.spec.ts
  src/elements/alert/alert/readme.md
  src/elements/core/i18n/i18n.ts
  src/elements/lead-container/lead-container.stories.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/lead-container/readme.md
  src/storybook/pages/home/home.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3277 fix(sbb-form-field): update floating label on programmatic changes
  src/elements/form-field/form-field/form-field.spec.ts
  src/elements/form-field/form-field/form-field.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3278 fix: opening and close events no longer bubble
  src/elements/accordion/accordion.spec.ts
  src/elements/accordion/accordion.ssr.spec.ts
  src/elements/accordion/accordion.ts
  src/elements/alert/alert-group/alert-group.ssr.spec.ts
  src/elements/alert/alert-group/alert-group.ts
  src/elements/alert/alert/alert.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-optgroup/autocomplete-grid-optgroup.visual.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.visual.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.visual.spec.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.visual.spec.ts
  src/elements/container/sticky-bar/sticky-bar.ts
  src/elements/core/base-elements/open-close-base-element.ts
  src/elements/core/testing/event-spy.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/expansion-panel/expansion-panel/expansion-panel.spec.ts
  src/elements/expansion-panel/expansion-panel/expansion-panel.ts
  src/elements/form-field/form-field/form-field.scss
  src/elements/form-field/form-field/form-field.ts
  src/elements/header/header/header.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/notification/notification.spec.ts
  src/elements/notification/notification.ts
  src/elements/option/optgroup/optgroup.visual.spec.ts
  src/elements/option/option/option.visual.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/popover/popover-trigger/popover-trigger.spec.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/popover/popover/popover.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.visual.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
  src/elements/toast/toast.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3283 docs: fix link in the contributing guideline
  docs/CONTRIBUTING.md
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3282 docs: fix package names
  README.md
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3200 feat(sbb-image): support overlapping `sbb-chip-label`
  src/elements/container/container/container.scss
  src/elements/container/container/container.visual.spec.ts
  src/elements/container/container/readme.md
  src/elements/core/styles/_index.scss
  src/elements/core/styles/core.scss
  src/elements/core/styles/image.scss
  src/elements/core/styles/mixins/image.scss
  src/elements/core/styles/standard-theme.scss
  src/elements/flip-card/flip-card-summary/__snapshots__/flip-card-summary.snapshot.spec.snap.js
  src/elements/flip-card/flip-card-summary/flip-card-summary.scss
  src/elements/flip-card/flip-card-summary/readme.md
  src/elements/flip-card/flip-card/__snapshots__/flip-card.snapshot.spec.snap.js
  src/elements/flip-card/flip-card/flip-card.stories.ts
  src/elements/flip-card/flip-card/flip-card.visual.spec.ts
  src/elements/image/__snapshots__/image.snapshot.spec.snap.js
  src/elements/image/image.scss
  src/elements/image/image.stories.ts
  src/elements/image/image.ts
  src/elements/image/image.visual.spec.ts
  src/elements/image/readme.md
  src/elements/lead-container/__snapshots__/lead-container.snapshot.spec.snap.js
  src/elements/lead-container/lead-container.scss
  src/elements/lead-container/lead-container.stories.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/lead-container/readme.md
  src/elements/message/__snapshots__/message.snapshot.spec.snap.js
  src/elements/teaser-hero/__snapshots__/teaser-hero.snapshot.spec.snap.js
  src/elements/teaser-hero/readme.md
  src/elements/teaser-hero/teaser-hero.scss
  src/elements/teaser-hero/teaser-hero.snapshot.spec.ts
  src/elements/teaser-hero/teaser-hero.spec.ts
  src/elements/teaser-hero/teaser-hero.ssr.spec.ts
  src/elements/teaser-hero/teaser-hero.stories.ts
  src/elements/teaser-hero/teaser-hero.ts
  src/elements/teaser-hero/teaser-hero.visual.spec.ts
  src/elements/teaser-product/common/teaser-product-common.scss
  src/elements/teaser-product/teaser-product-static/__snapshots__/teaser-product-static.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product-static/readme.md
  src/elements/teaser-product/teaser-product-static/teaser-product-static.snapshot.spec.ts
  src/elements/teaser-product/teaser-product-static/teaser-product-static.spec.ts
  src/elements/teaser-product/teaser-product-static/teaser-product-static.ssr.spec.ts
  src/elements/teaser-product/teaser-product-static/teaser-product-static.stories.ts
  src/elements/teaser-product/teaser-product-static/teaser-product-static.visual.spec.ts
  src/elements/teaser-product/teaser-product/__snapshots__/teaser-product.snapshot.spec.snap.js
  src/elements/teaser-product/teaser-product/readme.md
  src/elements/teaser-product/teaser-product/teaser-product.scss
  src/elements/teaser-product/teaser-product/teaser-product.snapshot.spec.ts
  src/elements/teaser-product/teaser-product/teaser-product.spec.ts
  src/elements/teaser-product/teaser-product/teaser-product.ssr.spec.ts
  src/elements/teaser-product/teaser-product/teaser-product.stories.ts
  src/elements/teaser-product/teaser-product/teaser-product.visual.spec.ts
  src/elements/teaser/__snapshots__/teaser.snapshot.spec.snap.js
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.snapshot.spec.ts
  src/elements/teaser/teaser.stories.ts
  src/elements/teaser/teaser.visual.spec.ts
  src/storybook/pages/home/home.common.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3251 fix(sbb-tab-group): correctly select a new tab if it is 'active'
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/tabs/tab-group/tab-group.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3285 feat: provide scrollbar and table styles as CSS classes
  docs/GETTING_STARTED.md
  src/elements/core/styles/scrollbar.scss
  src/elements/core/styles/standard-theme.scss
  src/elements/vite.config.ts
  src/storybook/styles/layout/readme.md
  src/storybook/styles/list/readme.md
  src/storybook/styles/scrollbar/readme.md
  src/storybook/styles/scrollbar/scrollbar-internal.scss
  src/storybook/styles/scrollbar/scrollbar.stories.ts
  src/storybook/styles/scrollbar/scrollbar.visual.spec.ts
  src/storybook/styles/table/readme.md
  src/storybook/styles/typography/readme.md
  tools/vite/typography.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3288 fix: fix mixin due to wrong manifest generation
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/radio-button/common/radio-button-common.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3293 fix(sbb-teaser): fix image related issues
  src/elements/core/styles/core.scss
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.stories.ts
  src/elements/teaser/teaser.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3294 fix(sbb-message): support the use of `figure` as image
  src/elements/core/styles/core.scss
  src/elements/message/message.scss
  src/elements/message/message.visual.spec.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, target: 2.x

#3292 feat: add class generic type param in manifest
  tools/manifest/custom-elements-manifest.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3290 docs: standardize usage of terms `CSS` and `Sass`
  docs/CODING_STANDARDS.md
  docs/CONTRIBUTING.md
  docs/DEVELOPER.md
  docs/GETTING_STARTED.md
  docs/REVIEW.md
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.scss
  src/elements/button/accent-button-link/readme.md
  src/elements/button/accent-button-static/readme.md
  src/elements/button/accent-button/readme.md
  src/elements/button/button-link/readme.md
  src/elements/button/button-static/readme.md
  src/elements/button/button/readme.md
  src/elements/button/common/button-common.scss
  src/elements/button/mini-button/mini-button.scss
  src/elements/button/mini-button/readme.md
  src/elements/button/secondary-button-link/readme.md
  src/elements/button/secondary-button-static/readme.md
  src/elements/button/secondary-button/readme.md
  src/elements/button/transparent-button-link/readme.md
  src/elements/button/transparent-button-static/readme.md
  src/elements/button/transparent-button/readme.md
  src/elements/card/common/card-action.scss
  src/elements/checkbox/checkbox/checkbox.scss
  src/elements/core/mixins/panel-common.scss
  src/elements/core/styles/core.scss
  src/elements/core/styles/mixins/buttons.scss
  src/elements/footer/footer.ts
  src/elements/footer/readme.md
  src/elements/form-field/form-field-clear/form-field-clear.scss
  src/elements/form-field/form-field/form-field.scss
  src/elements/header/common/header-action.scss
  src/elements/header/header/header.scss
  src/elements/image/image.ts
  src/elements/image/readme.md
  src/elements/link/common/link.scss
  src/elements/menu/common/menu-action.scss
  src/elements/navigation/common/navigation-action.scss
  src/elements/notification/notification.scss
  src/elements/popover/popover-trigger/popover-trigger.scss
  src/elements/radio-button/radio-button/radio-button.scss
  src/elements/slider/slider.scss
  src/elements/tabs/tab-label/tab-label.scss
  src/elements/tag/tag/tag.scss
  src/elements/teaser-hero/teaser-hero.scss
  src/elements/teaser/teaser.scss
  src/elements/toggle-check/toggle-check.scss
  src/elements/toggle/toggle-option/toggle-option.scss
  src/storybook/styles/layout/layout.stories.ts
  src/storybook/styles/layout/readme.md
  src/storybook/styles/list/readme.md
  src/storybook/styles/scrollbar/readme.md
  src/storybook/styles/table/readme.md
  src/storybook/styles/typography/readme.md
  tools/node-esm-hook/sass-hook.js
  vite.config.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3295 fix(sbb-teaser-hero): fix image size on custom width
  src/elements/core/styles/core.scss
  src/elements/teaser-hero/teaser-hero.scss
  src/elements/teaser-hero/teaser-hero.visual.spec.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, target: 2.x

#3300 fix(sbb-select): update displayed value on option label change
  src/elements/option/option/option-base-element.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3305 fix(sbb-message): fix image alignment
  src/elements/message/message.scss
  src/elements/message/message.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3303 test(sbb-teaser): improve test stability
  src/elements/teaser/teaser.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3302 fix: improve null/undefined type handling for Angular wrapper
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/navigation/common/navigation-action-common.ts
  src/elements/slider/slider.ts
  src/elements/stepper/step/step.ts
  src/elements/stepper/stepper/readme.md
  src/elements/stepper/stepper/stepper.ts
  src/elements/tag/tag-group/tag-group.ts
  src/elements/time-input/time-input.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3307 docs: override prop in manifest
  src/elements/button/accent-button/readme.md
  src/elements/button/button/readme.md
  src/elements/button/mini-button/readme.md
  src/elements/button/secondary-button/readme.md
  src/elements/button/transparent-button/readme.md
  src/elements/card/card-button/readme.md
  src/elements/core/base-elements/button-base-element.ts
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/expansion-panel/expansion-panel-header/readme.md
  src/elements/form-field/form-field-clear/readme.md
  src/elements/header/header-button/readme.md
  src/elements/link/block-link-button/readme.md
  src/elements/link/link-button/readme.md
  src/elements/menu/menu-button/readme.md
  src/elements/navigation/navigation-button/readme.md
  src/elements/popover/popover-trigger/readme.md
  src/elements/stepper/step-label/readme.md
  src/elements/tag/tag/readme.md
  tools/manifest/custom-elements-manifest.config.js
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3314 refactor: move event handlers to constructors
  src/elements/accordion/accordion.ts
  src/elements/alert/alert-group/alert-group.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.ts
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/elements/checkbox/checkbox-group/checkbox-group.ts
  src/elements/core/controllers/connected-abort-controller.ts
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/datepicker/common/datepicker-button.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/elements/expansion-panel/expansion-panel/expansion-panel.ts
  src/elements/flip-card/flip-card/flip-card.ts
  src/elements/form-field/form-field-clear/form-field-clear.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/common/navigation-action-common.ts
  src/elements/navigation/navigation-section/navigation-section.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/option/option/option-base-element.ts
  src/elements/overlay/overlay-base-element.ts
  src/elements/radio-button/common/radio-button-common.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/select/select.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
  src/elements/slider/slider.ts
  src/elements/stepper/step-label/step-label.ts
  src/elements/stepper/step/step.ts
  src/elements/stepper/stepper/stepper.ts
  src/elements/tabs/tab-group/tab-group.ts
  src/elements/tag/tag/tag.ts
  src/elements/toast/toast.ts
  src/elements/toggle/toggle-option/toggle-option.ts
  src/elements/toggle/toggle/toggle.ts
  src/elements/train/train-formation/train-formation.ts
  tools/generate-component/boilerplate/component.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, target: 2.x

#3311 fix: remove leading inline padding from icon list
  src/elements/core/styles/mixins/lists.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required, pr: visual review required, diff-available, target: 2.x

#3313 fix(sbb-accent-button): adapt to new design
  src/elements/button/common/accent-button.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3310 fix: handle scroll events in custom scroll contexts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/core/eventing/forward-event.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/dialog/dialog-content/dialog-content.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/file-selector/common/file-selector-common.ts
  src/elements/map-container/map-container.spec.ts
  src/elements/map-container/map-container.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/notification/notification.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/overlay/overlay.ts
  src/elements/popover/popover/popover.ts
  src/elements/select/select.ts
  src/elements/slider/slider.ts
  src/elements/time-input/time-input.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3315 build: allow sequential use of docker slim
  .github/actions/docker-slim/action.yml
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3322 build: attempt to fix docker slim
  .github/actions/docker-slim/action.yml
Labels: pr: peer review required, target: 2.x

#3323 fix(sbb-radio-button-group): sync radios synchronously
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/radio-button/common/radio-button-common.ts
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ts
  src/elements/radio-button/radio-button/radio-button.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3327 fix: fix active color of buttons
  src/elements/button/common/button-common.scss
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x
