Repository sbb-design-systems/lyne-components, pull requests merged in 2024-09, with the labels that each got.

#3052 refactor: remove font-smoothing
  src/elements/button/common/button-common.scss
  src/elements/core/styles/mixins/panel.scss
  src/elements/core/styles/mixins/typo.scss
  src/elements/tabs/tab-label/tab-label.scss
  src/elements/teaser-hero/teaser-hero.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3055 fix(option-base): use data-active instead of active attribute
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.scss
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.visual.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/readme.md
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.ts
  src/elements/option/option/__snapshots__/option.snapshot.spec.snap.js
  src/elements/option/option/option-base-element.ts
  src/elements/option/option/option.scss
  src/elements/option/option/option.snapshot.spec.ts
  src/elements/option/option/option.visual.spec.ts
  src/elements/option/option/readme.md
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3060 fix(sbb-image): improve default image cdn config
  src/elements/image/__snapshots__/image.snapshot.spec.snap.js
  src/elements/image/image.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3059 fix(sbb-expansion-panel-header): fix height if disabled
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.scss
  src/elements/expansion-panel/expansion-panel/expansion-panel.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3040 feat: keep action elements focusable when disabled
  src/elements/button/button-link/__snapshots__/button-link.snapshot.spec.snap.js
  src/elements/button/button/__snapshots__/button.snapshot.spec.snap.js
  src/elements/button/button/button.ts
  src/elements/button/button/readme.md
  src/elements/button/mini-button/mini-button.ts
  src/elements/button/mini-button/readme.md
  src/elements/button/secondary-button-link/__snapshots__/secondary-button-link.snapshot.spec.snap.js
  src/elements/button/secondary-button/__snapshots__/secondary-button.snapshot.spec.snap.js
  src/elements/button/secondary-button/readme.md
  src/elements/button/secondary-button/secondary-button.ts
  src/elements/button/tertiary-button-link/__snapshots__/tertiary-button-link.snapshot.spec.snap.js
  src/elements/button/tertiary-button/__snapshots__/tertiary-button.snapshot.spec.snap.js
  src/elements/button/tertiary-button/readme.md
  src/elements/button/tertiary-button/tertiary-button.ts
  src/elements/button/transparent-button-link/__snapshots__/transparent-button-link.snapshot.spec.snap.js
  src/elements/button/transparent-button/__snapshots__/transparent-button.snapshot.spec.snap.js
  src/elements/button/transparent-button/readme.md
  src/elements/button/transparent-button/transparent-button.ts
  src/elements/core/base-elements/link-base-element.ts
  src/elements/core/mixins/disabled-mixin.ts
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.scss
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/elements/expansion-panel/expansion-panel/readme.md
  src/elements/link/block-link-button/block-link-button.ts
  src/elements/link/block-link-button/readme.md
  src/elements/link/link-button/link-button.ts
  src/elements/link/link-button/readme.md
  src/elements/menu/menu-button/menu-button.ts
  src/elements/menu/menu-button/readme.md
  src/elements/menu/menu-link/menu-link.stories.ts
  src/elements/menu/menu/__snapshots__/menu.snapshot.spec.snap.js
  src/elements/menu/menu/menu.ts
  src/elements/popover/popover-trigger/popover-trigger.spec.ts
  src/elements/popover/popover-trigger/popover-trigger.ts
  src/elements/slider/slider.ts
  src/elements/tag/tag/__snapshots__/tag.snapshot.spec.snap.js
  src/elements/tag/tag/readme.md
  src/elements/tag/tag/tag.ts
  src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3030 feat(sbb-selection-expansion-panel): introduce size s
  src/elements/core/mixins/panel-common.scss
  src/elements/selection-expansion-panel/__snapshots__/selection-expansion-panel.snapshot.spec.snap.js
  src/elements/selection-expansion-panel/readme.md
  src/elements/selection-expansion-panel/selection-expansion-panel.scss
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.stories.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3066 fix(sbb-pearl-chain): fix spacing of bullet points
  src/elements-experimental/pearl-chain/pearl-chain.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3065 fix(sbb-dialog): fix resizing flickering
  src/elements/dialog/dialog/dialog.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3068 build: enable eslint member ordering rule
  eslint.config.js
  src/elements/accordion/accordion.ts
  src/elements/action-group/action-group.ts
  src/elements/alert/alert/alert.ts
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/calendar/calendar.ts
  src/elements/clock/clock.ts
  src/elements/core/a11y/focus-visible-within-controller.ts
  src/elements/core/a11y/input-modality-detector.ts
  src/elements/core/base-elements/button-base-element.ts
  src/elements/core/controllers/slot-state-controller.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/file-selector/file-selector.ts
  src/elements/option/optgroup/optgroup-base-element.ts
  src/elements/option/option/option-base-element.ts
  src/elements/overlay/overlay-base-element.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/stepper/step-label/step-label.ts
  src/elements/stepper/stepper/stepper.ts
  src/elements/tabs/tab-group/tab-group.ts
  src/elements/toggle/toggle/toggle.ts
  src/visual-regression-app/src/screenshots.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3077 feat(table): introduce table size xs
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/table.scss
  src/storybook/styles/table/readme.md
  src/storybook/styles/table/table.stories.ts
  src/storybook/styles/table/table.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3048 feat(sbb-timetable-row): provide a11y footpaths
  src/elements-experimental/core/timetable/access-leg-helper.spec.ts
  src/elements-experimental/core/timetable/access-leg-helper.ts
  src/elements-experimental/pearl-chain-time/__snapshots__/pearl-chain-time.snapshot.spec.snap.js
  src/elements-experimental/pearl-chain-time/pearl-chain-time.scss
  src/elements-experimental/pearl-chain-time/pearl-chain-time.ts
  src/elements-experimental/pearl-chain-time/readme.md
  src/elements-experimental/pearl-chain/pearl-chain.sample-data.ts
  src/elements-experimental/timetable-row/__snapshots__/timetable-row.snapshot.spec.snap.js
  src/elements-experimental/timetable-row/readme.md
  src/elements-experimental/timetable-row/timetable-row.sample-data.ts
  src/elements-experimental/timetable-row/timetable-row.snapshot.spec.ts
  src/elements-experimental/timetable-row/timetable-row.stories.ts
  src/elements-experimental/timetable-row/timetable-row.ts
  src/elements-experimental/timetable-row/timetable-row.visual.spec.ts
  tools/web-test-runner/preload-icons.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3081 fix(sbb-icon): ensure sbb-angular compatibility
  src/elements/icon/icon.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3047 feat(sbb-header): introduce size s
  .storybook/preview-head.html
  src/elements/core/styles/core.scss
  src/elements/header/common/header-action.scss
  src/elements/header/header/__snapshots__/header.snapshot.spec.snap.js
  src/elements/header/header/header.scss
  src/elements/header/header/header.stories.ts
  src/elements/header/header/header.ts
  src/elements/header/header/header.visual.spec.ts
  src/elements/header/header/readme.md
  src/elements/logo/logo.scss
  src/elements/logo/logo.visual.spec.ts
  src/elements/signet/readme.md
  src/elements/signet/signet.scss
  src/elements/signet/signet.stories.ts
  src/elements/signet/signet.ts
  src/elements/signet/signet.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3080 test: respect state element for visual focus tests
  src/elements/core/testing/private/visual-regression-snapshot.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.visual.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.visual.spec.ts
  src/elements/form-field/form-field/form-field.visual.spec.ts
  src/elements/header/header/header.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3074 refactor: use lit observers
  package.json
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.ts
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/elements/card/common/card-action-common.ts
  src/elements/container/sticky-bar/sticky-bar.ts
  src/elements/core/controllers/language-controller.ts
  src/elements/core/observers/intersection-observer.ts
  src/elements/core/observers/mutation-observer.ts
  src/elements/core/observers/resize-observer.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/flip-card/flip-card-details/flip-card-details.spec.ts
  src/elements/flip-card/flip-card-details/flip-card-details.ts
  src/elements/form-field/form-field/form-field.ts
  src/elements/map-container/__snapshots__/map-container.snapshot.spec.snap.js
  src/elements/map-container/map-container.ts
  src/elements/navigation/navigation-marker/navigation-marker.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/notification/notification.ts
  src/elements/option/optgroup/optgroup-base-element.ts
  src/elements/option/option/option-base-element.ts
  src/elements/package.json
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
  src/elements/stepper/step/step.ts
  src/elements/table/table-wrapper/table-wrapper.ts
  src/elements/tabs/tab-group/tab-group.ts
  src/elements/toggle/toggle/toggle.ts
  src/elements/train/train-formation/train-formation.ts
  tools/vite/package-json-template.ts
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3089 test: stabilize visual tests
  src/elements/autocomplete-grid/autocomplete-grid-cell/autocomplete-grid-cell.visual.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-row/autocomplete-grid-row.visual.spec.ts
  src/elements/form-field/form-field/form-field.visual.spec.ts
  src/elements/header/header/header.visual.spec.ts
  src/elements/menu/menu-button/menu-button.visual.spec.ts
  src/elements/menu/menu-link/menu-link.visual.spec.ts
  src/elements/status/status.visual.spec.ts
  src/elements/tabs/tab-group/tab-group.visual.spec.ts
  src/elements/tag/tag-group/tag-group.visual.spec.ts
  src/elements/tag/tag/tag.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3099 refactor: use inert attribute instead of property hack
  src/elements/core/controllers/inert-controller.spec.ts
  src/elements/map-container/map-container.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
  src/elements/toggle/toggle-option/toggle-option.ts
  tsconfig.json
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3102 fix: assign correct dependency versions for published packages
  tools/vite/package-json-template.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3107 fix: prevent using HTMLElement in SSR context
  src/react/core/create-component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3110 refactor: remove obsolete `getLocalName()`
  src/elements/core/base-elements/action-base-element.ts
  src/elements/core/base-elements/link-base-element.ts
  src/elements/core/dom/ssr.ts
  src/elements/core/mixins/named-slot-list-mixin.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3112 build: refactor eslint rules
  eslint.config.js
  tools/eslint/custom-element-class-name-rule.ts
  tools/eslint/custom-element-decorator-position-rule.ts
  tools/eslint/import-extension-rule.ts
  tools/eslint/index.ts
  tools/eslint/local-name-rule.ts
  tools/eslint/missing-component-documentation-rule.ts
  tools/eslint/needs-super-call-rule.ts
  tools/eslint/property-decorator-accessor-rule.ts
  tools/eslint/test-describe-title-rule.ts
  tools/eslint/test-tabkey-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3113 fix: provide jsdom support for focus trap mechanism
  src/elements/core/a11y/focus.spec.ts
  src/elements/core/a11y/focus.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3116 fix(sbb-radio-group): disable focus when disabling radio
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3038 feat: add sbb-icon-list styles
  src/elements/_index.scss
  src/elements/core/styles/lists.scss
  src/elements/core/styles/mixins/lists.scss
  src/storybook/styles/list/list.stories.ts
  src/storybook/styles/list/list.visual.spec.ts
  src/storybook/styles/list/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3120 build: silence sass deprecation warning
  vite.config.ts
Labels: pr: peer review required, pr: lead review approved

#2982 feat(sbb-paginator): component implementation
  src/elements/core/i18n/i18n.ts
  src/elements/paginator.ts
  src/elements/paginator/__snapshots__/paginator.snapshot.spec.snap.js
  src/elements/paginator/index.ts
  src/elements/paginator/paginator.scss
  src/elements/paginator/paginator.snapshot.spec.ts
  src/elements/paginator/paginator.spec.ts
  src/elements/paginator/paginator.ssr.spec.ts
  src/elements/paginator/paginator.stories.ts
  src/elements/paginator/paginator.ts
  src/elements/paginator/paginator.visual.spec.ts
  src/elements/paginator/readme.md
  src/elements/select/select.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: a11y review approved, pr: visual review required, diff-available

#3104 feat(sbb-journey-summary): provide a11y footpath property
  src/elements-experimental/journey-summary/journey-summary.stories.ts
  src/elements-experimental/journey-summary/journey-summary.ts
  src/elements-experimental/journey-summary/readme.md
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available
