Repository sbb-design-systems/lyne-components, pull requests merged in 2024-02, with the labels that each got.

#2378 feat(a11y): implemented a11y tree snapshot function
  .github/workflows/continuous-integration.yml
  src/components/core/dom/platform.ts
  src/components/core/testing/a11y-tree-snapshot.ts
  src/components/selection-panel/__snapshots__/selection-panel.spec.snap.js
  src/components/selection-panel/selection-panel.spec.ts
  web-test-runner.config.js
Labels: preview-available

#2381 fix(multiple): render lists with just one element as span
  src/components/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/components/core/common-behaviors/named-slot-list-element.ts
  src/components/navigation/navigation-list/navigation-list.e2e.ts
  src/components/navigation/navigation-marker/navigation-marker.spec.ts
  src/components/skiplink-list/skiplink-list.scss
  src/components/tag/tag-group/tag-group.scss
  src/components/train/train-formation/__snapshots__/train-formation.spec.snap.js
  src/components/train/train-formation/train-formation.scss
  src/components/train/train-wagon/train-wagon.scss
  src/components/train/train-wagon/train-wagon.spec.ts
  src/components/train/train/train.spec.ts
Labels: preview-available

#2386 fix(sbb-form-field): suppress firefox outline for external framework compatibility
  src/components/form-field/form-field/form-field.scss
Labels: preview-available

#2360 refactor(selection-panel): improved open/close flow and animation
  scripts/chromatic-stories-generator.ts
  src/components/checkbox/checkbox/checkbox.ts
  src/components/notification/notification.stories.ts
  src/components/radio-button/radio-button/radio-button.ts
  src/components/selection-panel/readme.md
  src/components/selection-panel/selection-panel.e2e.ts
  src/components/selection-panel/selection-panel.scss
  src/components/selection-panel/selection-panel.stories.ts
  src/components/selection-panel/selection-panel.ts
Labels: preview-available

#2387 docs: document development process
  REVIEW.md
Labels: preview-available

#2390 feat: update journey-summary storybook title
  src/components/journey-summary/journey-summary.stories.ts
Labels: preview-available

#2271 feat(sbb-container): first implementation
  src/components/container/container/container.e2e.ts
  src/components/container/container/container.scss
  src/components/container/container/container.spec.ts
  src/components/container/container/container.stories.ts
  src/components/container/container/container.ts
  src/components/container/container/index.ts
  src/components/container/container/readme.md
  src/components/container/index.ts
  src/components/container/sticky-bar/index.ts
  src/components/container/sticky-bar/readme.md
  src/components/container/sticky-bar/sticky-bar.e2e.ts
  src/components/container/sticky-bar/sticky-bar.scss
  src/components/container/sticky-bar/sticky-bar.spec.ts
  src/components/container/sticky-bar/sticky-bar.stories.ts
  src/components/container/sticky-bar/sticky-bar.ts
  src/storybook/styles/layout/readme.md
Labels: preview-available, pr: lead review approved, pr: ux review approved

#2393 style(checkbox, radio-button): changed label disabled color
  src/components/checkbox/checkbox/checkbox.scss
  src/components/radio-button/radio-button/radio-button.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved

#2394 fix(sbb-alert): refactor animation to properly work in Safari
  src/components/alert/alert-group/alert-group.spec.ts
  src/components/alert/alert/__snapshots__/alert.spec.snap.js
  src/components/alert/alert/alert.e2e.ts
  src/components/alert/alert/alert.scss
  src/components/alert/alert/alert.spec.ts
  src/components/alert/alert/alert.stories.ts
  src/components/alert/alert/alert.ts
  src/components/alert/alert/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2399 fix(sbb-select): hide placeholder when using floating label in HCM
  src/components/form-field/form-field/form-field.scss
Labels: preview-available

#2354 fix(sbb-calendar): using keyboard navigation loses focus
  src/components/calendar/calendar.e2e.ts
  src/components/calendar/calendar.scss
  src/components/calendar/calendar.ts
  src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/components/datepicker/datepicker/datepicker.ts
Labels: preview-available, pr: peer review required

#2400 feat(sbb-clock): introduce option to configure color of seconds hand
  src/components/clock/clock.scss
Labels: preview-available

#2325 fix(sbb-notification): fix accessibility
  src/components/notification/notification.scss
  src/components/notification/notification.stories.ts
  src/components/notification/readme.md
Labels: preview-available, pr: lead review approved

#2406 fix(sbb-sticky-bar): remove unnecessary import to container
  src/components/container/sticky-bar/sticky-bar.ts
Labels: preview-available, pr: peer review required

#2408 chore: enable turbosnap
  .storybook/main.ts
  package.json
  yarn.lock
Labels: preview-available, pr: lead review required

#2409 fix(sbb-select): wait for shadow DOM readiness before setup when using nextjs
  src/components/select/select.ts
Labels: preview-available

#2417 fix(sbb-map-container): adapt width starting from ultra breakpoint
  src/components/map-container/map-container.scss
Labels: preview-available, pr: peer review required

#2413 chore: cleanup snapshot files
  src/components/autocomplete/__snapshots__/autocomplete.spec.snap.js
  src/components/calendar/__snapshots__/calendar.spec.snap.js
  src/components/checkbox/checkbox-group/__snapshots__/checkbox-group.spec.snap.js
  src/components/checkbox/checkbox/__snapshots__/checkbox.spec.snap.js
  src/components/file-selector/__snapshots__/file-selector.spec.snap.js
  src/components/icon/__snapshots__/icon.spec.snap.js
  src/components/link-list/__snapshots__/link-list.spec.snap.js
  src/components/navigation/navigation-list/__snapshots__/navigation-list.spec.snap.js
  src/components/screenreader-only/__snapshots__/screenreader-only.spec.snap.js
  src/components/skiplink-list/__snapshots__/skiplink-list.spec.snap.js
  src/components/timetable-occupancy/__snapshots__/timetable-occupancy.spec.snap.js
  src/components/tooltip/tooltip-trigger/__snapshots__/tooltip-trigger.spec.snap.js
  src/components/tooltip/tooltip/__snapshots__/tooltip.spec.snap.js
Labels: preview-available, pr: peer review approved

#2420 chore: update 'test:snapshot' command and dotReporter
  package.json
  web-test-runner.config.js
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2419 fix(sbb-container): container causes interference with overlay components
  src/components/container/container/container.scss
Labels: preview-available, pr: peer review required, pr: lead review approved

#2403 feat(sbb-status): allow custom icons
  src/components/status/__snapshots__/status.spec.snap.js
  src/components/status/readme.md
  src/components/status/status.scss
  src/components/status/status.stories.ts
  src/components/status/status.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2424 fix(sbb-pearl-chain-time): use role paragraph for accessibility reasons
  src/components/pearl-chain-time/pearl-chain-time.scss
  src/components/pearl-chain-time/pearl-chain-time.ts
Labels: preview-available, pr: peer review required

#2401 feat(sbb-image): introduce support for round variant
  src/components/image/image.scss
  src/components/image/image.stories.ts
  src/components/image/image.ts
  src/components/image/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved

#2427 fix(sbb-container): remove overflowing margin without using overflow
  src/components/container/container/container.scss
Labels: preview-available, pr: peer review required

#2428 fix(sbb-toast): fix default z-index
  src/components/toast/toast.scss
Labels: preview-available, pr: peer review required

#2414 chore(chromatic): enable turbosnap
  .github/workflows/continuous-integration.yml
Labels: preview-available, pr: peer review required, pr: lead review approved

#2433 chore(github): update 'is-pr-open' action dep from v6 => v7
  .github/workflows/continuous-integration.yml
Labels: pr: peer review required, pr: lead review approved

#2407 build(sbb-popover): stabilize chromatic tests
  src/components/popover/popover/popover.stories.ts
Labels: preview-available, pr: peer review approved

#2440 test: replace skip logic with conditional code paths
  src/components/core/testing/a11y-tree-snapshot.ts
  src/components/core/testing/mocha-extensions.ts
Labels: preview-available, pr: peer review approved

#2437 feat: implement initial support for SSR
  .nvmrc
  config/lit-ssr-worker.js
  package.json
  scripts/migrate-ssr-e2e.ts
  src/components/accordion/accordion.e2e.ts
  src/components/accordion/accordion.ts
  src/components/core/common-behaviors/action-base-element.ts
  src/components/core/common-behaviors/button-base-element.ts
  src/components/core/common-behaviors/hydration-mixin.ts
  src/components/core/common-behaviors/index.ts
  src/components/core/common-behaviors/link-base-element.ts
  src/components/core/dom/index.ts
  src/components/core/dom/platform.ts
  src/components/core/dom/ssr.ts
  src/components/core/testing/a11y-tree-snapshot.ts
  src/components/core/testing/fixture.ts
  src/components/core/testing/index.ts
  src/components/core/testing/mocha-extensions.ts
  src/components/core/testing/platform.ts
  src/components/core/testing/test-setup.ts
  src/components/core/testing/wait-for-render.ts
  src/components/expansion-panel/expansion-panel-content/expansion-panel-content.ts
  src/components/expansion-panel/expansion-panel-header/expansion-panel-header.ts
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/icon/__snapshots__/icon.spec.snap.js
  src/components/icon/icon-base.ts
  src/components/icon/icon.spec.ts
  src/components/icon/icon.ts
  src/components/vite.config.ts
  web-test-runner.config.js
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review required

#2446 fix(sbb-radio-group, sbb-tab-group): avoid incorrect setup if component is invisible during init
  src/components/radio-button/radio-button-group/radio-button-group.ts
  src/components/tabs/tab-group/tab-group.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2445 docs: extend testing documentation
  DEVELOPER.md
  package.json
Labels: preview-available, pr: peer review approved, pr: lead review approved

#2447 docs(multiple): remove undefined type from titleLevel
  src/components/accordion/accordion.ts
  src/components/accordion/readme.md
  src/components/alert/alert-group/alert-group.ts
  src/components/alert/alert-group/readme.md
  src/components/alert/alert/alert.ts
  src/components/alert/alert/readme.md
  src/components/dialog/dialog.ts
  src/components/dialog/readme.md
  src/components/expansion-panel/expansion-panel/expansion-panel.ts
  src/components/expansion-panel/expansion-panel/readme.md
  src/components/footer/footer.ts
  src/components/footer/readme.md
  src/components/journey-header/journey-header.ts
  src/components/journey-header/readme.md
  src/components/journey-summary/journey-summary.ts
  src/components/journey-summary/readme.md
  src/components/link-list/link-list.ts
  src/components/link-list/readme.md
  src/components/message/message.ts
  src/components/message/readme.md
  src/components/notification/notification.ts
  src/components/notification/readme.md
  src/components/skiplink-list/readme.md
  src/components/skiplink-list/skiplink-list.ts
  src/components/status/readme.md
  src/components/status/status.ts
  src/components/tabs/tab-title/readme.md
  src/components/tabs/tab-title/tab-title.ts
  src/components/teaser/readme.md
  src/components/teaser/teaser.ts
  src/components/title/readme.md
  src/components/title/title.ts
  src/components/train/train/readme.md
  src/components/train/train/train.ts
Labels: preview-available, pr: peer review required, pr: lead review approved

#2448 feat: increase `--sbb-font-size-title-5` for zero to small breakpoints
  .github/workflows/continuous-integration.yml
  src/components/core/styles/core/variables.scss
Labels: preview-available, pr: peer review approved, pr: ux review approved
