Repository sbb-design-systems/lyne-components, pull requests merged in 2024-11, with the labels that each got.

#3192 fix(sbb-calendar): fix month selection on wide view
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3193 fix(sbb-calendar): fix month selection on wide view (#3192)
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3188 refactor(sbb-chip-label): rename chip to chip-label
  src/elements/chip-label.ts
  src/elements/chip-label/__snapshots__/chip-label.snapshot.spec.snap.js
  src/elements/chip-label/chip-label.scss
  src/elements/chip-label/chip-label.snapshot.spec.ts
  src/elements/chip-label/chip-label.spec.ts
  src/elements/chip-label/chip-label.ssr.spec.ts
  src/elements/chip-label/chip-label.stories.ts
  src/elements/chip-label/chip-label.ts
  src/elements/chip-label/chip-label.visual.spec.ts
  src/elements/chip-label/readme.md
  src/elements/chip.ts
  src/elements/chip/__snapshots__/chip.snapshot.spec.snap.js
  src/elements/chip/chip.spec.ts
  src/elements/chip/chip.ssr.spec.ts
  src/elements/core/styles/mixins/chip.scss
  src/elements/teaser-hero/__snapshots__/teaser-hero.snapshot.spec.snap.js
  src/elements/teaser-hero/readme.md
  src/elements/teaser-hero/teaser-hero.scss
  src/elements/teaser-hero/teaser-hero.snapshot.spec.ts
  src/elements/teaser-hero/teaser-hero.spec.ts
  src/elements/teaser-hero/teaser-hero.stories.ts
  src/elements/teaser-hero/teaser-hero.ts
  src/elements/teaser-hero/teaser-hero.visual.spec.ts
  src/elements/teaser/__snapshots__/teaser.snapshot.spec.snap.js
  src/elements/teaser/readme.md
  src/elements/teaser/teaser.scss
  src/elements/teaser/teaser.ts
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
  src/visual-regression-app/src/components/test-case/test-case.scss
  src/visual-regression-app/src/components/test-case/test-case.ts
  src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.scss
  src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3201 build: update release-please config
  .github/workflows/release-please.yml
  .release-please-manifest.json
Labels: pr: peer review required, target: 1.x

#3195 fix(sbb-calendar): fix disabled month selection on wide view
  src/elements/calendar/__snapshots__/calendar.snapshot.spec.snap.js
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3204 test: use promise instead of waitForCondition for events
  src/elements-experimental/timetable-row/timetable-row.spec.ts
  src/elements/accordion/accordion.spec.ts
  src/elements/alert/alert/alert.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.spec.ts
  src/elements/breadcrumb/breadcrumb/breadcrumb.spec.ts
  src/elements/button/button-link/button-link.spec.ts
  src/elements/button/button-static/button-static.spec.ts
  src/elements/button/button/button.spec.ts
  src/elements/calendar/calendar.spec.ts
  src/elements/card/card-button/card-button.spec.ts
  src/elements/card/card-link/card-link.spec.ts
  src/elements/checkbox/common/checkbox-common.spec.ts
  src/elements/core/testing/event-spy.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/expansion-panel/expansion-panel/expansion-panel.spec.ts
  src/elements/flip-card/flip-card/flip-card.spec.ts
  src/elements/header/header-button/header-button.spec.ts
  src/elements/header/header-link/header-link.spec.ts
  src/elements/header/header/header.spec.ts
  src/elements/link/link-button/link-button.spec.ts
  src/elements/link/link-static/link-static.spec.ts
  src/elements/link/link/link.spec.ts
  src/elements/menu/menu-button/menu-button.spec.ts
  src/elements/menu/menu-link/menu-link.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation-button/navigation-button.spec.ts
  src/elements/navigation/navigation-link/navigation-link.spec.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/notification/notification.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/popover/popover-trigger/popover-trigger.spec.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.spec.ts
  src/elements/radio-button/radio-button/radio-button.spec.ts
  src/elements/select/select.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/tag/tag-group/tag-group.spec.ts
  src/elements/toast/toast.spec.ts
  src/elements/toggle-check/toggle-check.spec.ts
  src/elements/toggle/toggle-option/toggle-option.spec.ts
  src/elements/toggle/toggle/toggle.spec.ts
  src/elements/train/train-wagon/train-wagon.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3210 test: remove obsolete waitForEvent() method
  src/elements/core/testing.ts
  src/elements/core/testing/wait-for-event.ts
  src/elements/navigation/navigation/navigation.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3160 feat(sbb-radio-button, sbb-radio-button-panel): implement native form support
  src/elements/autocomplete-grid/autocomplete-grid/__snapshots__/autocomplete-grid.snapshot.spec.snap.js
  src/elements/core/mixins.ts
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/radio-button/common/radio-button-common.scss
  src/elements/radio-button/common/radio-button-common.spec.ts
  src/elements/radio-button/common/radio-button-common.ts
  src/elements/radio-button/radio-button-group/__snapshots__/radio-button-group.snapshot.spec.snap.js
  src/elements/radio-button/radio-button-group/radio-button-group.snapshot.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.stories.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/radio-button/radio-button-group/readme.md
  src/elements/radio-button/radio-button-panel/__snapshots__/radio-button-panel.snapshot.spec.snap.js
  src/elements/radio-button/radio-button-panel/radio-button-panel.snapshot.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ssr.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.stories.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ts
  src/elements/radio-button/radio-button-panel/readme.md
  src/elements/radio-button/radio-button/__snapshots__/radio-button.snapshot.spec.snap.js
  src/elements/radio-button/radio-button/radio-button.snapshot.spec.ts
  src/elements/radio-button/radio-button/radio-button.spec.ts
  src/elements/radio-button/radio-button/radio-button.ssr.spec.ts
  src/elements/radio-button/radio-button/radio-button.stories.ts
  src/elements/radio-button/radio-button/radio-button.ts
  src/elements/radio-button/radio-button/readme.md
  src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review required, pr: visual review required, diff-available

#3199 feat(sbb-train-formation): introduce new types and refactoring
  src/elements/card/card-badge/readme.md
  src/elements/core/i18n/i18n.ts
  src/elements/core/styles/core.scss
  src/elements/train/train-blocked-passage/readme.md
  src/elements/train/train-blocked-passage/train-blocked-passage.scss
  src/elements/train/train-formation/__snapshots__/train-formation.snapshot.spec.snap.js
  src/elements/train/train-formation/readme.md
  src/elements/train/train-formation/train-formation.scss
  src/elements/train/train-formation/train-formation.stories.ts
  src/elements/train/train-formation/train-formation.ts
  src/elements/train/train-formation/train-formation.visual.spec.ts
  src/elements/train/train-wagon/__snapshots__/train-wagon.snapshot.spec.snap.js
  src/elements/train/train-wagon/readme.md
  src/elements/train/train-wagon/train-wagon.scss
  src/elements/train/train-wagon/train-wagon.snapshot.spec.ts
  src/elements/train/train-wagon/train-wagon.spec.ts
  src/elements/train/train-wagon/train-wagon.stories.ts
  src/elements/train/train-wagon/train-wagon.ts
  src/elements/train/train-wagon/train-wagon.visual.spec.ts
  src/elements/train/train/__snapshots__/train.snapshot.spec.snap.js
  src/elements/train/train/readme.md
  src/elements/train/train/train.scss
  src/elements/train/train/train.spec.ts
  src/elements/train/train/train.stories.ts
  src/elements/train/train/train.ts
  src/elements/train/train/train.visual.spec.ts
  tools/web-test-runner/preload-icons.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3219 fix: cleanup deprecated core functionality
  src/elements/core/dom.ts
  src/elements/core/dom/get-document-writing-mode.ts
  src/elements/core/dom/ssr.ts
  src/elements/core/eventing.ts
  src/elements/core/eventing/form-element-handlers.ts
  src/elements/core/eventing/handler-repository.ts
  src/elements/core/mixins/disabled-mixin.ts
  src/elements/core/observers.ts
  src/elements/core/observers/intersection-observer.ts
  src/elements/core/observers/mutation-observer.ts
  src/elements/core/observers/resize-observer.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3214 fix(sbb-map-container): improve support for tablet devices
  src/elements/map-container/map-container.scss
  src/elements/map-container/map-container.visual.spec.ts
Labels: pr: peer review approved, target: 1.x

#3222 build: fix slim container image build
  .github/workflows/continuous-integration-secure.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-please.yml
Labels: target: 1.x

#3220 fix(sbb-option,sbb-autocomplete-grid-option): remove deprecated `active` property
  src/elements/option/option/option-base-element.ts
Labels: pr: peer review required, pr: lead review approved

#3221 fix(sbb-form-field): remove deprecated `getInputElement()` method
  src/elements/datepicker/common/datepicker-button.ts
  src/elements/form-field/form-field/form-field.ts
  src/elements/form-field/form-field/readme.md
Labels: pr: peer review required, pr: lead review approved

#3225 docs(sbb-card): cleanup stories and visual tests
  src/elements/card/card/card.stories.ts
  src/elements/card/card/card.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3223 refactor: remove async modifier from willUpdate
  src/elements/checkbox/checkbox-panel/checkbox-panel.ts
  src/elements/checkbox/common/checkbox-common.ts
  src/elements/clock/clock.ts
  src/elements/core/mixins/required-mixin.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/flip-card/flip-card-summary/flip-card-summary.ts
  src/elements/icon/icon.snapshot.spec.ts
  src/elements/icon/icon.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.ts
  src/elements/table/table-wrapper/table-wrapper.ts
  src/elements/toggle-check/toggle-check.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3216 fix(sbb-alert, sbb-alert-group): remove dismissal event and method
  src/elements/alert/alert-group/alert-group.spec.ts
  src/elements/alert/alert-group/alert-group.stories.ts
  src/elements/alert/alert-group/alert-group.ts
  src/elements/alert/alert-group/alert-group.visual.spec.ts
  src/elements/alert/alert-group/readme.md
  src/elements/alert/alert/alert.spec.ts
  src/elements/alert/alert/alert.stories.ts
  src/elements/alert/alert/alert.ts
  src/elements/alert/alert/readme.md
  src/elements/notification/notification.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available

#3228 refactor: remove dvh/dvw backwards compatibility
  src/elements/menu/menu/menu.scss
  src/elements/navigation/navigation-section/navigation-section.scss
  src/elements/navigation/navigation/navigation.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3226 fix: fix width breakpoints of SbbMediaMatcherController
  src/elements/calendar/calendar.ts
  src/elements/core/controllers/media-matchers-controller.ts
  src/elements/core/dom/breakpoint.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/image/image.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/navigation-section/navigation-section.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 1.x

#2244 fix(sbb-time-input): create get/set for valueAsDate
  src/elements/time-input/readme.md
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.stories.ts
  src/elements/time-input/time-input.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: major

#3229 fix(sbb-select): improve connected label handling
  src/elements/paginator/paginator/__snapshots__/paginator.snapshot.spec.snap.js
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/paginator/paginator/paginator.ts
  src/elements/paginator/paginator/readme.md
  src/elements/select/readme.md
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3198 feat(sbb-file-selector): split file-selector variants in separate components
  src/elements/button/common/common-stories.ts
  src/elements/file-selector.ts
  src/elements/file-selector/common.ts
  src/elements/file-selector/common/file-selector-common-stories.ts
  src/elements/file-selector/common/file-selector-common.scss
  src/elements/file-selector/common/file-selector-common.spec.ts
  src/elements/file-selector/common/file-selector-common.ts
  src/elements/file-selector/file-selector-dropzone.ts
  src/elements/file-selector/file-selector-dropzone/__snapshots__/file-selector-dropzone.snapshot.spec.snap.js
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.scss
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.snapshot.spec.ts
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.spec.ts
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.ssr.spec.ts
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.stories.ts
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.ts
  src/elements/file-selector/file-selector-dropzone/file-selector-dropzone.visual.spec.ts
  src/elements/file-selector/file-selector-dropzone/readme.md
  src/elements/file-selector/file-selector.spec.ts
  src/elements/file-selector/file-selector.stories.ts
  src/elements/file-selector/file-selector.ts
  src/elements/file-selector/file-selector/__snapshots__/file-selector.snapshot.spec.snap.js
  src/elements/file-selector/file-selector/file-selector.snapshot.spec.ts
  src/elements/file-selector/file-selector/file-selector.spec.ts
  src/elements/file-selector/file-selector/file-selector.ssr.spec.ts
  src/elements/file-selector/file-selector/file-selector.stories.ts
  src/elements/file-selector/file-selector/file-selector.ts
  src/elements/file-selector/file-selector/file-selector.visual.spec.ts
  src/elements/file-selector/file-selector/readme.md
  src/elements/link/common/link-common-stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3237 build: update codeql action from v2 to v3
  .github/workflows/codeql-analysis.yml
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3241 test(sbb-menu): fix flickering menu test on webkit
  src/elements/menu/menu/menu.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 1.x

#3242 fix: fix type of form associated controls
  src/elements/checkbox/checkbox-panel/readme.md
  src/elements/checkbox/checkbox/readme.md
  src/elements/checkbox/common/checkbox-common.spec.ts
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/file-selector/common/file-selector-common.spec.ts
  src/elements/file-selector/common/file-selector-common.ts
  src/elements/file-selector/file-selector-dropzone/readme.md
  src/elements/file-selector/file-selector/readme.md
  src/elements/radio-button/common/radio-button-common.spec.ts
  src/elements/radio-button/radio-button-panel/readme.md
  src/elements/radio-button/radio-button/readme.md
  src/elements/select/readme.md
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
  src/elements/slider/readme.md
  src/elements/slider/slider.spec.ts
  src/elements/slider/slider.ts
  src/elements/toggle-check/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3243 fix(sbb-autocomplete, sbb-autocomplete-grid): avoid form submission on enter press
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 1.x

#3245 chore(deps): update dependency prettier to v3.4.0 (1.x)
  package.json
  src/elements/container/sticky-bar/sticky-bar.scss
  src/elements/core/styles/core/mediaqueries.scss
  src/elements/core/styles/mixins/buttons.scss
  src/elements/form-field/form-field/form-field.scss
  src/elements/notification/notification.scss
  src/elements/popover/popover-trigger/popover-trigger.scss
  src/elements/status/status.scss
  yarn.lock
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3253 fix: remove deprecated `didChange` events where possible
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/checkbox/checkbox-panel/checkbox-panel.ts
  src/elements/checkbox/checkbox-panel/readme.md
  src/elements/checkbox/checkbox/checkbox.ts
  src/elements/checkbox/checkbox/readme.md
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/datepicker/datepicker/readme.md
  src/elements/form-field/form-field/form-field.ts
  src/elements/select/readme.md
  src/elements/select/select.ts
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.ts
  src/elements/toggle-check/readme.md
  src/elements/toggle-check/toggle-check.ts
  src/elements/toggle/toggle/readme.md
  src/elements/toggle/toggle/toggle.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3230 refactor(sbb-header): removed 'logo' slot
  .storybook/preview-head.html
  src/elements/header/header/__snapshots__/header.snapshot.spec.snap.js
  src/elements/header/header/header.scss
  src/elements/header/header/header.snapshot.spec.ts
  src/elements/header/header/header.stories.ts
  src/elements/header/header/header.ts
  src/elements/header/header/header.visual.spec.ts
  src/elements/header/header/readme.md
  src/elements/map-container/map-container.stories.ts
  src/elements/map-container/map-container.visual.spec.ts
  src/storybook/pages/home/home--logged-in.stories.ts
  src/storybook/pages/home/home.stories.ts
  src/visual-regression-app/src/components/test-case/test-case.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3254 fix(sbb-flip-card): fix card summary image position
  src/elements/flip-card/flip-card-details/flip-card-details.scss
  src/elements/flip-card/flip-card-details/flip-card-details.visual.spec.ts
  src/elements/flip-card/flip-card-summary/flip-card-summary.scss
  src/elements/flip-card/flip-card/flip-card.scss
  src/elements/flip-card/flip-card/flip-card.stories.ts
  src/elements/flip-card/flip-card/flip-card.ts
  src/elements/flip-card/flip-card/flip-card.visual.spec.ts
  src/elements/flip-card/flip-card/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 1.x
