Repository sbb-design-systems/lyne-components, pull requests merged in 2025-09, with the labels that each got.

#4009 fix(sbb-notification): fix error color
  src/elements/notification/notification.scss
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 3.x

#4012 docs: improve documentation of sbb-title-base derived components
  src/elements/dialog/dialog-title/readme.md
  src/elements/journey-header/readme.md
  src/elements/sidebar/sidebar-title/readme.md
  src/elements/title/title-base.ts
  src/elements/title/title.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4015 feat(seat reservation): distinguishing active/focus-visited state for place selection
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 3.x

#4013 feat(sbb-timetable-form): component implementation
  docs/GETTING_STARTED.md
  src/elements/core/i18n/i18n.ts
  src/elements/core/styles/core.scss
  src/elements/core/styles/mixins/timetable-form.scss
  src/elements/core/styles/standard-theme.scss
  src/elements/core/styles/timetable-form.scss
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/form-field/form-field/form-field.scss
  src/elements/form-field/form-field/readme.md
  src/elements/timetable-form.ts
  src/elements/timetable-form/timetable-form-details.ts
  src/elements/timetable-form/timetable-form-details/readme.md
  src/elements/timetable-form/timetable-form-details/timetable-form-details.component.ts
  src/elements/timetable-form/timetable-form-details/timetable-form-details.scss
  src/elements/timetable-form/timetable-form-details/timetable-form-details.spec.ts
  src/elements/timetable-form/timetable-form-details/timetable-form-details.ssr.spec.ts
  src/elements/timetable-form/timetable-form-details/timetable-form-details.stories.ts
  src/elements/timetable-form/timetable-form-field.ts
  src/elements/timetable-form/timetable-form-field/__snapshots__/timetable-form-field.snapshot.spec.snap.js
  src/elements/timetable-form/timetable-form-field/readme.md
  src/elements/timetable-form/timetable-form-field/timetable-form-field.component.ts
  src/elements/timetable-form/timetable-form-field/timetable-form-field.scss
  src/elements/timetable-form/timetable-form-field/timetable-form-field.snapshot.spec.ts
  src/elements/timetable-form/timetable-form-field/timetable-form-field.spec.ts
  src/elements/timetable-form/timetable-form-field/timetable-form-field.ssr.spec.ts
  src/elements/timetable-form/timetable-form-field/timetable-form-field.stories.ts
  src/elements/timetable-form/timetable-form-swap-button.ts
  src/elements/timetable-form/timetable-form-swap-button/__snapshots__/timetable-form-swap-button.snapshot.spec.snap.js
  src/elements/timetable-form/timetable-form-swap-button/readme.md
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.component.ts
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.scss
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.snapshot.spec.ts
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.spec.ts
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.ssr.spec.ts
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.stories.ts
  src/elements/timetable-form/timetable-form-swap-button/timetable-form-swap-button.visual.spec.ts
  src/elements/timetable-form/timetable-form.ts
  src/elements/timetable-form/timetable-form/__snapshots__/timetable-form.snapshot.spec.snap.js
  src/elements/timetable-form/timetable-form/readme.md
  src/elements/timetable-form/timetable-form/timetable-form.component.ts
  src/elements/timetable-form/timetable-form/timetable-form.scss
  src/elements/timetable-form/timetable-form/timetable-form.snapshot.spec.ts
  src/elements/timetable-form/timetable-form/timetable-form.spec.ts
  src/elements/timetable-form/timetable-form/timetable-form.ssr.spec.ts
  src/elements/timetable-form/timetable-form/timetable-form.stories.ts
  src/elements/timetable-form/timetable-form/timetable-form.visual.spec.ts
  src/elements/vite.config.ts
  tools/vite/typography.ts
  tools/web-test-runner/preload-icons.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required, pr: visual review required, diff-available, target: 3.x

#4018 feat(sbb-autocomplete, sbb-autocomplete-grid): add requireSelection and autoSelectActiveOption
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/autocomplete/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3926 feat(sbb-carousel): add carousel component
  src/elements/carousel.ts
  src/elements/carousel/carousel-item.ts
  src/elements/carousel/carousel-item/__snapshots__/carousel-item.snapshot.spec.snap.js
  src/elements/carousel/carousel-item/carousel-item.component.ts
  src/elements/carousel/carousel-item/carousel-item.scss
  src/elements/carousel/carousel-item/carousel-item.snapshot.spec.ts
  src/elements/carousel/carousel-item/carousel-item.spec.ts
  src/elements/carousel/carousel-item/carousel-item.ssr.spec.ts
  src/elements/carousel/carousel-item/carousel-item.stories.ts
  src/elements/carousel/carousel-item/carousel-item.visual.spec.ts
  src/elements/carousel/carousel-item/readme.md
  src/elements/carousel/carousel-list.ts
  src/elements/carousel/carousel-list/__snapshots__/carousel-list.snapshot.spec.snap.js
  src/elements/carousel/carousel-list/carousel-list.component.ts
  src/elements/carousel/carousel-list/carousel-list.scss
  src/elements/carousel/carousel-list/carousel-list.snapshot.spec.ts
  src/elements/carousel/carousel-list/carousel-list.spec.ts
  src/elements/carousel/carousel-list/carousel-list.ssr.spec.ts
  src/elements/carousel/carousel-list/carousel-list.stories.ts
  src/elements/carousel/carousel-list/carousel-list.visual.spec.ts
  src/elements/carousel/carousel-list/readme.md
  src/elements/carousel/carousel.ts
  src/elements/carousel/carousel/__snapshots__/carousel.snapshot.spec.snap.js
  src/elements/carousel/carousel/carousel.component.ts
  src/elements/carousel/carousel/carousel.scss
  src/elements/carousel/carousel/carousel.snapshot.spec.ts
  src/elements/carousel/carousel/carousel.spec.ts
  src/elements/carousel/carousel/carousel.ssr.spec.ts
  src/elements/carousel/carousel/carousel.stories.ts
  src/elements/carousel/carousel/carousel.visual.spec.ts
  src/elements/carousel/carousel/readme.md
  src/elements/core/i18n/i18n.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, target: 3.x

#4029 chore: adapt image urls to new path
  src/elements/container/container/readme.md
  src/elements/core/images.ts
  src/elements/flip-card/flip-card-summary/readme.md
  src/elements/lead-container/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4036 test(sbb-carousel): stabilize visual regression tests
  src/elements/carousel/carousel/carousel.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4035 feat(sbb-dialog): expose CSS part of scroll-container
  src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
  src/elements/dialog/dialog/dialog.component.ts
  src/elements/dialog/dialog/readme.md
  tools/docs/docs_generate.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 3.x

#4041 feat(sbb-seat-reservation): add hover-trigger to popovers
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4044 fix(sbb-form-field): fix text color for suffix slot
  src/elements/form-field/form-field/form-field.scss
  src/elements/select/select.scss
Labels: preview-available, pr: peer review required, pr: ux review approved, pr: visual review required, diff-available, target: 3.x

#4050 chore: adapt timetable form red for off-brand theme
  src/elements/core/styles/mixins/timetable-form.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4054 feat(seat-reservation): navigation preload and squash icons
  src/elements-experimental/seat-reservation/common/types.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4058 fix(sbb-toast): check for zone.js in close timeout
  src/elements/toast/toast.component.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x
