Repository sbb-design-systems/lyne-components, pull requests merged in 2025-07, with the labels that each got.

#3869 feat/thm/seat-reservation-documentation
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/common/types.ts
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3875 fix: fix event types
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements/accordion/accordion.component.ts
  src/elements/alert/alert/alert.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/button/button-link/button-link.spec.ts
  src/elements/button/button-static/button-static.spec.ts
  src/elements/button/button/button.spec.ts
  src/elements/calendar/calendar.component.ts
  src/elements/checkbox/checkbox-panel/checkbox-panel.component.ts
  src/elements/chip/chip-group/chip-group.component.ts
  src/elements/chip/chip-group/chip-group.spec.ts
  src/elements/container/sticky-bar/sticky-bar.spec.ts
  src/elements/core/base-elements/open-close-base-element.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/file-selector/common/file-selector-common.ts
  src/elements/link/link-button/link-button.spec.ts
  src/elements/link/link-static/link-static.spec.ts
  src/elements/link/link/link.spec.ts
  src/elements/menu/menu-button/menu-button.spec.ts
  src/elements/menu/menu-link/menu-link.spec.ts
  src/elements/option/option/option-base-element.ts
  src/elements/option/option/option.component.ts
  src/elements/option/option/option.spec.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/overlay/overlay.stories.ts
  src/elements/paginator/paginator/paginator.component.ts
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.component.ts
  src/elements/select/select.component.ts
  src/elements/select/select.spec.ts
  src/elements/sidebar/icon-sidebar/icon-sidebar.stories.ts
  src/elements/sidebar/sidebar/sidebar.stories.ts
  src/elements/stepper/step/step.component.ts
  src/elements/stepper/stepper/stepper.component.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 3.x

#3889 fix: add string to property types in the react wrapper
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3890 perf(sbb-datepicker): delay rendering of calendar
  src/elements/datepicker/datepicker/datepicker.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3894 fix(seat-reservation): fix folder structure
  src/elements-experimental/seat-reservation.ts
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/__snapshots__/seat-reservation-navigation-coach.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ssr.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/__snapshots__/seat-reservation-navigation-services.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.ssr.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x, target: 3.x

#3876 feat(seat-reservation-button-navigation): add autoscroll right/left n…
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3884 feat/thm/rtl
  src/elements-experimental/seat-reservation/common/styles/seat-reservation-mixins.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3898 Saet reservation button navigation
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required

#3905 feat(sbb-popover): add global configurations for delays
  src/elements/core/config/config.ts
  src/elements/popover/popover/popover.component.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/popover/popover/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3802 refactor(sbb-menu, sbb-menu-button, sbb-menu-link): assigned specific role
  src/elements/core/base-elements/link-base-element.ts
  src/elements/menu/menu-button/__snapshots__/menu-button.snapshot.spec.snap.js
  src/elements/menu/menu-button/menu-button.component.ts
  src/elements/menu/menu-link/__snapshots__/menu-link.snapshot.spec.snap.js
  src/elements/menu/menu-link/menu-link.component.ts
  src/elements/menu/menu/__snapshots__/menu.snapshot.spec.snap.js
  src/elements/menu/menu/menu.component.ts
  src/elements/menu/menu/menu.snapshot.spec.ts
  src/elements/menu/menu/menu.stories.ts
  src/elements/menu/menu/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: a11y review approved, pr: visual review required, diff-available, target: 3.x

#3906 feat(sbb-form-field): add support for custom controls
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/form-field/form-field/form-field.spec.ts
  src/elements/form-field/form-field/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3913 feat(sbb-expansion-panel-header): add CSS variable for justify-content
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x

#3920 Seat reservation give out free places by type
  src/elements-experimental/seat-reservation/common/mapper/mapper.ts
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/common/types.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required

#3614 feat(sbb-calendar): multiple selection and week number
  src/elements/calendar/__snapshots__/calendar.snapshot.spec.snap.js
  src/elements/calendar/calendar.component.ts
  src/elements/calendar/calendar.scss
  src/elements/calendar/calendar.snapshot.spec.ts
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.ssr.spec.ts
  src/elements/calendar/calendar.stories.ts
  src/elements/calendar/calendar.visual.spec.ts
  src/elements/calendar/readme.md
  src/elements/core/i18n/i18n.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ssr.spec.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/datepicker.ssr.spec.ts
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3928 feat(seat-reservation-multiple-coach-decks): implement handling to render multiple coach decks
  src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
  src/elements-experimental/seat-reservation/common/mapper/mapper.ts
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/common/types.ts
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x
