Repository sbb-design-systems/lyne-components, pull requests merged in 2025-08, with the labels that each got.

#3935 refactor(seat-reservation): optimize rem size calculation
  src/elements-experimental/seat-reservation/common/styles/seat-reservation-functions.scss
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3943 fix(sbb-autocomplete): update active option if autoActiveFirstOption is enabled and options change
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/option/option/option-base-element.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x

#3945 feat(seat-reservation-comp-use-stylemap): reduce comp props and use stylemap
  src/elements-experimental/seat-reservation/seat-reservation-area/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-graphic/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/__snapshots__/seat-reservation-navigation-services.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3955 fix(sbb-autocomplete, sbb-autocomplete-grid): only opening on lazy options if count was 0
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x

#3956 fix(sbb-date-input, sbb-time-input): handle empty state and floating label
  src/elements/date-input/date-input.component.ts
  src/elements/date-input/date-input.spec.ts
  src/elements/date-input/readme.md
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/form-field/form-field/readme.md
  src/elements/time-input/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x

#3958 fix: fix disabled state handling
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/date-input/date-input.spec.ts
  src/elements/time-input/time-input.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 3.x

#3978 fix: element internals polyfill
  src/elements/core/mixins/element-internals-mixin.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#3987 feat(seat-reservation-v5): optimize input props + modify vertical mode
  src/elements-experimental/seat-reservation/seat-reservation-area/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-graphic/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/__snapshots__/seat-reservation-navigation-services.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3995 docs: add release documentation
  docs/CONTRIBUTING.md
  docs/RELEASE.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x
