Repository sbb-design-systems/lyne-components, pull requests merged in 2025-02, with the labels that each got.

#3384 fix: provide `accessibility-current` property for link elements
  src/elements/breadcrumb/breadcrumb-group/__snapshots__/breadcrumb-group.snapshot.spec.snap.js
  src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.ts
  src/elements/breadcrumb/breadcrumb-group/readme.md
  src/elements/breadcrumb/breadcrumb/readme.md
  src/elements/button/accent-button-link/readme.md
  src/elements/button/button-link/readme.md
  src/elements/button/secondary-button-link/readme.md
  src/elements/button/transparent-button-link/readme.md
  src/elements/card/card-link/readme.md
  src/elements/core/base-elements/link-base-element.spec.ts
  src/elements/core/base-elements/link-base-element.ts
  src/elements/header/header-link/readme.md
  src/elements/header/header/header.stories.ts
  src/elements/header/header/readme.md
  src/elements/link/block-link/readme.md
  src/elements/link/link/readme.md
  src/elements/menu/menu-link/readme.md
  src/elements/navigation/navigation-link/readme.md
  src/elements/navigation/navigation-section/readme.md
  src/elements/navigation/navigation/readme.md
  src/elements/teaser-hero/readme.md
  src/elements/teaser-product/teaser-product/readme.md
  src/elements/teaser/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3386 fix(sbb-datepicker-toggle): fix popover style
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3388 chore: fix pull request template typo
  .github/pull_request_template.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3389 chore: remove puppeteer dependency
  package.json
  src/elements/core/testing/private/a11y-tree-snapshot.ts
  web-test-runner.config.ts
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3383 build: fix eslint describe title rule
  eslint.config.js
  src/elements-experimental/pearl-chain-vertical-item/pearl-chain-vertical-item.spec.ts
  src/elements-experimental/pearl-chain-vertical/pearl-chain-vertical.spec.ts
  src/elements/checkbox/checkbox/checkbox.spec.ts
  src/elements/checkbox/common/checkbox-common.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/file-selector/common/file-selector-common.spec.ts
  src/elements/file-selector/file-selector/file-selector.spec.ts
  src/elements/icon/icon-validate.spec.ts
  src/elements/radio-button/common/radio-button-common.spec.ts
  src/elements/radio-button/radio-button-panel/radio-button-panel.spec.ts
  tools/eslint/test-describe-title-rule.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3397 build: fix build for Windows
  package.json
  src/elements-experimental/vite.config.ts
  src/elements/vite.config.ts
  src/react-experimental/vite.config.ts
  src/react/vite.config.ts
  src/visual-regression-app/vite.config.ts
  tools/node-esm-hook/raw-hook.js
  tools/vite/copy-assets.ts
  tools/vite/custom-elements-manifest.ts
  tools/vite/typography.ts
  tools/vite/verify-entry-points.ts
  yarn.lock
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3399 docs: added warning about necessary import in type-script file
  docs/GETTING_STARTED.md
Labels: pr: peer review required, target: 2.x

#3394 fix(buttons): avoid moving surrounding context on hover
  src/elements/button/button/button.visual.spec.ts
  src/elements/button/common/button-common.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3312 feat: include updated SBB fonts
  .storybook/preview-head.html
  src/elements/core/styles/mixins/font-face.scss
  src/visual-regression-app/index.html
  tools/web-test-runner/preload-fonts.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3411 chore: minor fixes on stories
  src/elements-experimental/journey-summary/journey-summary.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/card/card/card.stories.ts
  src/elements/checkbox/checkbox-group/checkbox-group.stories.ts
  src/elements/chip-label/chip-label.stories.ts
  src/elements/clock/clock.stories.ts
  src/elements/container/sticky-bar/sticky-bar.stories.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.stories.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.stories.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.stories.ts
  src/elements/datepicker/datepicker/datepicker.stories.ts
  src/elements/dialog/dialog-actions/dialog-actions.stories.ts
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/divider/divider.stories.ts
  src/elements/flip-card/flip-card-summary/flip-card-summary.stories.ts
  src/elements/flip-card/flip-card/flip-card.stories.ts
  src/elements/footer/footer.stories.ts
  src/elements/form-error/form-error.stories.ts
  src/elements/form-field/form-field/form-field.stories.ts
  src/elements/logo/logo.stories.ts
  src/elements/map-container/map-container.stories.ts
  src/elements/menu/menu-button/menu-button.stories.ts
  src/elements/menu/menu-link/menu-link.stories.ts
  src/elements/message/message.stories.ts
  src/elements/option/optgroup/optgroup.stories.ts
  src/elements/select/select.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3412 build: fix podman usage for local container tests
  vite.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3404 feat: implement native validation for form elements
  docs/GETTING_STARTED.md
  src/elements/button/accent-button/readme.md
  src/elements/button/button/readme.md
  src/elements/button/mini-button/readme.md
  src/elements/button/secondary-button/readme.md
  src/elements/button/transparent-button/readme.md
  src/elements/card/card-button/readme.md
  src/elements/checkbox/checkbox-panel/readme.md
  src/elements/checkbox/checkbox/readme.md
  src/elements/checkbox/common/checkbox-common.spec.ts
  src/elements/core/i18n/i18n.ts
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/expansion-panel/expansion-panel-header/readme.md
  src/elements/file-selector/file-selector-dropzone/readme.md
  src/elements/file-selector/file-selector/readme.md
  src/elements/form-field/form-field-clear/readme.md
  src/elements/form-field/form-field/form-field.ts
  src/elements/header/header-button/readme.md
  src/elements/link/block-link-button/readme.md
  src/elements/link/link-button/readme.md
  src/elements/menu/menu-button/readme.md
  src/elements/navigation/navigation-button/readme.md
  src/elements/popover/popover-trigger/readme.md
  src/elements/radio-button/common/radio-button-common.spec.ts
  src/elements/radio-button/radio-button-panel/__snapshots__/radio-button-panel.snapshot.spec.snap.js
  src/elements/radio-button/radio-button-panel/readme.md
  src/elements/radio-button/radio-button/__snapshots__/radio-button.snapshot.spec.snap.js
  src/elements/radio-button/radio-button/readme.md
  src/elements/select/readme.md
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
  src/elements/slider/readme.md
  src/elements/stepper/step-label/readme.md
  src/elements/tag/tag/readme.md
  src/elements/toggle-check/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#2639 feat(sbb-badge): provide badge styling via attribute
  docs/GETTING_STARTED.md
  src/elements/core/styles/badge.scss
  src/elements/core/styles/mixins/badge.scss
  src/elements/core/styles/standard-theme.scss
  src/elements/menu/common/menu-action-common.ts
  src/elements/menu/common/menu-action.scss
  src/elements/menu/menu-button/__snapshots__/menu-button.snapshot.spec.snap.js
  src/elements/menu/menu-button/menu-button.snapshot.spec.ts
  src/elements/menu/menu-button/menu-button.stories.ts
  src/elements/menu/menu-button/menu-button.visual.spec.ts
  src/elements/menu/menu-button/readme.md
  src/elements/menu/menu-link/__snapshots__/menu-link.snapshot.spec.snap.js
  src/elements/menu/menu-link/menu-link.snapshot.spec.ts
  src/elements/menu/menu-link/menu-link.stories.ts
  src/elements/menu/menu-link/menu-link.visual.spec.ts
  src/elements/menu/menu-link/readme.md
  src/elements/menu/menu/__snapshots__/menu.snapshot.spec.snap.js
  src/elements/menu/menu/menu.snapshot.spec.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/menu/menu/menu.ssr.spec.ts
  src/elements/menu/menu/menu.stories.ts
  src/elements/menu/menu/menu.visual.spec.ts
  src/elements/menu/menu/readme.md
  src/elements/vite.config.ts
  src/storybook/styles/badge/badge.stories.ts
  src/storybook/styles/badge/badge.visual.spec.ts
  src/storybook/styles/badge/readme.md
  tools/vite/typography.ts
  tsconfig.json
Labels: preview-available, ux approved, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3409 feat(sbb-toggle): implement form association
  src/elements/toggle/toggle-option/readme.md
  src/elements/toggle/toggle-option/toggle-option.ts
  src/elements/toggle/toggle/readme.md
  src/elements/toggle/toggle/toggle.scss
  src/elements/toggle/toggle/toggle.spec.ts
  src/elements/toggle/toggle/toggle.ts
  src/elements/toggle/toggle/toggle.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3408 feat: visually improve link underline styles
  src/elements/core/styles/mixins/link.scss
Labels: preview-available, ux approved, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3423 fix(panels): reflect colors
  src/elements/accordion/__snapshots__/accordion.snapshot.spec.snap.js
  src/elements/checkbox/checkbox-panel/__snapshots__/checkbox-panel.snapshot.spec.snap.js
  src/elements/core/mixins/panel-mixin.ts
  src/elements/expansion-panel/expansion-panel/__snapshots__/expansion-panel.snapshot.spec.snap.js
  src/elements/expansion-panel/expansion-panel/expansion-panel.ts
  src/elements/radio-button/radio-button-panel/__snapshots__/radio-button-panel.snapshot.spec.snap.js
  src/elements/selection-expansion-panel/__snapshots__/selection-expansion-panel.snapshot.spec.snap.js
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3422 fix: regex for generic type substitution
  src/elements/button/accent-button/readme.md
  src/elements/button/button/readme.md
  src/elements/button/mini-button/readme.md
  src/elements/button/secondary-button/readme.md
  src/elements/button/transparent-button/readme.md
  src/elements/card/card-button/readme.md
  src/elements/checkbox/checkbox-panel/readme.md
  src/elements/checkbox/checkbox/readme.md
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/expansion-panel/expansion-panel-header/readme.md
  src/elements/file-selector/file-selector-dropzone/readme.md
  src/elements/file-selector/file-selector/readme.md
  src/elements/form-field/form-field-clear/readme.md
  src/elements/header/header-button/readme.md
  src/elements/link/block-link-button/readme.md
  src/elements/link/link-button/readme.md
  src/elements/menu/menu-button/readme.md
  src/elements/navigation/navigation-button/readme.md
  src/elements/popover/popover-trigger/readme.md
  src/elements/radio-button/radio-button-panel/readme.md
  src/elements/radio-button/radio-button/readme.md
  src/elements/select/readme.md
  src/elements/slider/readme.md
  src/elements/stepper/step-label/readme.md
  src/elements/tag/tag/readme.md
  src/elements/toggle-check/readme.md
  src/elements/toggle/toggle/readme.md
  tools/manifest/custom-elements-manifest.config.js
Labels: pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3379 feat(sbb-tag, sbb-tag-group): implement native form support
  src/elements/tag/tag-group/readme.md
  src/elements/tag/tag-group/tag-group.spec.ts
  src/elements/tag/tag-group/tag-group.stories.ts
  src/elements/tag/tag-group/tag-group.ts
  src/elements/tag/tag-group/tag-group.visual.spec.ts
  src/elements/tag/tag/__snapshots__/tag.snapshot.spec.snap.js
  src/elements/tag/tag/tag.scss
  src/elements/tag/tag/tag.spec.ts
  src/elements/tag/tag/tag.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3425 chore: fix template lean story
  src/storybook/pages/lean/lean.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x
