Repository sbb-design-systems/lyne-components, pull requests merged in 2025-04, with the labels that each got.

#3511 refactor: avoid `new` expression without assignment
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.ts
  src/elements/dialog/dialog-title/dialog-title.ts
  src/elements/flip-card/flip-card-details/flip-card-details.ts
  src/elements/header/header/header.ts
  src/elements/navigation/navigation-marker/navigation-marker.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/option/optgroup/optgroup-base-element.ts
  src/elements/option/option/option-base-element.ts
  src/elements/select/select.ts
  src/elements/sidebar/sidebar/sidebar.ts
  tools/eslint/index.ts
  tools/eslint/no-new-expression-without-assignment-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3512 refactor: replace initialized with hasUpdated
  src/elements/expansion-panel/expansion-panel/expansion-panel.ts
  src/elements/selection-expansion-panel/selection-expansion-panel.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3514 fix: avoid throwing on parsing invalid date
  src/elements/core/datetime/native-date-adapter.spec.ts
  src/elements/core/datetime/native-date-adapter.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3516 test: use inlined font-face for testing
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3382 feat(sbb-chip-group): initial implementation
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.visual.spec.ts
  src/elements/chip-group.ts
  src/elements/chip-group/chip-group.ts
  src/elements/chip-group/chip-group/__snapshots__/chip-group.snapshot.spec.snap.js
  src/elements/chip-group/chip-group/chip-group.scss
  src/elements/chip-group/chip-group/chip-group.snapshot.spec.ts
  src/elements/chip-group/chip-group/chip-group.spec.ts
  src/elements/chip-group/chip-group/chip-group.ssr.spec.ts
  src/elements/chip-group/chip-group/chip-group.stories.ts
  src/elements/chip-group/chip-group/chip-group.ts
  src/elements/chip-group/chip-group/chip-group.visual.spec.ts
  src/elements/chip-group/chip-group/readme.md
  src/elements/chip-group/chip.ts
  src/elements/chip-group/chip/__snapshots__/chip.snapshot.spec.snap.js
  src/elements/chip-group/chip/chip.scss
  src/elements/chip-group/chip/chip.snapshot.spec.ts
  src/elements/chip-group/chip/chip.spec.ts
  src/elements/chip-group/chip/chip.ssr.spec.ts
  src/elements/chip-group/chip/chip.stories.ts
  src/elements/chip-group/chip/chip.ts
  src/elements/chip-group/chip/chip.visual.spec.ts
  src/elements/chip-group/chip/readme.md
  src/elements/core/i18n/i18n.ts
  src/elements/core/styles/core.scss
  src/elements/form-field/form-field/form-field.scss
  src/elements/form-field/form-field/form-field.ts
  src/elements/paginator/paginator/paginator.scss
  tools/web-test-runner/preload-icons.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: a11y review required, pr: visual review required, diff-available, target: 2.x

#3528 fix(sbb-clock): handle 'visibilityChange' when paused
  src/elements/clock/clock.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3529 fix(sbb-menu): fix positioning for a Webkit edge case
  src/elements/core/controllers/media-matchers-controller.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3531 test: fix waiting for images on Safari
  src/elements/core/testing/wait-for-image-ready.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3532 test(sbb-icon-sidebar): stabilize waiting for opening
  src/elements/sidebar/icon-sidebar/icon-sidebar.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3523 fix: support img in sbb-figure context
  src/elements/core/styles/core.scss
  src/elements/core/styles/image.scss
  src/elements/image/readme.md
  src/elements/teaser-hero/readme.md
  src/elements/teaser-hero/teaser-hero.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3505 fix: synchronize id references
  src/elements/autocomplete-grid/autocomplete-grid-optgroup/autocomplete-grid-optgroup.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/readme.md
  src/elements/core/controllers.ts
  src/elements/core/controllers/escapable-overlay-controller.spec.ts
  src/elements/core/controllers/id-observer-controller.spec.ts
  src/elements/core/controllers/id-observer-controller.ts
  src/elements/core/dom/find-referenced-element.ts
  src/elements/core/dom/input-element.ts
  src/elements/core/overlay/overlay-trigger-attributes.ts
  src/elements/core/overlay/position.ts
  src/elements/core/testing/scroll.ts
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/header/header/header.spec.ts
  src/elements/header/header/header.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/navigation-section/navigation-section.spec.ts
  src/elements/navigation/navigation-section/navigation-section.ts
  src/elements/navigation/navigation-section/readme.md
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/option/optgroup/optgroup.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/popover/popover/popover.ts
  src/elements/select/select.ts
  src/elements/sidebar/sidebar/sidebar.spec.ts
  src/elements/stepper/step-label/step-label.ts
  src/elements/stepper/step/step.ts
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3533 refactor(sbb-chip-group): adapt module name from chip-group to chip
  src/elements/chip-group.ts
  src/elements/chip.ts
  src/elements/chip/chip-group.ts
  src/elements/chip/chip-group/__snapshots__/chip-group.snapshot.spec.snap.js
  src/elements/chip/chip-group/chip-group.scss
  src/elements/chip/chip-group/chip-group.snapshot.spec.ts
  src/elements/chip/chip-group/chip-group.spec.ts
  src/elements/chip/chip-group/chip-group.ssr.spec.ts
  src/elements/chip/chip-group/chip-group.stories.ts
  src/elements/chip/chip-group/chip-group.ts
  src/elements/chip/chip-group/chip-group.visual.spec.ts
  src/elements/chip/chip-group/readme.md
  src/elements/chip/chip.ts
  src/elements/chip/chip/__snapshots__/chip.snapshot.spec.snap.js
  src/elements/chip/chip/chip.scss
  src/elements/chip/chip/chip.snapshot.spec.ts
  src/elements/chip/chip/chip.spec.ts
  src/elements/chip/chip/chip.ssr.spec.ts
  src/elements/chip/chip/chip.stories.ts
  src/elements/chip/chip/chip.ts
  src/elements/chip/chip/chip.visual.spec.ts
  src/elements/chip/chip/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3521 fix(sbb-timetable-row): fix count of transfer procedures
  src/elements-experimental/pearl-chain/pearl-chain.sample-data.ts
  src/elements-experimental/timetable-row/__snapshots__/timetable-row.snapshot.spec.snap.js
  src/elements-experimental/timetable-row/timetable-row.sample-data.ts
  src/elements-experimental/timetable-row/timetable-row.snapshot.spec.ts
  src/elements-experimental/timetable-row/timetable-row.ts
  src/elements/core/i18n/i18n.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3534 docs: minor fixes on stories
  src/elements/button/common/button-link-common-stories.ts
  src/elements/calendar/calendar.stories.ts
  src/elements/card/card/card.stories.ts
  src/elements/link/common/link-common-stories.ts
  src/elements/time-input/time-input.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3537 build: add lint rule for only using relative imports inside package
  eslint.config.js
  scripts/calculate-stats.ts
  scripts/migrate-ssr-e2e.ts
  scripts/migrate-ssr.ts
  scripts/migrate-toggle-data-entry.ts
  src/react/core/create-component.ts
  src/visual-regression-app/package.json
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
  src/visual-regression-app/src/components/test-case/test-case.ts
  tools/eslint/index.ts
  tools/eslint/relative-imports-rule.ts
  tools/web-test-runner/configure-container-playwright-browser.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3539 fix(sbb-select, sbb-autocomplete): edge cases related to disabled property
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3541 fix(sbb-select): adapt trigger size in light DOM to be more flexible
  src/elements/core/styles/core.scss
  src/elements/paginator/paginator/__snapshots__/paginator.snapshot.spec.snap.js
  src/elements/select/select.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3524 style(sbb-table): add support to header filters
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/table.scss
  src/elements/table/table-wrapper/table-wrapper.scss
  src/elements/table/table-wrapper/table-wrapper.stories.ts
  src/storybook/styles/table/readme.md
  src/storybook/styles/table/table.stories.ts
  src/storybook/styles/table/table.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3536 build: use playwright containers in GitHub Actions environment
  .github/workflows/test.yml
  .github/workflows/visual-regression.yml
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3542 docs: remove deprecated 'date-picker' property from tests, stories and docs
  src/elements/datepicker/datepicker-next-day/__snapshots__/datepicker-next-day.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.snapshot.spec.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.stories.ts
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/__snapshots__/datepicker-previous-day.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.snapshot.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.stories.ts
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.stories.ts
  src/elements/datepicker/datepicker-toggle/readme.md
  src/elements/datepicker/datepicker/datepicker.stories.ts
  src/elements/datepicker/datepicker/datepicker.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3545 build: use correct host inside GitHub Actions container usage
  .github/workflows/visual-regression.yml
  tools/web-test-runner/visual-regression-plugin-config.ts
Labels: pr: peer review required, pr: visual review required, target: 2.x

#3544 refactor: remove async overrides to avoid changing signature
  src/elements/alert/alert/alert.ts
  src/elements/clock/clock.ts
  src/elements/core/mixins/form-associated-input-mixin.ts
  src/elements/image/image.ts
  src/elements/notification/notification.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/stepper/stepper/stepper.ts
  src/elements/toggle/toggle/toggle.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3508 fix(sbb-step): fix stepper height when content changes
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/stepper/step/step.ts
  src/elements/stepper/stepper/stepper.spec.ts
  src/elements/stepper/stepper/stepper.stories.ts
  src/elements/stepper/stepper/stepper.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3543 test: stabilize by calling waitForImageReady in postsetup
  src/elements/container/container/container.visual.spec.ts
  src/elements/flip-card/flip-card-summary/flip-card-summary.visual.spec.ts
  src/elements/flip-card/flip-card/flip-card.visual.spec.ts
  src/elements/image/image.visual.spec.ts
  src/elements/lead-container/lead-container.visual.spec.ts
  src/elements/message/message.visual.spec.ts
  src/elements/teaser-hero/teaser-hero.visual.spec.ts
  src/elements/teaser-product/teaser-product-static/teaser-product-static.visual.spec.ts
  src/elements/teaser-product/teaser-product/teaser-product.visual.spec.ts
  src/elements/teaser/teaser.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3547 test: fix image containing tests
  src/elements/core/testing/wait-for-image-ready.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3550 feat(sbb-seat-reservation-accessibillity-navigation): initial accessi…
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-service.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3557 fix: avoid duplicated entries in escape overlay stack
  src/elements/core/controllers/escapable-overlay-controller.ts
  src/elements/sidebar/sidebar/sidebar.component.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3558 build: remove font preloading
  scripts/preload-test-artifacts.ts
  tools/web-test-runner/index.ts
  tools/web-test-runner/preload-fonts.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3577 sk-sbb Fix imports in seat reservation web component
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3576 Seat reservation preselected places
  src/elements-experimental/seat-reservation/common/mapper/mapper.ts
  src/elements-experimental/seat-reservation/common/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
Labels: pr: peer review required

#3578 docs(sbb-status): document CSS color vars
  src/elements/status/readme.md
  src/elements/status/status.component.ts
  src/elements/status/status.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3575 fix(sbb-form-field): reduce z-index conflicts with other components
  src/elements/form-field/form-field/form-field.scss
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3561 feat(sbb-table-wrapper): add support for the sticky table
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/table.scss
  src/elements/table/table-wrapper/readme.md
  src/elements/table/table-wrapper/table-wrapper.component.ts
  src/elements/table/table-wrapper/table-wrapper.scss
  src/elements/table/table-wrapper/table-wrapper.spec.ts
  src/elements/table/table-wrapper/table-wrapper.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review required, pr: visual review required, diff-available, target: 2.x

#3581 fix(sbb-date-input): sync state with controls and datepicker
  src/elements/date-input/date-input.component.ts
  src/elements/datepicker/datepicker/datepicker.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, target: 2.x

#3583 test(sbb-table-wrapper): fix visual spec tests
  src/elements/table/table-wrapper/table-wrapper.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3594 Seat reservation scaling size
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3579 fix(sbb-form-field): improve look of input type number
  src/elements/core/styles/core.scss
  src/elements/date-input/date-input.scss
  src/elements/date-input/date-input.visual.spec.ts
  src/elements/form-field/form-field/form-field.scss
  src/elements/form-field/form-field/form-field.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3602 fix: use correct react import paths
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3601 chore: fix filename of id reference controller
  src/elements/core/controllers.ts
  src/elements/core/controllers/id-reference-controller.spec.ts
  src/elements/core/controllers/id-reference-controller.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3608 fix(sbb-icon): add extra-small dimension
  src/elements/icon/icon.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3596 sk-sbb Seat reservation fix import and sample data
  src/elements-experimental/seat-reservation/common.ts
  src/elements-experimental/seat-reservation/common/mapper/mapper.ts
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3616 feature/thm/vertical-navi
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3622 feat(sbb-paginator): add convenience methods
  src/elements/paginator/common/paginator-common.ts
  src/elements/paginator/compact-paginator/readme.md
  src/elements/paginator/paginator/paginator.spec.ts
  src/elements/paginator/paginator/readme.md
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3624 feat(sbb-table-wrapper): introduce focusable property
  src/elements/table/table-wrapper/__snapshots__/table-wrapper.snapshot.spec.snap.js
  src/elements/table/table-wrapper/readme.md
  src/elements/table/table-wrapper/table-wrapper.component.ts
  src/elements/table/table-wrapper/table-wrapper.scss
  src/elements/table/table-wrapper/table-wrapper.snapshot.spec.ts
  src/elements/table/table-wrapper/table-wrapper.spec.ts
  src/elements/table/table-wrapper/table-wrapper.stories.ts
  src/elements/table/table-wrapper/table-wrapper.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3615 fix(sbb-toggle): improve stacking
  src/elements/core/styles/core.scss
  src/elements/toggle/toggle-option/toggle-option.component.ts
  src/elements/toggle/toggle-option/toggle-option.scss
  src/elements/toggle/toggle/toggle.component.ts
  src/elements/toggle/toggle/toggle.scss
  src/elements/toggle/toggle/toggle.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3620 Seat reservation nav coach accessibillity
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
  src/elements-experimental/seat-reservation/seat-reservation/scoped-components/scoped-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3630 feature/thm/icon-adjustments
  src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
  src/elements-experimental/seat-reservation/common/svgs.ts
  src/elements-experimental/seat-reservation/common/svgs/layout-stair.svg
  src/elements-experimental/seat-reservation/common/svgs/service-bistro.svg
  src/elements-experimental/seat-reservation/common/svgs/service-business.svg
  src/elements-experimental/seat-reservation/common/svgs/service-family.svg
  src/elements-experimental/seat-reservation/common/svgs/service-restaurant.svg
  src/elements-experimental/seat-reservation/common/svgs/service-silence.svg
  src/elements-experimental/seat-reservation/common/svgs/service-wheelchair.svg
  src/elements-experimental/seat-reservation/common/svgs/service-wifi.svg
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
Labels: pr: peer review required

#3625 docs(sbb-table-wrapper): add section about focus outline color
  src/elements/table/table-wrapper/readme.md
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3629 fix(sbb-paginator): configure page event for lyne-angular
  src/elements/paginator/common/paginator-common.ts
  src/elements/paginator/compact-paginator/compact-paginator.spec.ts
  src/elements/paginator/paginator/paginator.component.ts
  src/elements/paginator/paginator/paginator.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3636 feat: provide CSS to globally disable animations
  docs/GETTING_STARTED.md
  src/elements/core/styles/disable-animation.scss
  src/elements/vite.config.ts
  tools/vite/typography.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3634 fix(sbb-image): support badge on image
  src/elements/header/common/header-action.scss
  src/elements/header/header-button/header-button.stories.ts
  src/elements/header/header-button/header-button.visual.spec.ts
  src/elements/header/header-button/readme.md
  src/elements/header/header-link/header-link.stories.ts
  src/elements/header/header-link/header-link.visual.spec.ts
  src/elements/header/header-link/readme.md
  src/elements/image/image.scss
  src/elements/image/image.stories.ts
  src/storybook/styles/badge/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3633 fix(sbb-select): strengthen value initialization
  src/elements/select/select.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3643 fix(sbb-date-input): validate on dateFilter change
  src/elements/date-input/date-input.component.ts
  src/elements/date-input/date-input.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3646 fix(sbb-chip-group): fix chip position when initialized with value
  src/elements/chip/chip-group/chip-group.component.ts
  src/elements/chip/chip-group/chip-group.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x
