Repository sbb-design-systems/lyne-components, pull requests merged in 2025-10, with the labels that each got.

#4085 feat(sbb-autocomplete-grid): enable `sbb-options-nowrap` class
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.scss
  src/elements/autocomplete-grid/autocomplete-grid-row/autocomplete-grid-row.scss
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.visual.spec.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/autocomplete/autocomplete.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4087 fix(sbb-carousel): fix scrolling when carousel is offset
  src/elements/carousel/carousel/carousel.component.ts
  src/elements/carousel/carousel/carousel.scss
  src/elements/carousel/carousel/carousel.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 3.x

#4095 chore(deps): remove deprecated @types/glob package
  package.json
  yarn.lock
Labels: pr: lead review approved, target: 3.x

#4078 fix(sbb-tab): fix height observer and animation
  src/elements/tabs/tab-group/__snapshots__/tab-group.snapshot.spec.snap.js
  src/elements/tabs/tab-group/readme.md
  src/elements/tabs/tab-group/tab-group.component.ts
  src/elements/tabs/tab-group/tab-group.scss
  src/elements/tabs/tab-group/tab-group.spec.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
  src/elements/tabs/tab-label/tab-label.component.ts
  src/elements/tabs/tab-label/tab-label.scss
  src/elements/tabs/tab/__snapshots__/tab.snapshot.spec.snap.js
  src/elements/tabs/tab/readme.md
  src/elements/tabs/tab/tab.component.ts
  src/elements/tabs/tab/tab.scss
  src/elements/tabs/tab/tab.stories.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 3.x
