Repository sbb-design-systems/lyne-components, pull requests merged in 2025-01, with the labels that each got.

#3329 fix(sbb-select): respect text node mutations for displayed value
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.ts
  src/elements/option/option/option-base-element.ts
  src/elements/select/select.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3334 fix(sbb-select): handle properties change
  src/elements/accordion/accordion.ts
  src/elements/core/mixins/disabled-mixin.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
  src/elements/toggle/toggle/toggle.ts
  src/elements/train/train-wagon/train-wagon.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3345 chore(deps): fix stylelint dep resolutions
  package.json
  yarn.lock
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: major

#3325 feat(sbb-dialog): introduce `backdrop` property to control backdrop density
  src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
  src/elements/dialog/dialog/dialog.scss
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/dialog/dialog/dialog.visual.spec.ts
  src/elements/dialog/dialog/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3341 feat(sbb-menu): improvements on arrow navigation
  src/elements/menu/menu/menu.spec.ts
  src/elements/menu/menu/menu.ts
  src/elements/menu/menu/readme.md
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3340 build: move icon templates into dedicated div
  web-test-runner.config.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3350 chore(sbb-menu): improve code comments
  src/elements/menu/menu/menu.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3339 fix: handle datepicker association reliably
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.ts
  src/elements/datepicker/common.ts
  src/elements/datepicker/common/datepicker-association-controllers.ts
  src/elements/datepicker/common/datepicker-button.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.spec.ts
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.spec.ts
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/datepicker/datepicker-toggle/readme.md
  src/elements/datepicker/datepicker/__snapshots__/datepicker.snapshot.spec.snap.js
  src/elements/datepicker/datepicker/datepicker.snapshot.spec.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/datepicker/datepicker/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3337 feat(sbb-container, sbb-sticky-bar): add new color variants
  src/elements/container/container/container.scss
  src/elements/container/container/container.stories.ts
  src/elements/container/container/container.ts
  src/elements/container/container/container.visual.spec.ts
  src/elements/container/container/readme.md
  src/elements/container/sticky-bar/readme.md
  src/elements/container/sticky-bar/sticky-bar.scss
  src/elements/container/sticky-bar/sticky-bar.stories.ts
  src/elements/container/sticky-bar/sticky-bar.ts
  src/elements/container/sticky-bar/sticky-bar.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3349 feat: improve stacking context for overlay components
  docs/GETTING_STARTED.md
  src/elements/autocomplete-grid/autocomplete-grid/__snapshots__/autocomplete-grid.snapshot.spec.snap.js
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete/__snapshots__/autocomplete.snapshot.spec.snap.js
  src/elements/autocomplete/autocomplete-base-element.scss
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/core/dom/scroll.ts
  src/elements/core/styles/core.scss
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
  src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
  src/elements/dialog/dialog/dialog.scss
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/menu/menu/__snapshots__/menu.snapshot.spec.snap.js
  src/elements/menu/menu/menu.spec.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/navigation-section/navigation-section.spec.ts
  src/elements/navigation/navigation/__snapshots__/navigation.snapshot.spec.snap.js
  src/elements/navigation/navigation/navigation.scss
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/overlay/__snapshots__/overlay.snapshot.spec.snap.js
  src/elements/overlay/overlay-base-element.ts
  src/elements/overlay/overlay.scss
  src/elements/overlay/overlay.spec.ts
  src/elements/overlay/overlay.ts
  src/elements/paginator/paginator/__snapshots__/paginator.snapshot.spec.snap.js
  src/elements/popover/popover/__snapshots__/popover.snapshot.spec.snap.js
  src/elements/popover/popover/popover.scss
  src/elements/popover/popover/popover.spec.ts
  src/elements/popover/popover/popover.ts
  src/elements/select/__snapshots__/select.snapshot.spec.snap.js
  src/elements/select/select.scss
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
  src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
  src/elements/toast/toast.scss
  src/elements/toast/toast.spec.ts
  src/elements/toast/toast.ts
  tsconfig.json
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3353 test(sbb-dialog): fix visual tests
  src/elements/dialog/dialog/dialog.visual.spec.ts
  src/elements/navigation/navigation-section/navigation-section.visual.spec.ts
  src/elements/navigation/navigation/navigation.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3355 fix: display non bubbling events in storybook actions
  .storybook/preview.ts
  src/elements/overlay/overlay-base-element.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3359 docs(sbb-popover): enable focusing link in storybook
  src/elements/core/a11y/focus.ts
  src/elements/popover/popover/popover.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3356 test: fix visual tests of overlays
  src/elements/core/styles/core.scss
  src/elements/dialog/dialog/dialog.visual.spec.ts
  src/elements/navigation/navigation-section/navigation-section.visual.spec.ts
  src/elements/navigation/navigation/navigation.visual.spec.ts
  src/elements/overlay/overlay.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3363 refactor(sbb-title, sbb-dialog-title): remove obsolete h1-h6 tags
  src/elements/dialog/dialog-title/__snapshots__/dialog-title.snapshot.spec.snap.js
  src/elements/title/__snapshots__/title.snapshot.spec.snap.js
  src/elements/title/title-base.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3365 feat(sbb-autocomplete): opens automatically on new options
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3371 fix(sbb-radio-button-group): prevent didChange emit from nested group
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3372 docs: fix typo in GETTING_STARTED.md
  docs/GETTING_STARTED.md
Labels: pr: peer review required

#3369 fix: avoid moving content when blocking scrolling
  src/elements/core/dom/scroll.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3326 refactor: prepare standalone usage of buttons
  src/elements/button/common/button-common.scss
  src/elements/button/common/primary-button.scss
  src/elements/button/common/secondary-button.scss
  src/elements/core/a11y/focus.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3376 fix(sbb-datepicker-toggle): allow defining slot attribute
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x
