Repository sbb-design-systems/lyne-components, pull requests merged in 2025-06, with the labels that each got.

#3769 feat(seat-reservation-improve-scroll-navigation): improved manual scr…
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available

#3772 feat(seat-reservation-css-cleanup): remove unnecessary css style
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required

#3777 chore(sbb-tab-group): move and adapt TODO about didChange event
  src/elements/tabs/tab-group/tab-group.component.ts
  src/elements/tabs/tab-group/tab-group.stories.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3776 refactor(datepicker): remove obsolete attribute checks
  src/elements/datepicker/common/datepicker-association-controllers.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: major

#3774 refactor(sbb-autocomplete,sbb-autocomplete-grid): remove return type `undefined` from triggerElement
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3779 fix(sbb-toast): replace property `dismissible` with `readOnly` and change logic
  src/elements/sidebar/sidebar-container/sidebar-container.spec.ts
  src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
  src/elements/toast/readme.md
  src/elements/toast/toast.component.ts
  src/elements/toast/toast.scss
  src/elements/toast/toast.snapshot.spec.ts
  src/elements/toast/toast.spec.ts
  src/elements/toast/toast.ssr.spec.ts
  src/elements/toast/toast.stories.ts
  src/elements/toast/toast.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available

#3711 feat(sbb-autocomplete, sbb-autocomplete-grid, sbb-select): add options size s
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.scss
  src/elements/autocomplete-grid/autocomplete-grid/__snapshots__/autocomplete-grid.snapshot.spec.snap.js
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/__snapshots__/autocomplete.snapshot.spec.snap.js
  src/elements/autocomplete/autocomplete-base-element.scss
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/readme.md
  src/elements/core/styles/core.scss
  src/elements/core/styles/mixins/overlay.scss
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/option/optgroup/optgroup-base-element.scss
  src/elements/option/option/option.component.ts
  src/elements/option/option/option.scss
  src/elements/paginator/paginator/__snapshots__/paginator.snapshot.spec.snap.js
  src/elements/select/__snapshots__/select.snapshot.spec.snap.js
  src/elements/select/readme.md
  src/elements/select/select.component.ts
  src/elements/select/select.scss
  src/elements/select/select.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3770 fix(sbb-sidebar): fix sidebar inline-padding on iOS browsers
  src/elements/sidebar/sidebar/sidebar.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3805 build: avoid deploying pre releases
  .github/workflows/release-please.yml
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3808 refactor: remove table border radius
  src/elements/core/styles/mixins/table.scss
  src/elements/table/table-wrapper/table-wrapper.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review required, pr: visual review required, diff-available, target: 2.x

#3809 fix(sbb-form-field): handle undefined inputElement
  src/elements/form-field/form-field/form-field.component.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: major

#3831 fix(sbb-notification): fix positioning of the icon
  src/elements/notification/notification.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3817 fix: improve translations
  src/elements-experimental/timetable-row/__snapshots__/timetable-row.snapshot.spec.snap.js
  src/elements/core/i18n/i18n.ts
  src/elements/timetable-occupancy/__snapshots__/timetable-occupancy.snapshot.spec.snap.js
  src/elements/train/train-wagon/train-wagon.spec.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3798 refactor(sbb-dialog): remove various properties and introduce trigger
  src/elements/core/styles/core.scss
  src/elements/dialog/dialog-actions/__snapshots__/dialog-actions.snapshot.spec.snap.js
  src/elements/dialog/dialog-actions/dialog-actions.component.ts
  src/elements/dialog/dialog-actions/dialog-actions.scss
  src/elements/dialog/dialog-actions/dialog-actions.stories.ts
  src/elements/dialog/dialog-actions/readme.md
  src/elements/dialog/dialog-content/__snapshots__/dialog-content.snapshot.spec.snap.js
  src/elements/dialog/dialog-content/dialog-content.component.ts
  src/elements/dialog/dialog-content/dialog-content.scss
  src/elements/dialog/dialog-content/dialog-content.stories.ts
  src/elements/dialog/dialog-title/__snapshots__/dialog-title.snapshot.spec.snap.js
  src/elements/dialog/dialog-title/dialog-title.component.ts
  src/elements/dialog/dialog-title/dialog-title.scss
  src/elements/dialog/dialog-title/dialog-title.spec.ts
  src/elements/dialog/dialog-title/dialog-title.ssr.spec.ts
  src/elements/dialog/dialog-title/dialog-title.stories.ts
  src/elements/dialog/dialog-title/readme.md
  src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
  src/elements/dialog/dialog/dialog.component.ts
  src/elements/dialog/dialog/dialog.scss
  src/elements/dialog/dialog/dialog.snapshot.spec.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/dialog/dialog/dialog.visual.spec.ts
  src/elements/dialog/dialog/readme.md
  src/elements/overlay/__snapshots__/overlay.snapshot.spec.snap.js
  src/elements/overlay/overlay-base-element.ts
  src/elements/overlay/overlay.component.ts
  src/elements/overlay/overlay.spec.ts
  src/elements/overlay/overlay.stories.ts
  src/elements/overlay/readme.md
  src/elements/select/select.spec.ts
  src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
  src/storybook/pages/home/home-logged-in.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: ux review required, pr: visual review required, diff-available

#3832 refactor: use correct modifiers for LitElement methods
  src/elements/autocomplete-grid/autocomplete-grid-button/autocomplete-grid-button.component.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.component.ts
  src/elements/core/mixins/element-internals-mixin.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.component.ts
  src/elements/toggle/toggle-option/toggle-option.component.ts
  src/storybook/helpers/spread.spec.ts
  src/visual-regression-app/src/components/overview/overview.ts
  src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
  src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
  src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
  src/visual-regression-app/src/components/test-case/test-case.ts
  src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.ts
  src/visual-regression-app/src/main.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: major

#3839 feat/thm/one-px-diff-font-sizes
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3844 feat(seat-reservation-cleanup-scoped-elements): cleanup for unnecessa…
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3847 fix: avoid parsing 0 day/month dates
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3843 fix(sbb-select): check null value on keyboard interaction
  src/elements/select/select.component.ts
  src/elements/select/select.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3851 refactor(sbb-overlay): remove back button
  src/elements/overlay/overlay.component.ts
  src/elements/overlay/overlay.stories.ts
  src/elements/overlay/overlay.visual.spec.ts
  src/elements/overlay/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3840 fix(sbb-popover): fix hover trigger functionality
  src/elements/popover/popover/popover.component.ts
  src/elements/popover/popover/popover.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3854 docs: link stackblitz starter projects
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/GETTING_STARTED.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3858 refactor(sbb-step, sbb-step-label): replace private setter by private method
  src/elements/stepper/step-label/step-label.component.ts
  src/elements/stepper/step/step.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: major

#3861 refactor: remove SbbValidationChangeEvent interface
  src/elements/core/interfaces.ts
  src/elements/core/interfaces/validation-change.ts
  tools/vite/generate-react-wrappers.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x
