Repository sbb-design-systems/lyne-components, pull requests merged in 2025-05, with the labels that each got.

#3648 fix(sbb-header): support header actions without icon
  src/elements/header/common/header-action-common.ts
  src/elements/header/common/header-action.scss
  src/elements/header/header-button/__snapshots__/header-button.snapshot.spec.snap.js
  src/elements/header/header-button/header-button.visual.spec.ts
  src/elements/header/header-button/readme.md
  src/elements/header/header-link/__snapshots__/header-link.snapshot.spec.snap.js
  src/elements/header/header-link/header-link.visual.spec.ts
  src/elements/header/header-link/readme.md
  src/elements/header/header/__snapshots__/header.snapshot.spec.snap.js
  src/elements/header/header/header.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3661 fix: avoid throwing on utf8 id reference
  src/elements/core/controllers/id-reference-controller.spec.ts
  src/elements/core/controllers/id-reference-controller.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3641 feat(seat-reservation-place-color-states): add color handling for dif…
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-default.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-selected.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-default.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-selected.svg
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3663 sekm Seat reservation web component fix import decorator
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
Labels: pr: peer review required

#3664 fix(sbb-toggle): fix animation glitches
  src/elements/toggle/toggle-option/toggle-option.component.ts
  src/elements/toggle/toggle-option/toggle-option.scss
  src/elements/toggle/toggle/__snapshots__/toggle.snapshot.spec.snap.js
  src/elements/toggle/toggle/toggle.component.ts
  src/elements/toggle/toggle/toggle.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3666 docs: fix broken docs
  src/elements/datepicker/datepicker/readme.md
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3652 refactor: adapt id reference properties to only accept element references
  src/elements/autocomplete-grid/autocomplete-grid-cell/__snapshots__/autocomplete-grid-cell.snapshot.spec.snap.js
  src/elements/autocomplete-grid/autocomplete-grid-cell/autocomplete-grid-cell.snapshot.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-optgroup/__snapshots__/autocomplete-grid-optgroup.snapshot.spec.snap.js
  src/elements/autocomplete-grid/autocomplete-grid-optgroup/autocomplete-grid-optgroup.snapshot.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-row/__snapshots__/autocomplete-grid-row.snapshot.spec.snap.js
  src/elements/autocomplete-grid/autocomplete-grid-row/autocomplete-grid-row.snapshot.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/readme.md
  src/elements/core/decorators.ts
  src/elements/core/decorators/id-reference.spec.ts
  src/elements/core/decorators/id-reference.ts
  src/elements/header/header/header.component.ts
  src/elements/header/header/header.spec.ts
  src/elements/header/header/readme.md
  src/elements/menu/menu/menu.component.ts
  src/elements/menu/menu/readme.md
  src/elements/navigation/navigation-section/navigation-section.component.ts
  src/elements/navigation/navigation-section/readme.md
  src/elements/navigation/navigation/navigation.component.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/navigation/navigation/readme.md
  src/elements/popover/popover/popover.component.ts
  src/elements/popover/popover/readme.md
  src/elements/time-input/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.spec.ts
  tools/eslint/decorator-order-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3670 fix(sbb-chip-group): avoid importing autocomplete component
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/chip/chip-group/chip-group.component.ts
  src/elements/chip/chip-group/chip-group.spec.ts
  src/elements/chip/chip-group/chip-group.stories.ts
  src/elements/chip/chip-group/chip-group.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3672 refactor: remove autocompleteOptionSelectionChange event
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.component.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid-option/readme.md
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/option/option/option-base-element.ts
  src/elements/option/option/option.component.ts
  src/elements/select/select.component.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available

#3673 fix(sbb-autocomplete, sbb-autocomplete-grid): recalculate panel's position on slotchange
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3679 Sbb seat reservation css customizing
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-default.svg
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
Labels: pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3677 refactor: remove SbbDateLike
  src/elements-experimental/journey-summary/journey-summary.component.ts
  src/elements-experimental/journey-summary/journey-summary.stories.ts
  src/elements-experimental/journey-summary/readme.md
  src/elements-experimental/pearl-chain-time/pearl-chain-time.component.ts
  src/elements-experimental/pearl-chain-time/pearl-chain-time.stories.ts
  src/elements-experimental/pearl-chain-time/pearl-chain-time.visual.spec.ts
  src/elements-experimental/pearl-chain-time/readme.md
  src/elements-experimental/pearl-chain/pearl-chain.component.ts
  src/elements-experimental/pearl-chain/pearl-chain.stories.ts
  src/elements-experimental/pearl-chain/pearl-chain.visual.spec.ts
  src/elements-experimental/pearl-chain/readme.md
  src/elements-experimental/timetable-row/readme.md
  src/elements-experimental/timetable-row/timetable-row.component.ts
  src/elements-experimental/timetable-row/timetable-row.stories.ts
  src/elements-experimental/timetable-row/timetable-row.visual.spec.ts
  src/elements/calendar/calendar.component.ts
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/readme.md
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.spec.ts
  src/elements/core/datetime/native-date-adapter.ts
  src/elements/core/decorators.ts
  src/elements/core/decorators/date-converter.ts
  src/elements/core/decorators/date-only-type.ts
  src/elements/core/decorators/plain-date.ts
  src/elements/core/interfaces/types.ts
  src/elements/date-input/date-input.component.ts
  src/elements/date-input/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.component.ts
  src/elements/datepicker/datepicker/datepicker.component.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.spec.ts
  tools/eslint/decorator-order-rule.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3680 feat(finalize-icon-images): final version for icon names
  src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
  src/elements-experimental/seat-reservation/common/svgs.ts
  src/elements-experimental/seat-reservation/common/svgs/layout-ski.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-wardrobe.svg
  src/elements-experimental/seat-reservation/common/svgs/service-luggage.svg
  src/elements-experimental/seat-reservation/common/svgs/service-multifunction.svg
  src/elements-experimental/seat-reservation/common/svgs/service-prm.svg
  src/elements-experimental/seat-reservation/common/svgs/service-toilet-prm.svg
  src/elements-experimental/seat-reservation/common/svgs/service-toilet.svg
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3681 origin/rotate-z
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3695 feat(sbb-autocomplete): add 'autoActiveFirstOption' property
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/autocomplete/readme.md
  src/elements/core/a11y/arrow-navigation.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3700 feat(sbb-autocomplete): add 'autoActiveFirstOption' property
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/autocomplete/readme.md
  src/elements/core/a11y/arrow-navigation.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3701 feature/thm/remove-css
  package.json
  src/elements-experimental/journey-summary/journey-summary.component.ts
  src/elements-experimental/journey-summary/journey-summary.stories.ts
  src/elements-experimental/journey-summary/readme.md
  src/elements-experimental/pearl-chain-time/pearl-chain-time.component.ts
  src/elements-experimental/pearl-chain-time/pearl-chain-time.stories.ts
  src/elements-experimental/pearl-chain-time/pearl-chain-time.visual.spec.ts
  src/elements-experimental/pearl-chain-time/readme.md
  src/elements-experimental/pearl-chain/pearl-chain.component.ts
  src/elements-experimental/pearl-chain/pearl-chain.stories.ts
  src/elements-experimental/pearl-chain/pearl-chain.visual.spec.ts
  src/elements-experimental/pearl-chain/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
  src/elements-experimental/timetable-row/readme.md
  src/elements-experimental/timetable-row/timetable-row.component.ts
  src/elements-experimental/timetable-row/timetable-row.stories.ts
  src/elements-experimental/timetable-row/timetable-row.visual.spec.ts
  src/elements/calendar/calendar.component.ts
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/readme.md
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.spec.ts
  src/elements/core/datetime/native-date-adapter.ts
  src/elements/core/decorators.ts
  src/elements/core/decorators/date-converter.ts
  src/elements/core/decorators/date-only-type.ts
  src/elements/core/decorators/plain-date.ts
  src/elements/core/interfaces/types.ts
  src/elements/date-input/date-input.component.ts
  src/elements/date-input/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.component.ts
  src/elements/datepicker/datepicker/datepicker.component.ts
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.spec.ts
  tools/eslint/decorator-order-rule.ts
  yarn.lock
Labels: pr: peer review required, pr: visual review required, diff-available

#3703 feat(seat-reservation-scrolling-widescreen): optimize handling select…
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3693 feat(seat-reservation-preselection): rebuild auto place preselection
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required

#3707 fix(sbb-journey-header): accessibility improvement
  src/elements/journey-header/__snapshots__/journey-header.snapshot.spec.snap.js
  src/elements/journey-header/journey-header.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3706 fix(sbb-toast): fix a11y on windows browsers
  src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
  src/elements/toast/toast.component.ts
  src/elements/toast/toast.snapshot.spec.ts
  src/elements/toast/toast.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: a11y review required, pr: visual review required, diff-available, target: 2.x

#3709 feat(latest-icons): refactored icon usage and translations
  src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3705 Seat reservation emit coach infos
  src/elements-experimental/seat-reservation/common/mapper/mapper.ts
  src/elements-experimental/seat-reservation/seat-reservation.ts
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3715 fix(sbb-timetable-row): avoid exception on accessibility message creation
  src/elements-experimental/timetable-row/timetable-row.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3698 fix(sbb-select, sbb-slider): display readonly state correctly if set by property
  src/elements/select/select.component.ts
  src/elements/slider/slider.component.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3716 fix(sbb-train-formation): fix focus outline of scroll container
  src/elements/train/train-formation/train-formation.scss
  src/elements/train/train-formation/train-formation.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3719 feature/thm/code-fixes
  src/elements-experimental/seat-reservation/common/svgs.ts
  src/elements-experimental/seat-reservation/common/svgs/chassis-tmp-row-empty.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-tmp-table.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-tmp-generic-space.svg
  src/elements-experimental/seat-reservation/seat-reservation-area/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation.ts
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required

#3717 feat(seat-reservation-place-extend-button): place control extends fro…
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
Labels: pr: peer review required, pr: visual review required

#3712 merge-commits
  CHANGELOG.md
  package.json
  src/elements-experimental/timetable-row/timetable-row.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
  src/elements/autocomplete-grid/autocomplete-grid/readme.md
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.component.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/autocomplete/autocomplete.stories.ts
  src/elements/autocomplete/readme.md
  src/elements/core/a11y/arrow-navigation.ts
  src/elements/core/dom/platform.ts
  src/elements/journey-header/__snapshots__/journey-header.snapshot.spec.snap.js
  src/elements/journey-header/journey-header.component.ts
  src/elements/select/select.component.ts
  src/elements/skiplink-list/__snapshots__/skiplink-list.snapshot.spec.snap.js
  src/elements/skiplink-list/skiplink-list.component.ts
  src/elements/skiplink-list/skiplink-list.scss
  src/elements/skiplink-list/skiplink-list.visual.spec.ts
  src/elements/slider/slider.component.ts
  src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
  src/elements/toast/toast.component.ts
  src/elements/toast/toast.snapshot.spec.ts
  src/elements/toast/toast.spec.ts
  src/elements/train/train-formation/train-formation.scss
  src/elements/train/train-formation/train-formation.visual.spec.ts
  yarn.lock
Labels: pr: peer review required, pr: visual review required, diff-available

#3725 Seat reservation autoscroll place focus
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3734 test: stabilize flaky tests
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/select/select.spec.ts
  src/elements/sidebar/sidebar-container/sidebar-container.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3731 fix(sbb-popover): improve the robustness of the initialization
  src/elements/popover/popover/popover.component.ts
  src/elements/popover/popover/popover.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3736 test: stabilize visual regression tests
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.visual.spec.ts
  src/elements/autocomplete/autocomplete.visual.spec.ts
  src/elements/sidebar/icon-sidebar/icon-sidebar.visual.spec.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3721 fix(sbb-skiplink-list): avoid invisible content block
  src/elements/skiplink-list/skiplink-list.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3735 feature/thm/code-fixes
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ssr.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/readme.md
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: visual review required, diff-available

#3686 refactor(sbb-time-input): convert sbb-time-input into an input element
  src/elements/core/a11y.ts
  src/elements/core/a11y/live-announcer.ts
  src/elements/core/base-elements/button-base-element.ts
  src/elements/core/controllers/inert-controller.ts
  src/elements/core/i18n/i18n.ts
  src/elements/core/mixins/form-associated-input-mixin.ts
  src/elements/core/styles/core.scss
  src/elements/core/testing/private/type-in-element.ts
  src/elements/date-input/readme.md
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/form-field/form-field/form-field.scss
  src/elements/time-input/__snapshots__/time-input.snapshot.spec.snap.js
  src/elements/time-input/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.scss
  src/elements/time-input/time-input.snapshot.spec.ts
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.ssr.spec.ts
  src/elements/time-input/time-input.stories.ts
  src/elements/time-input/time-input.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3744 fix(sbb-time-input): handle nullish values
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.spec.ts
Labels: pr: peer review required, pr: lead review approved, target: major

#3745 style(sbb-form-field): remove obsolete label property handling
  src/elements/form-field/form-field/form-field.scss
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3740 feat(seat-reservation-disabled-coaches): unavailable coaches are now …
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3746 commit-latest
  CHANGELOG.md
  package.json
  src/elements/alert/alert/alert.component.ts
  src/elements/alert/alert/readme.md
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.visual.spec.ts
  src/elements/autocomplete/autocomplete.visual.spec.ts
  src/elements/card/card/card.component.ts
  src/elements/card/card/card.spec.ts
  src/elements/card/card/card.stories.ts
  src/elements/card/card/readme.md
  src/elements/chip/chip-group/chip-group.component.ts
  src/elements/chip/chip-group/chip-group.spec.ts
  src/elements/chip/chip/chip.component.ts
  src/elements/chip/chip/chip.spec.ts
  src/elements/chip/chip/readme.md
  src/elements/core/a11y.ts
  src/elements/core/a11y/live-announcer.ts
  src/elements/core/base-elements/button-base-element.ts
  src/elements/core/controllers/inert-controller.ts
  src/elements/core/i18n/i18n.ts
  src/elements/core/mixins.ts
  src/elements/core/mixins/form-associated-input-mixin.ts
  src/elements/core/mixins/readonly-mixin.ts
  src/elements/core/styles/core.scss
  src/elements/core/testing/private/type-in-element.ts
  src/elements/date-input/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/form-field/form-field/form-field.component.ts
  src/elements/form-field/form-field/form-field.scss
  src/elements/notification/notification.component.ts
  src/elements/notification/notification.stories.ts
  src/elements/notification/readme.md
  src/elements/popover/popover/popover.component.ts
  src/elements/popover/popover/popover.spec.ts
  src/elements/select/readme.md
  src/elements/select/select.component.ts
  src/elements/select/select.spec.ts
  src/elements/sidebar/icon-sidebar/icon-sidebar.visual.spec.ts
  src/elements/sidebar/sidebar-container/sidebar-container.spec.ts
  src/elements/skiplink-list/skiplink-list.scss
  src/elements/slider/readme.md
  src/elements/slider/slider.component.ts
  src/elements/time-input/__snapshots__/time-input.snapshot.spec.snap.js
  src/elements/time-input/readme.md
  src/elements/time-input/time-input.component.ts
  src/elements/time-input/time-input.scss
  src/elements/time-input/time-input.snapshot.spec.ts
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.ssr.spec.ts
  src/elements/time-input/time-input.stories.ts
  src/elements/time-input/time-input.visual.spec.ts
  yarn.lock
Labels: pr: peer review required, pr: visual review required, diff-available

#3748 build: replace GH workflow action
  .github/workflows/maintenance-cherry-pick.yml
  .github/workflows/release-please.yml
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3747 feat(seat-reservation-coach-floor-color): add handling to set coach b…
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-bus.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-train-full.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-train.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-left-top.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-middle.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-right-bottom.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-waggon-bottom-right.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-waggon-top-left.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-row-middle.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-row-outer.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-separator.svg
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required, pr: a11y review required, pr: visual review required

#3714 feat(sbb-sticky-bar): add size s
  src/elements/container/sticky-bar/__snapshots__/sticky-bar.snapshot.spec.snap.js
  src/elements/container/sticky-bar/readme.md
  src/elements/container/sticky-bar/sticky-bar.component.ts
  src/elements/container/sticky-bar/sticky-bar.scss
  src/elements/container/sticky-bar/sticky-bar.stories.ts
  src/elements/container/sticky-bar/sticky-bar.visual.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3741 test(seat-reservation): add and fix tests
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/__snapshots__/seat-reservation-navigation-coach.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/__snapshots__/seat-reservation-navigation-services.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ssr.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.visual.spec.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3749 feat(seat-reservation-coach-wall-type): change graphical type to COAC…
  src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
  src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required, pr: visual review required, diff-available

#3753 feature/thm/-pr-feedback
  src/elements-experimental/seat-reservation/seat-reservation/scoped-components.ts
  src/elements-experimental/seat-reservation/seat-reservation/scoped-components/scoped-element.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped-component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped-component/readme.md
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped-component/seat-reservation-scoped.component.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-scoped-component/seat-reservation-scoped.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: preview-available, pr: peer review approved, pr: visual review required

#3755 feat(seat-reservation-customize-attr): add missing exportparts attrib…
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
Labels: pr: peer review required

#3754 refactor: improve init flow for components with '@idReference'
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/header/header/header.component.ts
  src/elements/menu/menu/menu.component.ts
  src/elements/menu/menu/menu.spec.ts
  src/elements/navigation/navigation-section/navigation-section.component.ts
  src/elements/navigation/navigation/navigation.component.ts
  src/elements/navigation/navigation/navigation.spec.ts
  src/elements/popover/popover/popover.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3733 refactor(sbb-paginator): avoid sending page events with identical details
  src/elements/paginator/common/paginator-common.ts
  src/elements/paginator/paginator/paginator.component.ts
  src/elements/paginator/paginator/paginator.spec.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3760 fix: remove deprecated symbols
  src/elements/_index.scss
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/core/a11y/focus.spec.ts
  src/elements/core/a11y/focus.ts
  src/elements/core/a11y/input-modality-detector.ts
  src/elements/core/a11y/interactivity-checker.ts
  src/elements/core/controllers.ts
  src/elements/core/controllers/connected-abort-controller.ts
  src/elements/core/dom.ts
  src/elements/core/dom/find-referenced-element.ts
  src/elements/core/dom/input-element.ts
  src/elements/core/eventing/forward-event.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/core/styles/mixins/lists.scss
  src/elements/core/styles/mixins/table.scss
  src/elements/core/styles/table.scss
  src/elements/core/testing.ts
  src/elements/core/testing/scroll.ts
  src/elements/datepicker/common/datepicker-button.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.component.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.component.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.component.ts
  src/elements/datepicker/datepicker/datepicker.component.ts
  src/elements/option/option/option-base-element.ts
  src/elements/overlay/overlay-base-element.ts
  src/elements/select/select.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available

#3764 refactor: assign slot via connectedCallback
  src/elements/card/common/card-action-common.ts
  src/elements/container/sticky-bar/sticky-bar.component.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.component.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.component.ts
  src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.component.ts
  src/elements/flip-card/flip-card-details/flip-card-details.component.ts
  src/elements/flip-card/flip-card-summary/flip-card-summary.component.ts
  src/elements/form-field/form-field-clear/form-field-clear.component.ts
  src/elements/navigation/navigation-section/navigation-section.component.ts
  src/elements/sidebar/sidebar-close-button/sidebar-close-button.component.ts
  src/elements/sidebar/sidebar-title/sidebar-title.component.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: major
