Repository sbb-design-systems/lyne-components, pull requests merged in 2025-03, with the labels that each got.

#3427 fix(sbb-checkbox-group, sbb-radio-button-group): fix panel detection and styling
  src/elements/checkbox/checkbox-group/__snapshots__/checkbox-group.snapshot.spec.snap.js
  src/elements/checkbox/checkbox-group/checkbox-group.snapshot.spec.ts
  src/elements/checkbox/checkbox-group/checkbox-group.spec.ts
  src/elements/checkbox/checkbox-group/checkbox-group.ts
  src/elements/core/mixins/panel-mixin.ts
  src/elements/radio-button/radio-button-group/__snapshots__/radio-button-group.snapshot.spec.snap.js
  src/elements/radio-button/radio-button-group/radio-button-group.snapshot.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3378 feat(sbb-calendar): vertical orientation
  src/elements/calendar/__snapshots__/calendar.snapshot.spec.snap.js
  src/elements/calendar/calendar.scss
  src/elements/calendar/calendar.snapshot.spec.ts
  src/elements/calendar/calendar.spec.ts
  src/elements/calendar/calendar.stories.ts
  src/elements/calendar/calendar.ts
  src/elements/calendar/calendar.visual.spec.ts
  src/elements/calendar/readme.md
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.spec.ts
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3430 fix(sbb-autocomplete): fix floating label flickering
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.spec.ts
  src/elements/form-field/form-field/form-field.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3432 build: fix code coverage generation
  tools/vite/typescript-transform.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3385 fix: close overlay stack with Escape key
  src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/autocomplete/autocomplete.ts
  src/elements/core/controllers.ts
  src/elements/core/controllers/escapable-overlay-controller.spec.ts
  src/elements/core/controllers/escapable-overlay-controller.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/dialog/dialog/dialog.ts
  src/elements/menu/menu/menu.ts
  src/elements/navigation/navigation/navigation.ts
  src/elements/overlay/overlay-base-element.ts
  src/elements/overlay/overlay.ts
  src/elements/popover/popover/popover.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3296 feat(date-input): create sbb-date-input as a native text input
  src/elements/core/datetime/date-adapter.ts
  src/elements/core/datetime/native-date-adapter.spec.ts
  src/elements/core/datetime/native-date-adapter.ts
  src/elements/core/decorators.ts
  src/elements/core/decorators/date-converter.ts
  src/elements/core/decorators/date-only-type.ts
  src/elements/core/decorators/force-type.ts
  src/elements/core/dom/input-element.ts
  src/elements/core/i18n/i18n.ts
  src/elements/core/mixins.ts
  src/elements/core/mixins/form-associated-checkbox-mixin.ts
  src/elements/core/mixins/form-associated-input-mixin.ts
  src/elements/core/mixins/form-associated-mixin.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/core/styles/core.scss
  src/elements/core/testing/private/type-in-element.ts
  src/elements/date-input.ts
  src/elements/date-input/__snapshots__/date-input.snapshot.spec.snap.js
  src/elements/date-input/date-input.scss
  src/elements/date-input/date-input.snapshot.spec.ts
  src/elements/date-input/date-input.spec.ts
  src/elements/date-input/date-input.ssr.spec.ts
  src/elements/date-input/date-input.stories.ts
  src/elements/date-input/date-input.ts
  src/elements/date-input/date-input.visual.spec.ts
  src/elements/date-input/readme.md
  src/elements/datepicker/common/datepicker-button.ts
  src/elements/datepicker/datepicker-next-day/__snapshots__/datepicker-next-day.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.snapshot.spec.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.spec.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.stories.ts
  src/elements/datepicker/datepicker-next-day/datepicker-next-day.visual.spec.ts
  src/elements/datepicker/datepicker-next-day/readme.md
  src/elements/datepicker/datepicker-previous-day/__snapshots__/datepicker-previous-day.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.snapshot.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.spec.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.stories.ts
  src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.visual.spec.ts
  src/elements/datepicker/datepicker-previous-day/readme.md
  src/elements/datepicker/datepicker-toggle/__snapshots__/datepicker-toggle.snapshot.spec.snap.js
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.snapshot.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.stories.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.visual.spec.ts
  src/elements/datepicker/datepicker-toggle/readme.md
  src/elements/datepicker/datepicker/datepicker.spec.ts
  src/elements/datepicker/datepicker/datepicker.ssr.spec.ts
  src/elements/datepicker/datepicker/datepicker.stories.ts
  src/elements/datepicker/datepicker/datepicker.ts
  src/elements/datepicker/datepicker/datepicker.visual.spec.ts
  src/elements/datepicker/datepicker/readme.md
  src/elements/form-field/form-field/form-field.scss
  src/elements/form-field/form-field/form-field.ts
  src/elements/select/select.ts
  tools/docs/docs_generate.ts
  web-test-runner.config.ts
Labels: pr: peer review required, pr: lead review approved, pr: visual review required, target: 2.x

#3429 fix(sbb-stepper): marker not visible in stepper
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/stepper/step/step.ts
  src/elements/stepper/stepper/stepper.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3445 feature/thm/seat-reservation-navigation
  src/elements-experimental/seat-reservation/common/aria-label.ts
  src/elements-experimental/seat-reservation/common/mapper.ts
  src/elements-experimental/seat-reservation/common/navigation-icon-mapper.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.snapshot.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ssr.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.stories.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.visual.spec.ts
  src/elements-experimental/seat-reservation/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3448 fix(sbb-time-input): connect input
  src/elements/time-input/time-input.spec.ts
  src/elements/time-input/time-input.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3451 feat(sbb-seat-reservation-navigation): i18n implementation
  src/elements-experimental/seat-reservation/common/aria-label.ts
  src/elements-experimental/seat-reservation/common/i18n/i18n.ts
  src/elements-experimental/seat-reservation/common/index.ts
  src/elements-experimental/seat-reservation/common/navigation-icon-mapper.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
  src/elements-experimental/seat-reservation/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3458 fix(sbb-clock): fix de-sync on long-running use cases
  src/elements/clock/clock.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3462 feat(sbb-seat-reservation-inline-css): move inline styles to <style>-Block
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
Labels: pr: peer review required

#3442 feat(sbb-stepper): fix wrong stepper height
  src/elements/dialog/dialog/dialog.stories.ts
  src/elements/stepper/step/step.scss
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3457 fix(sbb-datepicker): update datepicker-toggle's calendar when wide/dateFilter are updated
  src/elements/date-input/date-input.spec.ts
  src/elements/date-input/date-input.ts
  src/elements/date-input/readme.md
  src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
  src/elements/datepicker/datepicker/datepicker.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3471 seat-reservation-high-contrast-mode
  src/elements-experimental/seat-reservation/assets/chassis-driver-bus.svg
  src/elements-experimental/seat-reservation/assets/chassis-driver-train-full.svg
  src/elements-experimental/seat-reservation/assets/chassis-passage-compartment-middle.svg
  src/elements-experimental/seat-reservation/assets/chassis-passage-waggon-bottom-right.svg
  src/elements-experimental/seat-reservation/assets/chassis-passage-waggon-top-left.svg
  src/elements-experimental/seat-reservation/assets/chassis-row-middle.svg
  src/elements-experimental/seat-reservation/assets/chassis-row-outer.svg
  src/elements-experimental/seat-reservation/assets/interior-place-bike-default.svg
  src/elements-experimental/seat-reservation/assets/interior-place-bike-selected.svg
  src/elements-experimental/seat-reservation/assets/interior-place-seat-default.svg
  src/elements-experimental/seat-reservation/assets/interior-place-seat-selected.svg
  src/elements-experimental/seat-reservation/assets/service-bistro.svg
  src/elements-experimental/seat-reservation/assets/service-business.svg
  src/elements-experimental/seat-reservation/assets/service-family.svg
  src/elements-experimental/seat-reservation/assets/service-luggage.svg
  src/elements-experimental/seat-reservation/assets/service-multifunction.svg
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.scss
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
Labels: pr: peer review required

#3472 fix(buttons): fix various colors
  src/elements/button/accent-button-link/accent-button-link.stories.ts
  src/elements/button/accent-button-static/accent-button-static.stories.ts
  src/elements/button/accent-button/accent-button.stories.ts
  src/elements/button/accent-button/accent-button.visual.spec.ts
  src/elements/button/button-link/button-link.stories.ts
  src/elements/button/button-link/button-link.visual.spec.ts
  src/elements/button/button-static/button-static.stories.ts
  src/elements/button/button/button.stories.ts
  src/elements/button/button/button.visual.spec.ts
  src/elements/button/common/primary-button.scss
  src/elements/button/common/secondary-button.scss
  src/elements/button/common/transparent-button.scss
  src/elements/button/secondary-button-link/secondary-button-link.stories.ts
  src/elements/button/secondary-button-static/secondary-button-static.stories.ts
  src/elements/button/secondary-button/secondary-button.stories.ts
  src/elements/button/secondary-button/secondary-button.visual.spec.ts
Labels: preview-available, ux approved, pr: peer review required, pr: ux review approved, pr: visual review required, diff-available, target: 2.x

#3477 build: update Node.js version
  .nvmrc
  src/elements/core/testing/private/fixture.ts
  web-test-runner.config.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3476 build: update eslint plugin configuration
  eslint.config.js
  package.json
  scripts/migrate-ssr-e2e.ts
  scripts/migrate-ssr.ts
  scripts/migrate-toggle-data-entry.ts
  src/react/core/create-component.ts
  tools/eslint/index.ts
  tools/web-test-runner/configure-container-playwright-browser.ts
  yarn.lock
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3480 feat(sbb-seat-reservation-mock-data): add several mock data
  src/elements-experimental/seat-reservation/common/mapper.ts
  src/elements-experimental/seat-reservation/seat-reservation-sample-data.ts
Labels: pr: peer review required

#3487 fix(sbb-select): update displayed value on option slot change
  src/elements/form-field/form-field/form-field.ts
  src/elements/select/select.spec.ts
  src/elements/select/select.ts
Labels: preview-available, pr: peer review approved, pr: visual review required, diff-available, target: 2.x

#3492 refactor: use hasUpdated where possible
  src/elements/autocomplete/autocomplete-base-element.ts
  src/elements/core/mixins/form-associated-radio-button-mixin.ts
  src/elements/radio-button/radio-button-group/radio-button-group.ts
  src/elements/stepper/step/step.ts
Labels: preview-available, pr: peer review approved, pr: lead review approved, pr: visual review required, diff-available, target: 2.x

#3490 fix(sbb-date-input): display initially set value
  src/elements/core/dom/platform.ts
  src/elements/core/mixins/form-associated-input-mixin.ts
  src/elements/date-input/date-input.spec.ts
Labels: pr: peer review required, pr: visual review required, target: 2.x

#3495 feat(sbb-seat-reservation-fix-build): fix build error while using subdirectories
  src/elements-experimental/seat-reservation/common.ts
  src/elements-experimental/seat-reservation/common/index.ts
  src/elements-experimental/seat-reservation/common/translations.ts
  src/elements-experimental/seat-reservation/common/translations/i18n.ts
Labels: pr: peer review required

#3497 build: disable automatic Gemini code review
  .gemini/config.yaml
Labels: pr: peer review required, pr: lead review approved, target: 2.x

#3482 test: increase timeout for flaky ssr test
  src/elements-experimental/journey-summary/journey-summary.ssr.spec.ts
  src/elements-experimental/timetable-row/timetable-row.ssr.spec.ts
Labels: preview-available, pr: peer review required, pr: visual review required, diff-available, target: 2.x

#3481 build: add size check for GitHub CI
  .github/workflows/continuous-integration-secure.yml
  package.json
  scripts/calculate-stats.ts
  scripts/compare-stats.ts
  yarn.lock
Labels: pr: peer review approved, pr: lead review approved, pr: visual review required, target: 2.x

#3501 fix: make seat reservation web component usable
  src/elements-experimental/seat-reservation/assets.ts
  src/elements-experimental/seat-reservation/assets/index.ts
  src/elements-experimental/seat-reservation/common.ts
  src/elements-experimental/seat-reservation/common/mapper.ts
  src/elements-experimental/seat-reservation/common/seat-reservation-sample-data.ts
  src/elements-experimental/seat-reservation/common/svgs.ts
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-bus.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-train-full.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-driver-train.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-left-top.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-middle.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-compartment-right-bottom.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-waggon-bottom-right.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-passage-waggon-top-left.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-row-middle.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-row-outer.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-separator.svg
  src/elements-experimental/seat-reservation/common/svgs/chassis-tmp-row-empty.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-default.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-not-bookable.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-selected.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-bike-unavailable.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-default.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-not-bookable.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-selected.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-place-seat-unavailable.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-table.svg
  src/elements-experimental/seat-reservation/common/svgs/interior-tmp-table.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-entrance.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-ski.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-stair.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-tmp-generic-space.svg
  src/elements-experimental/seat-reservation/common/svgs/layout-wardrobe.svg
  src/elements-experimental/seat-reservation/common/svgs/service-bistro.svg
  src/elements-experimental/seat-reservation/common/svgs/service-business.svg
  src/elements-experimental/seat-reservation/common/svgs/service-family.svg
  src/elements-experimental/seat-reservation/common/svgs/service-luggage.svg
  src/elements-experimental/seat-reservation/common/svgs/service-multifunction.svg
  src/elements-experimental/seat-reservation/common/svgs/service-pram.svg
  src/elements-experimental/seat-reservation/common/svgs/service-prm.svg
  src/elements-experimental/seat-reservation/common/svgs/service-restaurant.svg
  src/elements-experimental/seat-reservation/common/svgs/service-silence.svg
  src/elements-experimental/seat-reservation/common/svgs/service-toilet-prm.svg
  src/elements-experimental/seat-reservation/common/svgs/service-toilet.svg
  src/elements-experimental/seat-reservation/common/svgs/service-wheelchair.svg
  src/elements-experimental/seat-reservation/common/svgs/service-wifi.svg
  src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
Labels: pr: peer review required

#3488 build: configure tests to be run as matrix
  .github/workflows/build-secure.yml
  .github/workflows/build.yml
  .github/workflows/continuous-integration-requested.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/test-secure.yml
  .github/workflows/test.yml
  .github/workflows/visual-regression-secure.yml
  .github/workflows/visual-regression.yml
  package.json
  scripts/preload-test-artifacts.ts
  src/elements/core/testing/test-setup.ts
  src/elements/dialog/dialog/dialog.spec.ts
  src/elements/sidebar/sidebar-container/sidebar-container.spec.ts
  tools/web-test-runner/preload-fonts.ts
  tools/web-test-runner/preload-icons.ts
  web-test-runner.config.ts
  yarn.lock
Labels: pr: peer review required, target: 2.x

#3499 feat(sbb-seat-reservation-fix-wcagii-violation): fix violation
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
Labels: pr: peer review required

#3504 seat-reservation-web-component-add-interfaces
  src/elements-experimental/seat-reservation/common/mapper.ts
  src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
  src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
  src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
  tools/vite/generate-react-wrappers.ts
Labels: pr: peer review required

#3506 refactor(sbb-date-input): feature detect plaintext-only support
  src/elements/core/mixins/form-associated-input-mixin.ts
Labels: preview-available, pr: peer review required, pr: lead review approved, pr: visual review required, diff-available, target: 2.x
